/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufAirPlay.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufAirPlay.dylib/libAWDProtobufAirPlay.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDAirPlayAudioSessionEndedOnClient : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _duration;
	unsigned _futileRetransmits;
	int _reason;
	unsigned _retransmits;
	NSString* _sessionUUID;
	unsigned _slowKeepAlives;
	SCD_Struct_AW3 _has;

}

@property (nonatomic,readonly) bool hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                    //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasReason; 
@property (assign,nonatomic) int reason;                                //@synthesize reason=_reason - In the implementation block
@property (assign,nonatomic) bool hasDuration; 
@property (assign,nonatomic) unsigned duration;                         //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) bool hasSlowKeepAlives; 
@property (assign,nonatomic) unsigned slowKeepAlives;                   //@synthesize slowKeepAlives=_slowKeepAlives - In the implementation block
@property (assign,nonatomic) bool hasRetransmits; 
@property (assign,nonatomic) unsigned retransmits;                      //@synthesize retransmits=_retransmits - In the implementation block
@property (assign,nonatomic) bool hasFutileRetransmits; 
@property (assign,nonatomic) unsigned futileRetransmits;                //@synthesize futileRetransmits=_futileRetransmits - In the implementation block
-(void)setReason:(int)arg1 ;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(unsigned)duration;
-(void)setDuration:(unsigned)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(int)reason;
-(void)setSessionUUID:(id)arg1 ;
-(void)setSlowKeepAlives:(unsigned)arg1 ;
-(void)setRetransmits:(unsigned)arg1 ;
-(void)setFutileRetransmits:(unsigned)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(bool)hasDuration;
-(void)setHasDuration:(bool)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(bool)hasSessionUUID;
-(id)sessionUUID;
-(void)setHasSlowKeepAlives:(bool)arg1 ;
-(bool)hasSlowKeepAlives;
-(void)setHasRetransmits:(bool)arg1 ;
-(bool)hasRetransmits;
-(void)setHasFutileRetransmits:(bool)arg1 ;
-(bool)hasFutileRetransmits;
-(unsigned)slowKeepAlives;
-(unsigned)retransmits;
-(unsigned)futileRetransmits;
-(void)setHasReason:(bool)arg1 ;
-(bool)hasReason;
@end

