/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufAirPlay.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufAirPlay.dylib/libAWDProtobufAirPlay.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDAirPlayAudioSessionEndedOnServer : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _bigLosses;
	unsigned _compressionPercent;
	unsigned _dacpNext;
	unsigned _dacpPauses;
	unsigned _dacpPrevious;
	unsigned _duration;
	unsigned _futileRetransmits;
	unsigned _glitches;
	unsigned _lastPackets;
	unsigned _lostPackets;
	unsigned _maxBurstLoss;
	unsigned _ntpOffsetAvg;
	unsigned _ntpOffsetMax;
	unsigned _ntpOffsetMin;
	unsigned _ntpOutliers;
	unsigned _ntpRTTAvg;
	unsigned _ntpRTTMax;
	unsigned _ntpRTTMin;
	unsigned _ntpSteps;
	int _reason;
	unsigned _retransmitAvgMs;
	unsigned _retransmitMaxMs;
	unsigned _retransmitMinMs;
	unsigned _retransmitNotFounds;
	unsigned _retransmitReceives;
	unsigned _retransmitRetryMaxMs;
	unsigned _retransmitRetryMinMs;
	unsigned _retransmitSends;
	unsigned _rtpMaxSkew;
	unsigned _rtpSkewResets;
	NSString* _sessionUUID;
	unsigned _unrecoveredPackets;
	SCD_Struct_AW4 _has;

}

@property (nonatomic,readonly) bool hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                     //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasReason; 
@property (assign,nonatomic) int reason;                                 //@synthesize reason=_reason - In the implementation block
@property (assign,nonatomic) bool hasDuration; 
@property (assign,nonatomic) unsigned duration;                          //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) bool hasCompressionPercent; 
@property (assign,nonatomic) unsigned compressionPercent;                //@synthesize compressionPercent=_compressionPercent - In the implementation block
@property (assign,nonatomic) bool hasGlitches; 
@property (assign,nonatomic) unsigned glitches;                          //@synthesize glitches=_glitches - In the implementation block
@property (assign,nonatomic) bool hasRetransmitSends; 
@property (assign,nonatomic) unsigned retransmitSends;                   //@synthesize retransmitSends=_retransmitSends - In the implementation block
@property (assign,nonatomic) bool hasRetransmitReceives; 
@property (assign,nonatomic) unsigned retransmitReceives;                //@synthesize retransmitReceives=_retransmitReceives - In the implementation block
@property (assign,nonatomic) bool hasFutileRetransmits; 
@property (assign,nonatomic) unsigned futileRetransmits;                 //@synthesize futileRetransmits=_futileRetransmits - In the implementation block
@property (assign,nonatomic) bool hasRetransmitNotFounds; 
@property (assign,nonatomic) unsigned retransmitNotFounds;               //@synthesize retransmitNotFounds=_retransmitNotFounds - In the implementation block
@property (assign,nonatomic) bool hasRetransmitMinMs; 
@property (assign,nonatomic) unsigned retransmitMinMs;                   //@synthesize retransmitMinMs=_retransmitMinMs - In the implementation block
@property (assign,nonatomic) bool hasRetransmitMaxMs; 
@property (assign,nonatomic) unsigned retransmitMaxMs;                   //@synthesize retransmitMaxMs=_retransmitMaxMs - In the implementation block
@property (assign,nonatomic) bool hasRetransmitAvgMs; 
@property (assign,nonatomic) unsigned retransmitAvgMs;                   //@synthesize retransmitAvgMs=_retransmitAvgMs - In the implementation block
@property (assign,nonatomic) bool hasRetransmitRetryMinMs; 
@property (assign,nonatomic) unsigned retransmitRetryMinMs;              //@synthesize retransmitRetryMinMs=_retransmitRetryMinMs - In the implementation block
@property (assign,nonatomic) bool hasRetransmitRetryMaxMs; 
@property (assign,nonatomic) unsigned retransmitRetryMaxMs;              //@synthesize retransmitRetryMaxMs=_retransmitRetryMaxMs - In the implementation block
@property (assign,nonatomic) bool hasLostPackets; 
@property (assign,nonatomic) unsigned lostPackets;                       //@synthesize lostPackets=_lostPackets - In the implementation block
@property (assign,nonatomic) bool hasUnrecoveredPackets; 
@property (assign,nonatomic) unsigned unrecoveredPackets;                //@synthesize unrecoveredPackets=_unrecoveredPackets - In the implementation block
@property (assign,nonatomic) bool hasLastPackets; 
@property (assign,nonatomic) unsigned lastPackets;                       //@synthesize lastPackets=_lastPackets - In the implementation block
@property (assign,nonatomic) bool hasMaxBurstLoss; 
@property (assign,nonatomic) unsigned maxBurstLoss;                      //@synthesize maxBurstLoss=_maxBurstLoss - In the implementation block
@property (assign,nonatomic) bool hasBigLosses; 
@property (assign,nonatomic) unsigned bigLosses;                         //@synthesize bigLosses=_bigLosses - In the implementation block
@property (assign,nonatomic) bool hasNtpRTTMin; 
@property (assign,nonatomic) unsigned ntpRTTMin;                         //@synthesize ntpRTTMin=_ntpRTTMin - In the implementation block
@property (assign,nonatomic) bool hasNtpRTTMax; 
@property (assign,nonatomic) unsigned ntpRTTMax;                         //@synthesize ntpRTTMax=_ntpRTTMax - In the implementation block
@property (assign,nonatomic) bool hasNtpRTTAvg; 
@property (assign,nonatomic) unsigned ntpRTTAvg;                         //@synthesize ntpRTTAvg=_ntpRTTAvg - In the implementation block
@property (assign,nonatomic) bool hasNtpOffsetMin; 
@property (assign,nonatomic) unsigned ntpOffsetMin;                      //@synthesize ntpOffsetMin=_ntpOffsetMin - In the implementation block
@property (assign,nonatomic) bool hasNtpOffsetMax; 
@property (assign,nonatomic) unsigned ntpOffsetMax;                      //@synthesize ntpOffsetMax=_ntpOffsetMax - In the implementation block
@property (assign,nonatomic) bool hasNtpOffsetAvg; 
@property (assign,nonatomic) unsigned ntpOffsetAvg;                      //@synthesize ntpOffsetAvg=_ntpOffsetAvg - In the implementation block
@property (assign,nonatomic) bool hasNtpOutliers; 
@property (assign,nonatomic) unsigned ntpOutliers;                       //@synthesize ntpOutliers=_ntpOutliers - In the implementation block
@property (assign,nonatomic) bool hasNtpSteps; 
@property (assign,nonatomic) unsigned ntpSteps;                          //@synthesize ntpSteps=_ntpSteps - In the implementation block
@property (assign,nonatomic) bool hasRtpMaxSkew; 
@property (assign,nonatomic) unsigned rtpMaxSkew;                        //@synthesize rtpMaxSkew=_rtpMaxSkew - In the implementation block
@property (assign,nonatomic) bool hasRtpSkewResets; 
@property (assign,nonatomic) unsigned rtpSkewResets;                     //@synthesize rtpSkewResets=_rtpSkewResets - In the implementation block
@property (assign,nonatomic) bool hasDacpPauses; 
@property (assign,nonatomic) unsigned dacpPauses;                        //@synthesize dacpPauses=_dacpPauses - In the implementation block
@property (assign,nonatomic) bool hasDacpNext; 
@property (assign,nonatomic) unsigned dacpNext;                          //@synthesize dacpNext=_dacpNext - In the implementation block
@property (assign,nonatomic) bool hasDacpPrevious; 
@property (assign,nonatomic) unsigned dacpPrevious;                      //@synthesize dacpPrevious=_dacpPrevious - In the implementation block
-(void)setReason:(int)arg1 ;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(unsigned)duration;
-(void)setDuration:(unsigned)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(int)reason;
-(void)setSessionUUID:(id)arg1 ;
-(void)setFutileRetransmits:(unsigned)arg1 ;
-(void)setCompressionPercent:(unsigned)arg1 ;
-(void)setGlitches:(unsigned)arg1 ;
-(void)setRetransmitSends:(unsigned)arg1 ;
-(void)setRetransmitReceives:(unsigned)arg1 ;
-(void)setRetransmitNotFounds:(unsigned)arg1 ;
-(void)setRetransmitMinMs:(unsigned)arg1 ;
-(void)setRetransmitMaxMs:(unsigned)arg1 ;
-(void)setRetransmitAvgMs:(unsigned)arg1 ;
-(void)setRetransmitRetryMinMs:(unsigned)arg1 ;
-(void)setRetransmitRetryMaxMs:(unsigned)arg1 ;
-(void)setLostPackets:(unsigned)arg1 ;
-(void)setUnrecoveredPackets:(unsigned)arg1 ;
-(void)setLastPackets:(unsigned)arg1 ;
-(void)setMaxBurstLoss:(unsigned)arg1 ;
-(void)setBigLosses:(unsigned)arg1 ;
-(void)setNtpRTTMin:(unsigned)arg1 ;
-(void)setNtpRTTMax:(unsigned)arg1 ;
-(void)setNtpRTTAvg:(unsigned)arg1 ;
-(void)setNtpOffsetMin:(unsigned)arg1 ;
-(void)setNtpOffsetMax:(unsigned)arg1 ;
-(void)setNtpOffsetAvg:(unsigned)arg1 ;
-(void)setNtpOutliers:(unsigned)arg1 ;
-(void)setNtpSteps:(unsigned)arg1 ;
-(void)setRtpMaxSkew:(unsigned)arg1 ;
-(void)setRtpSkewResets:(unsigned)arg1 ;
-(void)setDacpPauses:(unsigned)arg1 ;
-(void)setDacpNext:(unsigned)arg1 ;
-(void)setDacpPrevious:(unsigned)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(bool)hasDuration;
-(void)setHasDuration:(bool)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(bool)hasSessionUUID;
-(id)sessionUUID;
-(void)setHasFutileRetransmits:(bool)arg1 ;
-(bool)hasFutileRetransmits;
-(unsigned)futileRetransmits;
-(void)setHasCompressionPercent:(bool)arg1 ;
-(bool)hasCompressionPercent;
-(void)setHasGlitches:(bool)arg1 ;
-(bool)hasGlitches;
-(void)setHasRetransmitSends:(bool)arg1 ;
-(bool)hasRetransmitSends;
-(void)setHasRetransmitReceives:(bool)arg1 ;
-(bool)hasRetransmitReceives;
-(void)setHasRetransmitNotFounds:(bool)arg1 ;
-(bool)hasRetransmitNotFounds;
-(void)setHasRetransmitMinMs:(bool)arg1 ;
-(bool)hasRetransmitMinMs;
-(void)setHasRetransmitMaxMs:(bool)arg1 ;
-(bool)hasRetransmitMaxMs;
-(void)setHasRetransmitAvgMs:(bool)arg1 ;
-(bool)hasRetransmitAvgMs;
-(void)setHasRetransmitRetryMinMs:(bool)arg1 ;
-(bool)hasRetransmitRetryMinMs;
-(void)setHasRetransmitRetryMaxMs:(bool)arg1 ;
-(bool)hasRetransmitRetryMaxMs;
-(void)setHasLostPackets:(bool)arg1 ;
-(bool)hasLostPackets;
-(void)setHasUnrecoveredPackets:(bool)arg1 ;
-(bool)hasUnrecoveredPackets;
-(void)setHasLastPackets:(bool)arg1 ;
-(bool)hasLastPackets;
-(void)setHasMaxBurstLoss:(bool)arg1 ;
-(bool)hasMaxBurstLoss;
-(void)setHasBigLosses:(bool)arg1 ;
-(bool)hasBigLosses;
-(void)setHasNtpRTTMin:(bool)arg1 ;
-(bool)hasNtpRTTMin;
-(void)setHasNtpRTTMax:(bool)arg1 ;
-(bool)hasNtpRTTMax;
-(void)setHasNtpRTTAvg:(bool)arg1 ;
-(bool)hasNtpRTTAvg;
-(void)setHasNtpOffsetMin:(bool)arg1 ;
-(bool)hasNtpOffsetMin;
-(void)setHasNtpOffsetMax:(bool)arg1 ;
-(bool)hasNtpOffsetMax;
-(void)setHasNtpOffsetAvg:(bool)arg1 ;
-(bool)hasNtpOffsetAvg;
-(void)setHasNtpOutliers:(bool)arg1 ;
-(bool)hasNtpOutliers;
-(void)setHasNtpSteps:(bool)arg1 ;
-(bool)hasNtpSteps;
-(void)setHasRtpMaxSkew:(bool)arg1 ;
-(bool)hasRtpMaxSkew;
-(void)setHasRtpSkewResets:(bool)arg1 ;
-(bool)hasRtpSkewResets;
-(void)setHasDacpPauses:(bool)arg1 ;
-(bool)hasDacpPauses;
-(void)setHasDacpNext:(bool)arg1 ;
-(bool)hasDacpNext;
-(void)setHasDacpPrevious:(bool)arg1 ;
-(bool)hasDacpPrevious;
-(unsigned)compressionPercent;
-(unsigned)glitches;
-(unsigned)retransmitSends;
-(unsigned)retransmitReceives;
-(unsigned)retransmitNotFounds;
-(unsigned)retransmitMinMs;
-(unsigned)retransmitMaxMs;
-(unsigned)retransmitAvgMs;
-(unsigned)retransmitRetryMinMs;
-(unsigned)retransmitRetryMaxMs;
-(unsigned)lostPackets;
-(unsigned)unrecoveredPackets;
-(unsigned)lastPackets;
-(unsigned)maxBurstLoss;
-(unsigned)bigLosses;
-(unsigned)ntpRTTMin;
-(unsigned)ntpRTTMax;
-(unsigned)ntpRTTAvg;
-(unsigned)ntpOffsetMin;
-(unsigned)ntpOffsetMax;
-(unsigned)ntpOffsetAvg;
-(unsigned)ntpOutliers;
-(unsigned)ntpSteps;
-(unsigned)rtpMaxSkew;
-(unsigned)rtpSkewResets;
-(unsigned)dacpPauses;
-(unsigned)dacpNext;
-(unsigned)dacpPrevious;
-(void)setHasReason:(bool)arg1 ;
-(bool)hasReason;
@end

