/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufAirPlay.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufAirPlay.dylib/libAWDProtobufAirPlay.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDAirPlayVideoSessionEndedOnClient : PBCodable <NSCopying> {

	double _bandwidthMax;
	double _bandwidthMean;
	double _bandwidthStdDev;
	unsigned long long _timestamp;
	unsigned _duration;
	unsigned _localFairPlayCount;
	unsigned _localNonFairPlayCount;
	unsigned _readyToPlayMs;
	int _reason;
	unsigned _remoteFairPlayCount;
	unsigned _remoteNonFairPlayCount;
	NSString* _sessionUUID;
	unsigned _stallCount;
	SCD_Struct_AW5 _has;

}

@property (nonatomic,readonly) bool hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                       //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                 //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasReason; 
@property (assign,nonatomic) int reason;                                   //@synthesize reason=_reason - In the implementation block
@property (assign,nonatomic) bool hasDuration; 
@property (assign,nonatomic) unsigned duration;                            //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) bool hasReadyToPlayMs; 
@property (assign,nonatomic) unsigned readyToPlayMs;                       //@synthesize readyToPlayMs=_readyToPlayMs - In the implementation block
@property (assign,nonatomic) bool hasStallCount; 
@property (assign,nonatomic) unsigned stallCount;                          //@synthesize stallCount=_stallCount - In the implementation block
@property (assign,nonatomic) bool hasBandwidthStdDev; 
@property (assign,nonatomic) double bandwidthStdDev;                       //@synthesize bandwidthStdDev=_bandwidthStdDev - In the implementation block
@property (assign,nonatomic) bool hasBandwidthMean; 
@property (assign,nonatomic) double bandwidthMean;                         //@synthesize bandwidthMean=_bandwidthMean - In the implementation block
@property (assign,nonatomic) bool hasBandwidthMax; 
@property (assign,nonatomic) double bandwidthMax;                          //@synthesize bandwidthMax=_bandwidthMax - In the implementation block
@property (assign,nonatomic) bool hasLocalFairPlayCount; 
@property (assign,nonatomic) unsigned localFairPlayCount;                  //@synthesize localFairPlayCount=_localFairPlayCount - In the implementation block
@property (assign,nonatomic) bool hasLocalNonFairPlayCount; 
@property (assign,nonatomic) unsigned localNonFairPlayCount;               //@synthesize localNonFairPlayCount=_localNonFairPlayCount - In the implementation block
@property (assign,nonatomic) bool hasRemoteFairPlayCount; 
@property (assign,nonatomic) unsigned remoteFairPlayCount;                 //@synthesize remoteFairPlayCount=_remoteFairPlayCount - In the implementation block
@property (assign,nonatomic) bool hasRemoteNonFairPlayCount; 
@property (assign,nonatomic) unsigned remoteNonFairPlayCount;              //@synthesize remoteNonFairPlayCount=_remoteNonFairPlayCount - In the implementation block
-(void)setReason:(int)arg1 ;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(unsigned)duration;
-(void)setDuration:(unsigned)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(int)reason;
-(void)setSessionUUID:(id)arg1 ;
-(void)setReadyToPlayMs:(unsigned)arg1 ;
-(void)setStallCount:(unsigned)arg1 ;
-(void)setLocalFairPlayCount:(unsigned)arg1 ;
-(void)setLocalNonFairPlayCount:(unsigned)arg1 ;
-(void)setRemoteFairPlayCount:(unsigned)arg1 ;
-(void)setRemoteNonFairPlayCount:(unsigned)arg1 ;
-(void)setBandwidthStdDev:(double)arg1 ;
-(void)setBandwidthMean:(double)arg1 ;
-(void)setBandwidthMax:(double)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(bool)hasDuration;
-(void)setHasDuration:(bool)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(bool)hasSessionUUID;
-(id)sessionUUID;
-(void)setHasReadyToPlayMs:(bool)arg1 ;
-(bool)hasReadyToPlayMs;
-(void)setHasStallCount:(bool)arg1 ;
-(bool)hasStallCount;
-(void)setHasBandwidthStdDev:(bool)arg1 ;
-(bool)hasBandwidthStdDev;
-(void)setHasBandwidthMean:(bool)arg1 ;
-(bool)hasBandwidthMean;
-(void)setHasBandwidthMax:(bool)arg1 ;
-(bool)hasBandwidthMax;
-(void)setHasLocalFairPlayCount:(bool)arg1 ;
-(bool)hasLocalFairPlayCount;
-(void)setHasLocalNonFairPlayCount:(bool)arg1 ;
-(bool)hasLocalNonFairPlayCount;
-(void)setHasRemoteFairPlayCount:(bool)arg1 ;
-(bool)hasRemoteFairPlayCount;
-(void)setHasRemoteNonFairPlayCount:(bool)arg1 ;
-(bool)hasRemoteNonFairPlayCount;
-(unsigned)readyToPlayMs;
-(unsigned)stallCount;
-(double)bandwidthStdDev;
-(double)bandwidthMean;
-(double)bandwidthMax;
-(unsigned)localFairPlayCount;
-(unsigned)localNonFairPlayCount;
-(unsigned)remoteFairPlayCount;
-(unsigned)remoteNonFairPlayCount;
-(void)setHasReason:(bool)arg1 ;
-(bool)hasReason;
@end

