/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufAirPlay.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufAirPlay.dylib/libAWDProtobufAirPlay.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDAirPlayScreenSessionEndedOnServer : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _audioLate;
	unsigned _audioLost;
	unsigned _audioUnrecovered;
	int _avgAhead;
	unsigned _avgRTT;
	int _avgReceiveMs;
	unsigned _caDrops;
	unsigned _caFrames;
	unsigned _clearScreens;
	unsigned _configChanges;
	unsigned _duration;
	unsigned _forcedRefreshes;
	unsigned _framesReceived;
	unsigned _negativeAheadFrames;
	int _reason;
	unsigned _resumes;
	NSString* _sessionUUID;
	unsigned _suspends;
	unsigned _unclearScreens;
	SCD_Struct_AW10 _has;

}

@property (nonatomic,readonly) bool hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                    //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasReason; 
@property (assign,nonatomic) int reason;                                //@synthesize reason=_reason - In the implementation block
@property (assign,nonatomic) bool hasDuration; 
@property (assign,nonatomic) unsigned duration;                         //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) bool hasFramesReceived; 
@property (assign,nonatomic) unsigned framesReceived;                   //@synthesize framesReceived=_framesReceived - In the implementation block
@property (assign,nonatomic) bool hasConfigChanges; 
@property (assign,nonatomic) unsigned configChanges;                    //@synthesize configChanges=_configChanges - In the implementation block
@property (assign,nonatomic) bool hasClearScreens; 
@property (assign,nonatomic) unsigned clearScreens;                     //@synthesize clearScreens=_clearScreens - In the implementation block
@property (assign,nonatomic) bool hasUnclearScreens; 
@property (assign,nonatomic) unsigned unclearScreens;                   //@synthesize unclearScreens=_unclearScreens - In the implementation block
@property (assign,nonatomic) bool hasSuspends; 
@property (assign,nonatomic) unsigned suspends;                         //@synthesize suspends=_suspends - In the implementation block
@property (assign,nonatomic) bool hasResumes; 
@property (assign,nonatomic) unsigned resumes;                          //@synthesize resumes=_resumes - In the implementation block
@property (assign,nonatomic) bool hasForcedRefreshes; 
@property (assign,nonatomic) unsigned forcedRefreshes;                  //@synthesize forcedRefreshes=_forcedRefreshes - In the implementation block
@property (assign,nonatomic) bool hasNegativeAheadFrames; 
@property (assign,nonatomic) unsigned negativeAheadFrames;              //@synthesize negativeAheadFrames=_negativeAheadFrames - In the implementation block
@property (assign,nonatomic) bool hasCaFrames; 
@property (assign,nonatomic) unsigned caFrames;                         //@synthesize caFrames=_caFrames - In the implementation block
@property (assign,nonatomic) bool hasCaDrops; 
@property (assign,nonatomic) unsigned caDrops;                          //@synthesize caDrops=_caDrops - In the implementation block
@property (assign,nonatomic) bool hasAudioLost; 
@property (assign,nonatomic) unsigned audioLost;                        //@synthesize audioLost=_audioLost - In the implementation block
@property (assign,nonatomic) bool hasAudioUnrecovered; 
@property (assign,nonatomic) unsigned audioUnrecovered;                 //@synthesize audioUnrecovered=_audioUnrecovered - In the implementation block
@property (assign,nonatomic) bool hasAudioLate; 
@property (assign,nonatomic) unsigned audioLate;                        //@synthesize audioLate=_audioLate - In the implementation block
@property (assign,nonatomic) bool hasAvgRTT; 
@property (assign,nonatomic) unsigned avgRTT;                           //@synthesize avgRTT=_avgRTT - In the implementation block
@property (assign,nonatomic) bool hasAvgAhead; 
@property (assign,nonatomic) int avgAhead;                              //@synthesize avgAhead=_avgAhead - In the implementation block
@property (assign,nonatomic) bool hasAvgReceiveMs; 
@property (assign,nonatomic) int avgReceiveMs;                          //@synthesize avgReceiveMs=_avgReceiveMs - In the implementation block
-(void)setReason:(int)arg1 ;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(unsigned)duration;
-(void)setDuration:(unsigned)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(int)reason;
-(void)setSessionUUID:(id)arg1 ;
-(void)setConfigChanges:(unsigned)arg1 ;
-(void)setClearScreens:(unsigned)arg1 ;
-(void)setUnclearScreens:(unsigned)arg1 ;
-(void)setSuspends:(unsigned)arg1 ;
-(void)setResumes:(unsigned)arg1 ;
-(void)setForcedRefreshes:(unsigned)arg1 ;
-(void)setFramesReceived:(unsigned)arg1 ;
-(void)setNegativeAheadFrames:(unsigned)arg1 ;
-(void)setCaFrames:(unsigned)arg1 ;
-(void)setCaDrops:(unsigned)arg1 ;
-(void)setAudioLost:(unsigned)arg1 ;
-(void)setAudioUnrecovered:(unsigned)arg1 ;
-(void)setAudioLate:(unsigned)arg1 ;
-(void)setAvgRTT:(unsigned)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(bool)hasDuration;
-(void)setHasDuration:(bool)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(bool)hasSessionUUID;
-(id)sessionUUID;
-(void)setHasConfigChanges:(bool)arg1 ;
-(bool)hasConfigChanges;
-(void)setHasClearScreens:(bool)arg1 ;
-(bool)hasClearScreens;
-(void)setHasUnclearScreens:(bool)arg1 ;
-(bool)hasUnclearScreens;
-(void)setHasSuspends:(bool)arg1 ;
-(bool)hasSuspends;
-(void)setHasResumes:(bool)arg1 ;
-(bool)hasResumes;
-(void)setHasForcedRefreshes:(bool)arg1 ;
-(bool)hasForcedRefreshes;
-(unsigned)configChanges;
-(unsigned)clearScreens;
-(unsigned)unclearScreens;
-(unsigned)suspends;
-(unsigned)resumes;
-(unsigned)forcedRefreshes;
-(void)setHasFramesReceived:(bool)arg1 ;
-(bool)hasFramesReceived;
-(void)setHasNegativeAheadFrames:(bool)arg1 ;
-(bool)hasNegativeAheadFrames;
-(void)setHasCaFrames:(bool)arg1 ;
-(bool)hasCaFrames;
-(void)setHasCaDrops:(bool)arg1 ;
-(bool)hasCaDrops;
-(void)setHasAudioLost:(bool)arg1 ;
-(bool)hasAudioLost;
-(void)setHasAudioUnrecovered:(bool)arg1 ;
-(bool)hasAudioUnrecovered;
-(void)setHasAudioLate:(bool)arg1 ;
-(bool)hasAudioLate;
-(void)setHasAvgRTT:(bool)arg1 ;
-(bool)hasAvgRTT;
-(void)setAvgAhead:(int)arg1 ;
-(void)setHasAvgAhead:(bool)arg1 ;
-(bool)hasAvgAhead;
-(void)setAvgReceiveMs:(int)arg1 ;
-(void)setHasAvgReceiveMs:(bool)arg1 ;
-(bool)hasAvgReceiveMs;
-(unsigned)framesReceived;
-(unsigned)negativeAheadFrames;
-(unsigned)caFrames;
-(unsigned)caDrops;
-(unsigned)audioLost;
-(unsigned)audioUnrecovered;
-(unsigned)audioLate;
-(unsigned)avgRTT;
-(int)avgAhead;
-(int)avgReceiveMs;
-(void)setHasReason:(bool)arg1 ;
-(bool)hasReason;
@end

