/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufAirPlay.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufAirPlay.dylib/libAWDProtobufAirPlay.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDAirPlaySessionStarted : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _audioCompressionType;
	unsigned _initiator;
	unsigned _sessionType;
	NSString* _sessionUUID;
	unsigned _transportType;
	SCD_Struct_AW2 _has;

}

@property (nonatomic,readonly) bool hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                     //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasInitiator; 
@property (assign,nonatomic) unsigned initiator;                         //@synthesize initiator=_initiator - In the implementation block
@property (assign,nonatomic) bool hasSessionType; 
@property (assign,nonatomic) unsigned sessionType;                       //@synthesize sessionType=_sessionType - In the implementation block
@property (assign,nonatomic) bool hasTransportType; 
@property (assign,nonatomic) unsigned transportType;                     //@synthesize transportType=_transportType - In the implementation block
@property (assign,nonatomic) bool hasAudioCompressionType; 
@property (assign,nonatomic) unsigned audioCompressionType;              //@synthesize audioCompressionType=_audioCompressionType - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(void)setTransportType:(unsigned)arg1 ;
-(void)setHasTransportType:(bool)arg1 ;
-(bool)hasTransportType;
-(unsigned)initiator;
-(void)setSessionUUID:(id)arg1 ;
-(void)setAudioCompressionType:(unsigned)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned)transportType;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(bool)hasSessionUUID;
-(void)setInitiator:(unsigned)arg1 ;
-(void)setHasInitiator:(bool)arg1 ;
-(bool)hasInitiator;
-(id)sessionUUID;
-(void)setSessionType:(unsigned)arg1 ;
-(void)setHasSessionType:(bool)arg1 ;
-(bool)hasSessionType;
-(void)setHasAudioCompressionType:(bool)arg1 ;
-(bool)hasAudioCompressionType;
-(unsigned)sessionType;
-(unsigned)audioCompressionType;
@end

