/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufAirPlay.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufAirPlay.dylib/libAWDProtobufAirPlay.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDAirPlayScreenSessionStartedOnServer : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _audioCompressionType;
	unsigned _clientBonjourMs;
	unsigned _clientConfigMs;
	unsigned _clientConnectMs;
	NSString* _clientModel;
	unsigned _clientPrepareMs;
	NSString* _clientVersion;
	unsigned _serverAcceptTime;
	unsigned _serverConfigTime;
	NSString* _sessionUUID;
	int _status;
	unsigned _transportType;
	SCD_Struct_AW11 _has;

}

@property (nonatomic,readonly) bool hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                     //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasStatus; 
@property (assign,nonatomic) int status;                                 //@synthesize status=_status - In the implementation block
@property (assign,nonatomic) bool hasTransportType; 
@property (assign,nonatomic) unsigned transportType;                     //@synthesize transportType=_transportType - In the implementation block
@property (nonatomic,readonly) bool hasClientModel; 
@property (nonatomic,retain) NSString * clientModel;                     //@synthesize clientModel=_clientModel - In the implementation block
@property (nonatomic,readonly) bool hasClientVersion; 
@property (nonatomic,retain) NSString * clientVersion;                   //@synthesize clientVersion=_clientVersion - In the implementation block
@property (assign,nonatomic) bool hasAudioCompressionType; 
@property (assign,nonatomic) unsigned audioCompressionType;              //@synthesize audioCompressionType=_audioCompressionType - In the implementation block
@property (assign,nonatomic) bool hasClientPrepareMs; 
@property (assign,nonatomic) unsigned clientPrepareMs;                   //@synthesize clientPrepareMs=_clientPrepareMs - In the implementation block
@property (assign,nonatomic) bool hasClientBonjourMs; 
@property (assign,nonatomic) unsigned clientBonjourMs;                   //@synthesize clientBonjourMs=_clientBonjourMs - In the implementation block
@property (assign,nonatomic) bool hasClientConnectMs; 
@property (assign,nonatomic) unsigned clientConnectMs;                   //@synthesize clientConnectMs=_clientConnectMs - In the implementation block
@property (assign,nonatomic) bool hasClientConfigMs; 
@property (assign,nonatomic) unsigned clientConfigMs;                    //@synthesize clientConfigMs=_clientConfigMs - In the implementation block
@property (assign,nonatomic) bool hasServerAcceptTime; 
@property (assign,nonatomic) unsigned serverAcceptTime;                  //@synthesize serverAcceptTime=_serverAcceptTime - In the implementation block
@property (assign,nonatomic) bool hasServerConfigTime; 
@property (assign,nonatomic) unsigned serverConfigTime;                  //@synthesize serverConfigTime=_serverConfigTime - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(int)status;
-(void)setStatus:(int)arg1 ;
-(void)setTransportType:(unsigned)arg1 ;
-(void)setHasTransportType:(bool)arg1 ;
-(bool)hasTransportType;
-(void)setHasStatus:(bool)arg1 ;
-(bool)hasStatus;
-(void)setSessionUUID:(id)arg1 ;
-(void)setClientModel:(id)arg1 ;
-(void)setAudioCompressionType:(unsigned)arg1 ;
-(void)setClientBonjourMs:(unsigned)arg1 ;
-(void)setClientConnectMs:(unsigned)arg1 ;
-(void)setClientPrepareMs:(unsigned)arg1 ;
-(void)setClientConfigMs:(unsigned)arg1 ;
-(void)setServerAcceptTime:(unsigned)arg1 ;
-(void)setServerConfigTime:(unsigned)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(id)clientVersion;
-(void)setClientVersion:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned)transportType;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(bool)hasSessionUUID;
-(id)sessionUUID;
-(void)setHasAudioCompressionType:(bool)arg1 ;
-(bool)hasAudioCompressionType;
-(unsigned)audioCompressionType;
-(bool)hasClientModel;
-(bool)hasClientVersion;
-(void)setHasClientBonjourMs:(bool)arg1 ;
-(bool)hasClientBonjourMs;
-(void)setHasClientConnectMs:(bool)arg1 ;
-(bool)hasClientConnectMs;
-(id)clientModel;
-(unsigned)clientBonjourMs;
-(unsigned)clientConnectMs;
-(void)setHasClientPrepareMs:(bool)arg1 ;
-(bool)hasClientPrepareMs;
-(void)setHasClientConfigMs:(bool)arg1 ;
-(bool)hasClientConfigMs;
-(void)setHasServerAcceptTime:(bool)arg1 ;
-(bool)hasServerAcceptTime;
-(void)setHasServerConfigTime:(bool)arg1 ;
-(bool)hasServerConfigTime;
-(unsigned)clientPrepareMs;
-(unsigned)clientConfigMs;
-(unsigned)serverAcceptTime;
-(unsigned)serverConfigTime;
@end

