/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufAirPlay.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufAirPlay.dylib/libAWDProtobufAirPlay.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDAirPlayVideoSessionStartedOnServer : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _audioOnly;
	unsigned _clientAuthMs;
	unsigned _clientBonjourMs;
	unsigned _clientConnectMs;
	unsigned _clientInfoMs;
	NSString* _clientModel;
	unsigned _clientPostAuthMs;
	unsigned _clientSecureConnectionMs;
	NSString* _clientVersion;
	NSString* _sessionUUID;
	int _status;
	unsigned _transportType;
	unsigned _type;
	SCD_Struct_AW12 _has;

}

@property (nonatomic,readonly) bool hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                         //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                   //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasStatus; 
@property (assign,nonatomic) int status;                                     //@synthesize status=_status - In the implementation block
@property (assign,nonatomic) bool hasTransportType; 
@property (assign,nonatomic) unsigned transportType;                         //@synthesize transportType=_transportType - In the implementation block
@property (assign,nonatomic) bool hasType; 
@property (assign,nonatomic) unsigned type;                                  //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) bool hasClientModel; 
@property (nonatomic,retain) NSString * clientModel;                         //@synthesize clientModel=_clientModel - In the implementation block
@property (nonatomic,readonly) bool hasClientVersion; 
@property (nonatomic,retain) NSString * clientVersion;                       //@synthesize clientVersion=_clientVersion - In the implementation block
@property (assign,nonatomic) bool hasAudioOnly; 
@property (assign,nonatomic) unsigned audioOnly;                             //@synthesize audioOnly=_audioOnly - In the implementation block
@property (assign,nonatomic) bool hasClientBonjourMs; 
@property (assign,nonatomic) unsigned clientBonjourMs;                       //@synthesize clientBonjourMs=_clientBonjourMs - In the implementation block
@property (assign,nonatomic) bool hasClientConnectMs; 
@property (assign,nonatomic) unsigned clientConnectMs;                       //@synthesize clientConnectMs=_clientConnectMs - In the implementation block
@property (assign,nonatomic) bool hasClientInfoMs; 
@property (assign,nonatomic) unsigned clientInfoMs;                          //@synthesize clientInfoMs=_clientInfoMs - In the implementation block
@property (assign,nonatomic) bool hasClientSecureConnectionMs; 
@property (assign,nonatomic) unsigned clientSecureConnectionMs;              //@synthesize clientSecureConnectionMs=_clientSecureConnectionMs - In the implementation block
@property (assign,nonatomic) bool hasClientAuthMs; 
@property (assign,nonatomic) unsigned clientAuthMs;                          //@synthesize clientAuthMs=_clientAuthMs - In the implementation block
@property (assign,nonatomic) bool hasClientPostAuthMs; 
@property (assign,nonatomic) unsigned clientPostAuthMs;                      //@synthesize clientPostAuthMs=_clientPostAuthMs - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setType:(unsigned)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(unsigned)type;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(int)status;
-(void)setStatus:(int)arg1 ;
-(void)setHasType:(bool)arg1 ;
-(void)setTransportType:(unsigned)arg1 ;
-(void)setHasTransportType:(bool)arg1 ;
-(bool)hasTransportType;
-(void)setHasStatus:(bool)arg1 ;
-(bool)hasStatus;
-(void)setSessionUUID:(id)arg1 ;
-(void)setClientModel:(id)arg1 ;
-(void)setClientBonjourMs:(unsigned)arg1 ;
-(void)setClientConnectMs:(unsigned)arg1 ;
-(void)setClientAuthMs:(unsigned)arg1 ;
-(void)setAudioOnly:(unsigned)arg1 ;
-(void)setClientInfoMs:(unsigned)arg1 ;
-(void)setClientSecureConnectionMs:(unsigned)arg1 ;
-(void)setClientPostAuthMs:(unsigned)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(bool)hasType;
-(id)clientVersion;
-(void)setClientVersion:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned)transportType;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(bool)hasSessionUUID;
-(id)sessionUUID;
-(bool)hasClientModel;
-(bool)hasClientVersion;
-(void)setHasClientBonjourMs:(bool)arg1 ;
-(bool)hasClientBonjourMs;
-(void)setHasClientConnectMs:(bool)arg1 ;
-(bool)hasClientConnectMs;
-(void)setHasClientAuthMs:(bool)arg1 ;
-(bool)hasClientAuthMs;
-(id)clientModel;
-(unsigned)clientBonjourMs;
-(unsigned)clientConnectMs;
-(unsigned)clientAuthMs;
-(void)setHasAudioOnly:(bool)arg1 ;
-(bool)hasAudioOnly;
-(unsigned)audioOnly;
-(void)setHasClientInfoMs:(bool)arg1 ;
-(bool)hasClientInfoMs;
-(void)setHasClientSecureConnectionMs:(bool)arg1 ;
-(bool)hasClientSecureConnectionMs;
-(void)setHasClientPostAuthMs:(bool)arg1 ;
-(bool)hasClientPostAuthMs;
-(unsigned)clientInfoMs;
-(unsigned)clientSecureConnectionMs;
-(unsigned)clientPostAuthMs;
@end

