/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufAirPlay.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufAirPlay.dylib/libAWDProtobufAirPlay.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDAirPlayVideoSessionStartedOnClient : PBCodable <NSCopying> {

	unsigned long long _fileBytes;
	unsigned long long _timestamp;
	unsigned _audioOnly;
	unsigned _authMs;
	unsigned _bitrate;
	unsigned _bonjourMs;
	unsigned _connectMs;
	unsigned _duration;
	unsigned _infoMs;
	unsigned _postAuthMs;
	unsigned _secureConnectionMs;
	NSString* _serverModel;
	NSString* _serverVersion;
	NSString* _sessionUUID;
	int _status;
	unsigned _transportType;
	unsigned _type;
	SCD_Struct_AW14 _has;

}

@property (nonatomic,readonly) bool hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                    //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasStatus; 
@property (assign,nonatomic) int status;                                //@synthesize status=_status - In the implementation block
@property (nonatomic,readonly) bool hasServerModel; 
@property (nonatomic,retain) NSString * serverModel;                    //@synthesize serverModel=_serverModel - In the implementation block
@property (nonatomic,readonly) bool hasServerVersion; 
@property (nonatomic,retain) NSString * serverVersion;                  //@synthesize serverVersion=_serverVersion - In the implementation block
@property (assign,nonatomic) bool hasType; 
@property (assign,nonatomic) unsigned type;                             //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) bool hasTransportType; 
@property (assign,nonatomic) unsigned transportType;                    //@synthesize transportType=_transportType - In the implementation block
@property (assign,nonatomic) bool hasFileBytes; 
@property (assign,nonatomic) unsigned long long fileBytes;              //@synthesize fileBytes=_fileBytes - In the implementation block
@property (assign,nonatomic) bool hasDuration; 
@property (assign,nonatomic) unsigned duration;                         //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) bool hasBitrate; 
@property (assign,nonatomic) unsigned bitrate;                          //@synthesize bitrate=_bitrate - In the implementation block
@property (assign,nonatomic) bool hasAudioOnly; 
@property (assign,nonatomic) unsigned audioOnly;                        //@synthesize audioOnly=_audioOnly - In the implementation block
@property (assign,nonatomic) bool hasBonjourMs; 
@property (assign,nonatomic) unsigned bonjourMs;                        //@synthesize bonjourMs=_bonjourMs - In the implementation block
@property (assign,nonatomic) bool hasConnectMs; 
@property (assign,nonatomic) unsigned connectMs;                        //@synthesize connectMs=_connectMs - In the implementation block
@property (assign,nonatomic) bool hasInfoMs; 
@property (assign,nonatomic) unsigned infoMs;                           //@synthesize infoMs=_infoMs - In the implementation block
@property (assign,nonatomic) bool hasSecureConnectionMs; 
@property (assign,nonatomic) unsigned secureConnectionMs;               //@synthesize secureConnectionMs=_secureConnectionMs - In the implementation block
@property (assign,nonatomic) bool hasAuthMs; 
@property (assign,nonatomic) unsigned authMs;                           //@synthesize authMs=_authMs - In the implementation block
@property (assign,nonatomic) bool hasPostAuthMs; 
@property (assign,nonatomic) unsigned postAuthMs;                       //@synthesize postAuthMs=_postAuthMs - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(unsigned)duration;
-(void)setDuration:(unsigned)arg1 ;
-(void)setType:(unsigned)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(unsigned)type;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(int)status;
-(void)setStatus:(int)arg1 ;
-(void)setServerVersion:(id)arg1 ;
-(id)serverVersion;
-(unsigned)bitrate;
-(void)setBitrate:(unsigned)arg1 ;
-(void)setHasType:(bool)arg1 ;
-(void)setTransportType:(unsigned)arg1 ;
-(void)setHasTransportType:(bool)arg1 ;
-(bool)hasTransportType;
-(void)setHasStatus:(bool)arg1 ;
-(bool)hasStatus;
-(void)setSessionUUID:(id)arg1 ;
-(void)setBonjourMs:(unsigned)arg1 ;
-(void)setConnectMs:(unsigned)arg1 ;
-(void)setAuthMs:(unsigned)arg1 ;
-(void)setFileBytes:(unsigned long long)arg1 ;
-(void)setAudioOnly:(unsigned)arg1 ;
-(void)setServerModel:(id)arg1 ;
-(void)setInfoMs:(unsigned)arg1 ;
-(void)setSecureConnectionMs:(unsigned)arg1 ;
-(void)setPostAuthMs:(unsigned)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(bool)hasDuration;
-(void)setHasDuration:(bool)arg1 ;
-(bool)hasType;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned)transportType;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(bool)hasSessionUUID;
-(id)sessionUUID;
-(void)setHasBonjourMs:(bool)arg1 ;
-(bool)hasBonjourMs;
-(void)setHasConnectMs:(bool)arg1 ;
-(bool)hasConnectMs;
-(void)setHasAuthMs:(bool)arg1 ;
-(bool)hasAuthMs;
-(unsigned)bonjourMs;
-(unsigned)connectMs;
-(unsigned)authMs;
-(bool)hasServerModel;
-(bool)hasServerVersion;
-(void)setHasFileBytes:(bool)arg1 ;
-(bool)hasFileBytes;
-(void)setHasBitrate:(bool)arg1 ;
-(bool)hasBitrate;
-(void)setHasAudioOnly:(bool)arg1 ;
-(bool)hasAudioOnly;
-(void)setHasInfoMs:(bool)arg1 ;
-(bool)hasInfoMs;
-(void)setHasSecureConnectionMs:(bool)arg1 ;
-(bool)hasSecureConnectionMs;
-(void)setHasPostAuthMs:(bool)arg1 ;
-(bool)hasPostAuthMs;
-(id)serverModel;
-(unsigned long long)fileBytes;
-(unsigned)audioOnly;
-(unsigned)infoMs;
-(unsigned)secureConnectionMs;
-(unsigned)postAuthMs;
@end

