/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufAPSD.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	unsigned timestamp : 1;
	unsigned connectDuration : 1;
	unsigned connectionType : 1;
	unsigned dualChannelState : 1;
	unsigned linkQuality : 1;
} SCD_Struct_AW1;

typedef struct {
	unsigned timestamp : 1;
	unsigned connectionType : 1;
	unsigned error : 1;
	unsigned genericError : 1;
	unsigned linkQuality : 1;
	unsigned sslError : 1;
} SCD_Struct_AW2;

typedef struct {
	unsigned timestamp : 1;
	unsigned connectionType : 1;
	unsigned dualChannelState : 1;
	unsigned keepAliveACKDuration : 1;
	unsigned linkQuality : 1;
	unsigned nextKeepAliveInterval : 1;
	unsigned timeSinceLastKeepAlive : 1;
} SCD_Struct_AW3;

typedef struct {
	unsigned timestamp : 1;
	unsigned connectionType : 1;
	unsigned dualChannelState : 1;
	unsigned error : 1;
	unsigned flushes : 1;
	unsigned linkQuality : 1;
	unsigned payloadSize : 1;
	unsigned sendDuration : 1;
} SCD_Struct_AW4;

