/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufMMCS.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufMMCS.dylib/libAWDProtobufMMCS.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDMMCSTcpInfo : PBCodable <NSCopying> {

	unsigned long long _tcpiCellRxbytes;
	unsigned long long _tcpiCellRxpackets;
	unsigned long long _tcpiCellTxbytes;
	unsigned long long _tcpiCellTxpackets;
	unsigned long long _tcpiRxbytes;
	unsigned long long _tcpiRxduplicatebytes;
	unsigned long long _tcpiRxoutoforderbytes;
	unsigned long long _tcpiRxpackets;
	unsigned long long _tcpiSndBw;
	unsigned long long _tcpiTxbytes;
	unsigned long long _tcpiTxpackets;
	unsigned long long _tcpiTxretransmitbytes;
	unsigned long long _tcpiTxunacked;
	unsigned long long _tcpiWifiRxbytes;
	unsigned long long _tcpiWifiRxpackets;
	unsigned long long _tcpiWifiTxbytes;
	unsigned long long _tcpiWifiTxpackets;
	unsigned _tcpiFlags;
	int _tcpiLastOutif;
	unsigned _tcpiOptions;
	unsigned _tcpiRcvMss;
	unsigned _tcpiRcvNxt;
	unsigned _tcpiRcvSpace;
	unsigned _tcpiRcvWscale;
	unsigned _tcpiRto;
	unsigned _tcpiRttbest;
	unsigned _tcpiRttcur;
	unsigned _tcpiRttvar;
	unsigned _tcpiSndCwnd;
	unsigned _tcpiSndMss;
	unsigned _tcpiSndNxt;
	unsigned _tcpiSndSbbytes;
	unsigned _tcpiSndSsthresh;
	unsigned _tcpiSndWnd;
	unsigned _tcpiSndWscale;
	unsigned _tcpiSrtt;
	unsigned _tcpiState;
	int _tcpiSynrexmits;
	int _tcpiUnused1;
	unsigned _tcpiUnused2;
	SCD_Struct_AW1 _has;

}

@property (assign,nonatomic) bool hasTcpiState; 
@property (assign,nonatomic) unsigned tcpiState;                                    //@synthesize tcpiState=_tcpiState - In the implementation block
@property (assign,nonatomic) bool hasTcpiOptions; 
@property (assign,nonatomic) unsigned tcpiOptions;                                  //@synthesize tcpiOptions=_tcpiOptions - In the implementation block
@property (assign,nonatomic) bool hasTcpiSndWscale; 
@property (assign,nonatomic) unsigned tcpiSndWscale;                                //@synthesize tcpiSndWscale=_tcpiSndWscale - In the implementation block
@property (assign,nonatomic) bool hasTcpiRcvWscale; 
@property (assign,nonatomic) unsigned tcpiRcvWscale;                                //@synthesize tcpiRcvWscale=_tcpiRcvWscale - In the implementation block
@property (assign,nonatomic) bool hasTcpiFlags; 
@property (assign,nonatomic) unsigned tcpiFlags;                                    //@synthesize tcpiFlags=_tcpiFlags - In the implementation block
@property (assign,nonatomic) bool hasTcpiRto; 
@property (assign,nonatomic) unsigned tcpiRto;                                      //@synthesize tcpiRto=_tcpiRto - In the implementation block
@property (assign,nonatomic) bool hasTcpiSndMss; 
@property (assign,nonatomic) unsigned tcpiSndMss;                                   //@synthesize tcpiSndMss=_tcpiSndMss - In the implementation block
@property (assign,nonatomic) bool hasTcpiRcvMss; 
@property (assign,nonatomic) unsigned tcpiRcvMss;                                   //@synthesize tcpiRcvMss=_tcpiRcvMss - In the implementation block
@property (assign,nonatomic) bool hasTcpiRttcur; 
@property (assign,nonatomic) unsigned tcpiRttcur;                                   //@synthesize tcpiRttcur=_tcpiRttcur - In the implementation block
@property (assign,nonatomic) bool hasTcpiSrtt; 
@property (assign,nonatomic) unsigned tcpiSrtt;                                     //@synthesize tcpiSrtt=_tcpiSrtt - In the implementation block
@property (assign,nonatomic) bool hasTcpiRttvar; 
@property (assign,nonatomic) unsigned tcpiRttvar;                                   //@synthesize tcpiRttvar=_tcpiRttvar - In the implementation block
@property (assign,nonatomic) bool hasTcpiRttbest; 
@property (assign,nonatomic) unsigned tcpiRttbest;                                  //@synthesize tcpiRttbest=_tcpiRttbest - In the implementation block
@property (assign,nonatomic) bool hasTcpiSndSsthresh; 
@property (assign,nonatomic) unsigned tcpiSndSsthresh;                              //@synthesize tcpiSndSsthresh=_tcpiSndSsthresh - In the implementation block
@property (assign,nonatomic) bool hasTcpiSndCwnd; 
@property (assign,nonatomic) unsigned tcpiSndCwnd;                                  //@synthesize tcpiSndCwnd=_tcpiSndCwnd - In the implementation block
@property (assign,nonatomic) bool hasTcpiRcvSpace; 
@property (assign,nonatomic) unsigned tcpiRcvSpace;                                 //@synthesize tcpiRcvSpace=_tcpiRcvSpace - In the implementation block
@property (assign,nonatomic) bool hasTcpiSndWnd; 
@property (assign,nonatomic) unsigned tcpiSndWnd;                                   //@synthesize tcpiSndWnd=_tcpiSndWnd - In the implementation block
@property (assign,nonatomic) bool hasTcpiSndNxt; 
@property (assign,nonatomic) unsigned tcpiSndNxt;                                   //@synthesize tcpiSndNxt=_tcpiSndNxt - In the implementation block
@property (assign,nonatomic) bool hasTcpiRcvNxt; 
@property (assign,nonatomic) unsigned tcpiRcvNxt;                                   //@synthesize tcpiRcvNxt=_tcpiRcvNxt - In the implementation block
@property (assign,nonatomic) bool hasTcpiLastOutif; 
@property (assign,nonatomic) int tcpiLastOutif;                                     //@synthesize tcpiLastOutif=_tcpiLastOutif - In the implementation block
@property (assign,nonatomic) bool hasTcpiSndSbbytes; 
@property (assign,nonatomic) unsigned tcpiSndSbbytes;                               //@synthesize tcpiSndSbbytes=_tcpiSndSbbytes - In the implementation block
@property (assign,nonatomic) bool hasTcpiTxpackets; 
@property (assign,nonatomic) unsigned long long tcpiTxpackets;                      //@synthesize tcpiTxpackets=_tcpiTxpackets - In the implementation block
@property (assign,nonatomic) bool hasTcpiTxbytes; 
@property (assign,nonatomic) unsigned long long tcpiTxbytes;                        //@synthesize tcpiTxbytes=_tcpiTxbytes - In the implementation block
@property (assign,nonatomic) bool hasTcpiTxretransmitbytes; 
@property (assign,nonatomic) unsigned long long tcpiTxretransmitbytes;              //@synthesize tcpiTxretransmitbytes=_tcpiTxretransmitbytes - In the implementation block
@property (assign,nonatomic) bool hasTcpiTxunacked; 
@property (assign,nonatomic) unsigned long long tcpiTxunacked;                      //@synthesize tcpiTxunacked=_tcpiTxunacked - In the implementation block
@property (assign,nonatomic) bool hasTcpiRxpackets; 
@property (assign,nonatomic) unsigned long long tcpiRxpackets;                      //@synthesize tcpiRxpackets=_tcpiRxpackets - In the implementation block
@property (assign,nonatomic) bool hasTcpiRxbytes; 
@property (assign,nonatomic) unsigned long long tcpiRxbytes;                        //@synthesize tcpiRxbytes=_tcpiRxbytes - In the implementation block
@property (assign,nonatomic) bool hasTcpiRxduplicatebytes; 
@property (assign,nonatomic) unsigned long long tcpiRxduplicatebytes;               //@synthesize tcpiRxduplicatebytes=_tcpiRxduplicatebytes - In the implementation block
@property (assign,nonatomic) bool hasTcpiRxoutoforderbytes; 
@property (assign,nonatomic) unsigned long long tcpiRxoutoforderbytes;              //@synthesize tcpiRxoutoforderbytes=_tcpiRxoutoforderbytes - In the implementation block
@property (assign,nonatomic) bool hasTcpiSndBw; 
@property (assign,nonatomic) unsigned long long tcpiSndBw;                          //@synthesize tcpiSndBw=_tcpiSndBw - In the implementation block
@property (assign,nonatomic) bool hasTcpiSynrexmits; 
@property (assign,nonatomic) int tcpiSynrexmits;                                    //@synthesize tcpiSynrexmits=_tcpiSynrexmits - In the implementation block
@property (assign,nonatomic) bool hasTcpiUnused1; 
@property (assign,nonatomic) int tcpiUnused1;                                       //@synthesize tcpiUnused1=_tcpiUnused1 - In the implementation block
@property (assign,nonatomic) bool hasTcpiUnused2; 
@property (assign,nonatomic) unsigned tcpiUnused2;                                  //@synthesize tcpiUnused2=_tcpiUnused2 - In the implementation block
@property (assign,nonatomic) bool hasTcpiCellRxpackets; 
@property (assign,nonatomic) unsigned long long tcpiCellRxpackets;                  //@synthesize tcpiCellRxpackets=_tcpiCellRxpackets - In the implementation block
@property (assign,nonatomic) bool hasTcpiCellRxbytes; 
@property (assign,nonatomic) unsigned long long tcpiCellRxbytes;                    //@synthesize tcpiCellRxbytes=_tcpiCellRxbytes - In the implementation block
@property (assign,nonatomic) bool hasTcpiCellTxpackets; 
@property (assign,nonatomic) unsigned long long tcpiCellTxpackets;                  //@synthesize tcpiCellTxpackets=_tcpiCellTxpackets - In the implementation block
@property (assign,nonatomic) bool hasTcpiCellTxbytes; 
@property (assign,nonatomic) unsigned long long tcpiCellTxbytes;                    //@synthesize tcpiCellTxbytes=_tcpiCellTxbytes - In the implementation block
@property (assign,nonatomic) bool hasTcpiWifiRxpackets; 
@property (assign,nonatomic) unsigned long long tcpiWifiRxpackets;                  //@synthesize tcpiWifiRxpackets=_tcpiWifiRxpackets - In the implementation block
@property (assign,nonatomic) bool hasTcpiWifiRxbytes; 
@property (assign,nonatomic) unsigned long long tcpiWifiRxbytes;                    //@synthesize tcpiWifiRxbytes=_tcpiWifiRxbytes - In the implementation block
@property (assign,nonatomic) bool hasTcpiWifiTxpackets; 
@property (assign,nonatomic) unsigned long long tcpiWifiTxpackets;                  //@synthesize tcpiWifiTxpackets=_tcpiWifiTxpackets - In the implementation block
@property (assign,nonatomic) bool hasTcpiWifiTxbytes; 
@property (assign,nonatomic) unsigned long long tcpiWifiTxbytes;                    //@synthesize tcpiWifiTxbytes=_tcpiWifiTxbytes - In the implementation block
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTcpiState:(unsigned)arg1 ;
-(void)setHasTcpiState:(bool)arg1 ;
-(bool)hasTcpiState;
-(void)setTcpiOptions:(unsigned)arg1 ;
-(void)setHasTcpiOptions:(bool)arg1 ;
-(bool)hasTcpiOptions;
-(void)setTcpiSndWscale:(unsigned)arg1 ;
-(void)setHasTcpiSndWscale:(bool)arg1 ;
-(bool)hasTcpiSndWscale;
-(void)setTcpiRcvWscale:(unsigned)arg1 ;
-(void)setHasTcpiRcvWscale:(bool)arg1 ;
-(bool)hasTcpiRcvWscale;
-(void)setTcpiFlags:(unsigned)arg1 ;
-(void)setHasTcpiFlags:(bool)arg1 ;
-(bool)hasTcpiFlags;
-(void)setTcpiRto:(unsigned)arg1 ;
-(void)setHasTcpiRto:(bool)arg1 ;
-(bool)hasTcpiRto;
-(void)setTcpiSndMss:(unsigned)arg1 ;
-(void)setHasTcpiSndMss:(bool)arg1 ;
-(bool)hasTcpiSndMss;
-(void)setTcpiRcvMss:(unsigned)arg1 ;
-(void)setHasTcpiRcvMss:(bool)arg1 ;
-(bool)hasTcpiRcvMss;
-(void)setTcpiRttcur:(unsigned)arg1 ;
-(void)setHasTcpiRttcur:(bool)arg1 ;
-(bool)hasTcpiRttcur;
-(void)setTcpiSrtt:(unsigned)arg1 ;
-(void)setHasTcpiSrtt:(bool)arg1 ;
-(bool)hasTcpiSrtt;
-(void)setTcpiRttvar:(unsigned)arg1 ;
-(void)setHasTcpiRttvar:(bool)arg1 ;
-(bool)hasTcpiRttvar;
-(void)setTcpiRttbest:(unsigned)arg1 ;
-(void)setHasTcpiRttbest:(bool)arg1 ;
-(bool)hasTcpiRttbest;
-(void)setTcpiSndSsthresh:(unsigned)arg1 ;
-(void)setHasTcpiSndSsthresh:(bool)arg1 ;
-(bool)hasTcpiSndSsthresh;
-(void)setTcpiSndCwnd:(unsigned)arg1 ;
-(void)setHasTcpiSndCwnd:(bool)arg1 ;
-(bool)hasTcpiSndCwnd;
-(void)setTcpiRcvSpace:(unsigned)arg1 ;
-(void)setHasTcpiRcvSpace:(bool)arg1 ;
-(bool)hasTcpiRcvSpace;
-(void)setTcpiSndWnd:(unsigned)arg1 ;
-(void)setHasTcpiSndWnd:(bool)arg1 ;
-(bool)hasTcpiSndWnd;
-(void)setTcpiSndNxt:(unsigned)arg1 ;
-(void)setHasTcpiSndNxt:(bool)arg1 ;
-(bool)hasTcpiSndNxt;
-(void)setTcpiRcvNxt:(unsigned)arg1 ;
-(void)setHasTcpiRcvNxt:(bool)arg1 ;
-(bool)hasTcpiRcvNxt;
-(void)setTcpiLastOutif:(int)arg1 ;
-(void)setHasTcpiLastOutif:(bool)arg1 ;
-(bool)hasTcpiLastOutif;
-(void)setTcpiSndSbbytes:(unsigned)arg1 ;
-(void)setHasTcpiSndSbbytes:(bool)arg1 ;
-(bool)hasTcpiSndSbbytes;
-(void)setTcpiTxpackets:(unsigned long long)arg1 ;
-(void)setHasTcpiTxpackets:(bool)arg1 ;
-(bool)hasTcpiTxpackets;
-(void)setTcpiTxbytes:(unsigned long long)arg1 ;
-(void)setHasTcpiTxbytes:(bool)arg1 ;
-(bool)hasTcpiTxbytes;
-(void)setTcpiTxretransmitbytes:(unsigned long long)arg1 ;
-(void)setHasTcpiTxretransmitbytes:(bool)arg1 ;
-(bool)hasTcpiTxretransmitbytes;
-(void)setTcpiTxunacked:(unsigned long long)arg1 ;
-(void)setHasTcpiTxunacked:(bool)arg1 ;
-(bool)hasTcpiTxunacked;
-(void)setTcpiRxpackets:(unsigned long long)arg1 ;
-(void)setHasTcpiRxpackets:(bool)arg1 ;
-(bool)hasTcpiRxpackets;
-(void)setTcpiRxbytes:(unsigned long long)arg1 ;
-(void)setHasTcpiRxbytes:(bool)arg1 ;
-(bool)hasTcpiRxbytes;
-(void)setTcpiRxduplicatebytes:(unsigned long long)arg1 ;
-(void)setHasTcpiRxduplicatebytes:(bool)arg1 ;
-(bool)hasTcpiRxduplicatebytes;
-(void)setTcpiRxoutoforderbytes:(unsigned long long)arg1 ;
-(void)setHasTcpiRxoutoforderbytes:(bool)arg1 ;
-(bool)hasTcpiRxoutoforderbytes;
-(void)setTcpiSndBw:(unsigned long long)arg1 ;
-(void)setHasTcpiSndBw:(bool)arg1 ;
-(bool)hasTcpiSndBw;
-(void)setTcpiSynrexmits:(int)arg1 ;
-(void)setHasTcpiSynrexmits:(bool)arg1 ;
-(bool)hasTcpiSynrexmits;
-(void)setTcpiUnused1:(int)arg1 ;
-(void)setHasTcpiUnused1:(bool)arg1 ;
-(bool)hasTcpiUnused1;
-(void)setTcpiUnused2:(unsigned)arg1 ;
-(void)setHasTcpiUnused2:(bool)arg1 ;
-(bool)hasTcpiUnused2;
-(void)setTcpiCellRxpackets:(unsigned long long)arg1 ;
-(void)setHasTcpiCellRxpackets:(bool)arg1 ;
-(bool)hasTcpiCellRxpackets;
-(void)setTcpiCellRxbytes:(unsigned long long)arg1 ;
-(void)setHasTcpiCellRxbytes:(bool)arg1 ;
-(bool)hasTcpiCellRxbytes;
-(void)setTcpiCellTxpackets:(unsigned long long)arg1 ;
-(void)setHasTcpiCellTxpackets:(bool)arg1 ;
-(bool)hasTcpiCellTxpackets;
-(void)setTcpiCellTxbytes:(unsigned long long)arg1 ;
-(void)setHasTcpiCellTxbytes:(bool)arg1 ;
-(bool)hasTcpiCellTxbytes;
-(void)setTcpiWifiRxpackets:(unsigned long long)arg1 ;
-(void)setHasTcpiWifiRxpackets:(bool)arg1 ;
-(bool)hasTcpiWifiRxpackets;
-(void)setTcpiWifiRxbytes:(unsigned long long)arg1 ;
-(void)setHasTcpiWifiRxbytes:(bool)arg1 ;
-(bool)hasTcpiWifiRxbytes;
-(void)setTcpiWifiTxpackets:(unsigned long long)arg1 ;
-(void)setHasTcpiWifiTxpackets:(bool)arg1 ;
-(bool)hasTcpiWifiTxpackets;
-(void)setTcpiWifiTxbytes:(unsigned long long)arg1 ;
-(void)setHasTcpiWifiTxbytes:(bool)arg1 ;
-(bool)hasTcpiWifiTxbytes;
-(unsigned)tcpiState;
-(unsigned)tcpiOptions;
-(unsigned)tcpiSndWscale;
-(unsigned)tcpiRcvWscale;
-(unsigned)tcpiFlags;
-(unsigned)tcpiRto;
-(unsigned)tcpiSndMss;
-(unsigned)tcpiRcvMss;
-(unsigned)tcpiRttcur;
-(unsigned)tcpiSrtt;
-(unsigned)tcpiRttvar;
-(unsigned)tcpiRttbest;
-(unsigned)tcpiSndSsthresh;
-(unsigned)tcpiSndCwnd;
-(unsigned)tcpiRcvSpace;
-(unsigned)tcpiSndWnd;
-(unsigned)tcpiSndNxt;
-(unsigned)tcpiRcvNxt;
-(int)tcpiLastOutif;
-(unsigned)tcpiSndSbbytes;
-(unsigned long long)tcpiTxpackets;
-(unsigned long long)tcpiTxbytes;
-(unsigned long long)tcpiTxretransmitbytes;
-(unsigned long long)tcpiTxunacked;
-(unsigned long long)tcpiRxpackets;
-(unsigned long long)tcpiRxbytes;
-(unsigned long long)tcpiRxduplicatebytes;
-(unsigned long long)tcpiRxoutoforderbytes;
-(unsigned long long)tcpiSndBw;
-(int)tcpiSynrexmits;
-(int)tcpiUnused1;
-(unsigned)tcpiUnused2;
-(unsigned long long)tcpiCellRxpackets;
-(unsigned long long)tcpiCellRxbytes;
-(unsigned long long)tcpiCellTxpackets;
-(unsigned long long)tcpiCellTxbytes;
-(unsigned long long)tcpiWifiRxpackets;
-(unsigned long long)tcpiWifiRxbytes;
-(unsigned long long)tcpiWifiTxpackets;
-(unsigned long long)tcpiWifiTxbytes;
@end

