/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufMMCS.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufMMCS.dylib/libAWDProtobufMMCS.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString, NSMutableArray;

@interface AWDMMCSHttpInfo : PBCodable <NSCopying> {

	long long _duration;
	long long _responseReceivedDuration;
	long long _startTime;
	int _errorCode;
	NSString* _errorDomain;
	NSMutableArray* _httpErrors;
	int _httpStatus;
	NSString* _interfaceIdentifier;
	NSString* _locatorHostname;
	NSString* _locatorPeerAddress;
	unsigned _locatorPort;
	NSString* _locatorScheme;
	int _requestSize;
	int _responseSize;
	NSMutableArray* _tcpInfos;
	bool _cancelled;
	bool _connectionReused;
	bool _timedOut;
	bool _transactionComplete;
	SCD_Struct_AW2 _has;

}

@property (nonatomic,readonly) bool hasLocatorScheme; 
@property (nonatomic,retain) NSString * locatorScheme;                        //@synthesize locatorScheme=_locatorScheme - In the implementation block
@property (nonatomic,readonly) bool hasLocatorHostname; 
@property (nonatomic,retain) NSString * locatorHostname;                      //@synthesize locatorHostname=_locatorHostname - In the implementation block
@property (assign,nonatomic) bool hasLocatorPort; 
@property (assign,nonatomic) unsigned locatorPort;                            //@synthesize locatorPort=_locatorPort - In the implementation block
@property (assign,nonatomic) bool hasConnectionReused; 
@property (assign,nonatomic) bool connectionReused;                           //@synthesize connectionReused=_connectionReused - In the implementation block
@property (assign,nonatomic) bool hasStartTime; 
@property (assign,nonatomic) long long startTime;                             //@synthesize startTime=_startTime - In the implementation block
@property (assign,nonatomic) bool hasResponseReceivedDuration; 
@property (assign,nonatomic) long long responseReceivedDuration;              //@synthesize responseReceivedDuration=_responseReceivedDuration - In the implementation block
@property (assign,nonatomic) bool hasDuration; 
@property (assign,nonatomic) long long duration;                              //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) bool hasHttpStatus; 
@property (assign,nonatomic) int httpStatus;                                  //@synthesize httpStatus=_httpStatus - In the implementation block
@property (nonatomic,readonly) bool hasErrorDomain; 
@property (nonatomic,retain) NSString * errorDomain;                          //@synthesize errorDomain=_errorDomain - In the implementation block
@property (assign,nonatomic) bool hasErrorCode; 
@property (assign,nonatomic) int errorCode;                                   //@synthesize errorCode=_errorCode - In the implementation block
@property (assign,nonatomic) bool hasRequestSize; 
@property (assign,nonatomic) int requestSize;                                 //@synthesize requestSize=_requestSize - In the implementation block
@property (assign,nonatomic) bool hasResponseSize; 
@property (assign,nonatomic) int responseSize;                                //@synthesize responseSize=_responseSize - In the implementation block
@property (assign,nonatomic) bool hasTransactionComplete; 
@property (assign,nonatomic) bool transactionComplete;                        //@synthesize transactionComplete=_transactionComplete - In the implementation block
@property (assign,nonatomic) bool hasTimedOut; 
@property (assign,nonatomic) bool timedOut;                                   //@synthesize timedOut=_timedOut - In the implementation block
@property (assign,nonatomic) bool hasCancelled; 
@property (assign,nonatomic) bool cancelled;                                  //@synthesize cancelled=_cancelled - In the implementation block
@property (nonatomic,retain) NSMutableArray * tcpInfos;                       //@synthesize tcpInfos=_tcpInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * httpErrors;                     //@synthesize httpErrors=_httpErrors - In the implementation block
@property (nonatomic,readonly) bool hasInterfaceIdentifier; 
@property (nonatomic,retain) NSString * interfaceIdentifier;                  //@synthesize interfaceIdentifier=_interfaceIdentifier - In the implementation block
@property (nonatomic,readonly) bool hasLocatorPeerAddress; 
@property (nonatomic,retain) NSString * locatorPeerAddress;                   //@synthesize locatorPeerAddress=_locatorPeerAddress - In the implementation block
-(id)errorDomain;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(long long)duration;
-(void)setDuration:(long long)arg1 ;
-(void)setStartTime:(long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(bool)cancelled;
-(void)setCancelled:(bool)arg1 ;
-(id)dictionaryRepresentation;
-(long long)startTime;
-(void)setTimedOut:(bool)arg1 ;
-(void)setHasStartTime:(bool)arg1 ;
-(void)setErrorDomain:(id)arg1 ;
-(bool)hasErrorDomain;
-(bool)timedOut;
-(bool)readFrom:(id)arg1 ;
-(bool)hasDuration;
-(void)setHasDuration:(bool)arg1 ;
-(id)interfaceIdentifier;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(bool)hasStartTime;
-(void)setErrorCode:(int)arg1 ;
-(void)setHasErrorCode:(bool)arg1 ;
-(bool)hasErrorCode;
-(int)errorCode;
-(void)setLocatorScheme:(id)arg1 ;
-(void)setLocatorHostname:(id)arg1 ;
-(void)setTcpInfos:(id)arg1 ;
-(void)setHttpErrors:(id)arg1 ;
-(void)setInterfaceIdentifier:(id)arg1 ;
-(void)setLocatorPeerAddress:(id)arg1 ;
-(void)addTcpInfo:(id)arg1 ;
-(void)addHttpError:(id)arg1 ;
-(unsigned long long)tcpInfosCount;
-(void)clearTcpInfos;
-(id)tcpInfoAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)httpErrorsCount;
-(void)clearHttpErrors;
-(id)httpErrorAtIndex:(unsigned long long)arg1 ;
-(bool)hasLocatorScheme;
-(bool)hasLocatorHostname;
-(void)setLocatorPort:(unsigned)arg1 ;
-(void)setHasLocatorPort:(bool)arg1 ;
-(bool)hasLocatorPort;
-(void)setConnectionReused:(bool)arg1 ;
-(void)setHasConnectionReused:(bool)arg1 ;
-(bool)hasConnectionReused;
-(void)setResponseReceivedDuration:(long long)arg1 ;
-(void)setHasResponseReceivedDuration:(bool)arg1 ;
-(bool)hasResponseReceivedDuration;
-(void)setHttpStatus:(int)arg1 ;
-(void)setHasHttpStatus:(bool)arg1 ;
-(bool)hasHttpStatus;
-(void)setRequestSize:(int)arg1 ;
-(void)setHasRequestSize:(bool)arg1 ;
-(bool)hasRequestSize;
-(void)setResponseSize:(int)arg1 ;
-(void)setHasResponseSize:(bool)arg1 ;
-(bool)hasResponseSize;
-(void)setTransactionComplete:(bool)arg1 ;
-(void)setHasTransactionComplete:(bool)arg1 ;
-(bool)hasTransactionComplete;
-(void)setHasTimedOut:(bool)arg1 ;
-(bool)hasTimedOut;
-(void)setHasCancelled:(bool)arg1 ;
-(bool)hasCancelled;
-(bool)hasInterfaceIdentifier;
-(bool)hasLocatorPeerAddress;
-(id)locatorScheme;
-(id)locatorHostname;
-(unsigned)locatorPort;
-(bool)connectionReused;
-(long long)responseReceivedDuration;
-(int)httpStatus;
-(int)requestSize;
-(int)responseSize;
-(bool)transactionComplete;
-(id)tcpInfos;
-(id)httpErrors;
-(id)locatorPeerAddress;
@end

