/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufMMCS.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufMMCS.dylib/libAWDProtobufMMCS.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSMutableArray, NSString;

@interface AWDMMCSGetRequestInfo : PBCodable <NSCopying> {

	long long _duration;
	long long _localBytes;
	long long _resumedBytes;
	long long _startTime;
	long long _timestamp;
	NSMutableArray* _authHttpInfos;
	NSMutableArray* _cancelErrors;
	int _cancelledErrorCode;
	NSString* _cancelledErrorDomain;
	NSString* _clientId;
	NSMutableArray* _completeHttpInfos;
	NSMutableArray* _containerHttpInfos;
	NSMutableArray* _errors;
	int _itemCount;
	int _itemsNeedingChunks;
	int _requestErrorCode;
	NSString* _requestErrorDomain;
	SCD_Struct_AW4 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) long long timestamp;                              //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) bool hasClientId; 
@property (nonatomic,retain) NSString * clientId;                              //@synthesize clientId=_clientId - In the implementation block
@property (assign,nonatomic) bool hasStartTime; 
@property (assign,nonatomic) long long startTime;                              //@synthesize startTime=_startTime - In the implementation block
@property (assign,nonatomic) bool hasDuration; 
@property (assign,nonatomic) long long duration;                               //@synthesize duration=_duration - In the implementation block
@property (nonatomic,readonly) bool hasCancelledErrorDomain; 
@property (nonatomic,retain) NSString * cancelledErrorDomain;                  //@synthesize cancelledErrorDomain=_cancelledErrorDomain - In the implementation block
@property (assign,nonatomic) bool hasCancelledErrorCode; 
@property (assign,nonatomic) int cancelledErrorCode;                           //@synthesize cancelledErrorCode=_cancelledErrorCode - In the implementation block
@property (nonatomic,readonly) bool hasRequestErrorDomain; 
@property (nonatomic,retain) NSString * requestErrorDomain;                    //@synthesize requestErrorDomain=_requestErrorDomain - In the implementation block
@property (assign,nonatomic) bool hasRequestErrorCode; 
@property (assign,nonatomic) int requestErrorCode;                             //@synthesize requestErrorCode=_requestErrorCode - In the implementation block
@property (assign,nonatomic) bool hasItemCount; 
@property (assign,nonatomic) int itemCount;                                    //@synthesize itemCount=_itemCount - In the implementation block
@property (assign,nonatomic) bool hasItemsNeedingChunks; 
@property (assign,nonatomic) int itemsNeedingChunks;                           //@synthesize itemsNeedingChunks=_itemsNeedingChunks - In the implementation block
@property (assign,nonatomic) bool hasLocalBytes; 
@property (assign,nonatomic) long long localBytes;                             //@synthesize localBytes=_localBytes - In the implementation block
@property (assign,nonatomic) bool hasResumedBytes; 
@property (assign,nonatomic) long long resumedBytes;                           //@synthesize resumedBytes=_resumedBytes - In the implementation block
@property (nonatomic,retain) NSMutableArray * authHttpInfos;                   //@synthesize authHttpInfos=_authHttpInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * containerHttpInfos;              //@synthesize containerHttpInfos=_containerHttpInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * completeHttpInfos;               //@synthesize completeHttpInfos=_completeHttpInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * cancelErrors;                    //@synthesize cancelErrors=_cancelErrors - In the implementation block
@property (nonatomic,retain) NSMutableArray * errors;                          //@synthesize errors=_errors - In the implementation block
-(void)setItemCount:(int)arg1 ;
-(int)itemCount;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(long long)timestamp;
-(long long)duration;
-(void)setDuration:(long long)arg1 ;
-(void)setStartTime:(long long)arg1 ;
-(void)setTimestamp:(long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(long long)startTime;
-(void)setClientId:(id)arg1 ;
-(id)clientId;
-(void)setHasStartTime:(bool)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(bool)hasDuration;
-(void)setHasDuration:(bool)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(bool)hasStartTime;
-(id)errors;
-(void)setErrors:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setCancelledErrorDomain:(id)arg1 ;
-(void)setRequestErrorDomain:(id)arg1 ;
-(void)setAuthHttpInfos:(id)arg1 ;
-(void)setContainerHttpInfos:(id)arg1 ;
-(void)setCompleteHttpInfos:(id)arg1 ;
-(void)setCancelErrors:(id)arg1 ;
-(void)addAuthHttpInfos:(id)arg1 ;
-(void)addContainerHttpInfos:(id)arg1 ;
-(void)addCompleteHttpInfos:(id)arg1 ;
-(void)addCancelError:(id)arg1 ;
-(void)addError:(id)arg1 ;
-(unsigned long long)authHttpInfosCount;
-(void)clearAuthHttpInfos;
-(id)authHttpInfosAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)containerHttpInfosCount;
-(void)clearContainerHttpInfos;
-(id)containerHttpInfosAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)completeHttpInfosCount;
-(void)clearCompleteHttpInfos;
-(id)completeHttpInfosAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)cancelErrorsCount;
-(void)clearCancelErrors;
-(id)cancelErrorAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)errorsCount;
-(void)clearErrors;
-(id)errorAtIndex:(unsigned long long)arg1 ;
-(bool)hasClientId;
-(bool)hasCancelledErrorDomain;
-(void)setCancelledErrorCode:(int)arg1 ;
-(void)setHasCancelledErrorCode:(bool)arg1 ;
-(bool)hasCancelledErrorCode;
-(bool)hasRequestErrorDomain;
-(void)setRequestErrorCode:(int)arg1 ;
-(void)setHasRequestErrorCode:(bool)arg1 ;
-(bool)hasRequestErrorCode;
-(void)setHasItemCount:(bool)arg1 ;
-(bool)hasItemCount;
-(id)cancelledErrorDomain;
-(int)cancelledErrorCode;
-(id)requestErrorDomain;
-(int)requestErrorCode;
-(id)authHttpInfos;
-(id)containerHttpInfos;
-(id)completeHttpInfos;
-(id)cancelErrors;
-(void)setItemsNeedingChunks:(int)arg1 ;
-(void)setHasItemsNeedingChunks:(bool)arg1 ;
-(bool)hasItemsNeedingChunks;
-(void)setLocalBytes:(long long)arg1 ;
-(void)setHasLocalBytes:(bool)arg1 ;
-(bool)hasLocalBytes;
-(void)setResumedBytes:(long long)arg1 ;
-(void)setHasResumedBytes:(bool)arg1 ;
-(bool)hasResumedBytes;
-(int)itemsNeedingChunks;
-(long long)localBytes;
-(long long)resumedBytes;
@end

