/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufMMCS.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufMMCS.dylib/libAWDProtobufMMCS.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSMutableArray, NSString;

@interface AWDMMCSChunkingInfo : PBCodable <NSCopying> {

	long long _byteCount;
	long long _chunkCount;
	long long _duration;
	long long _startTime;
	NSMutableArray* _chunkingErrors;
	int _errorCode;
	NSString* _errorDomain;
	bool _cancelled;
	SCD_Struct_AW5 _has;

}

@property (assign,nonatomic) bool hasChunkCount; 
@property (assign,nonatomic) long long chunkCount;                         //@synthesize chunkCount=_chunkCount - In the implementation block
@property (assign,nonatomic) bool hasByteCount; 
@property (assign,nonatomic) long long byteCount;                          //@synthesize byteCount=_byteCount - In the implementation block
@property (assign,nonatomic) bool hasStartTime; 
@property (assign,nonatomic) long long startTime;                          //@synthesize startTime=_startTime - In the implementation block
@property (assign,nonatomic) bool hasDuration; 
@property (assign,nonatomic) long long duration;                           //@synthesize duration=_duration - In the implementation block
@property (nonatomic,readonly) bool hasErrorDomain; 
@property (nonatomic,retain) NSString * errorDomain;                       //@synthesize errorDomain=_errorDomain - In the implementation block
@property (assign,nonatomic) bool hasErrorCode; 
@property (assign,nonatomic) int errorCode;                                //@synthesize errorCode=_errorCode - In the implementation block
@property (assign,nonatomic) bool hasCancelled; 
@property (assign,nonatomic) bool cancelled;                               //@synthesize cancelled=_cancelled - In the implementation block
@property (nonatomic,retain) NSMutableArray * chunkingErrors;              //@synthesize chunkingErrors=_chunkingErrors - In the implementation block
-(id)errorDomain;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(long long)duration;
-(void)setDuration:(long long)arg1 ;
-(void)setStartTime:(long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(bool)cancelled;
-(void)setCancelled:(bool)arg1 ;
-(id)dictionaryRepresentation;
-(long long)startTime;
-(void)setHasStartTime:(bool)arg1 ;
-(void)setErrorDomain:(id)arg1 ;
-(bool)hasErrorDomain;
-(bool)readFrom:(id)arg1 ;
-(bool)hasDuration;
-(void)setHasDuration:(bool)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(bool)hasStartTime;
-(void)setErrorCode:(int)arg1 ;
-(void)setHasErrorCode:(bool)arg1 ;
-(bool)hasErrorCode;
-(int)errorCode;
-(void)setHasCancelled:(bool)arg1 ;
-(bool)hasCancelled;
-(void)setChunkingErrors:(id)arg1 ;
-(void)addChunkingError:(id)arg1 ;
-(unsigned long long)chunkingErrorsCount;
-(void)clearChunkingErrors;
-(id)chunkingErrorAtIndex:(unsigned long long)arg1 ;
-(void)setChunkCount:(long long)arg1 ;
-(void)setHasChunkCount:(bool)arg1 ;
-(bool)hasChunkCount;
-(void)setByteCount:(long long)arg1 ;
-(void)setHasByteCount:(bool)arg1 ;
-(bool)hasByteCount;
-(long long)chunkCount;
-(long long)byteCount;
-(id)chunkingErrors;
@end

