/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufEasyConfig.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufEasyConfig.dylib/libAWDProtobufEasyConfig.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString, NSMutableArray;

@interface AWDEasyConfigCompleted : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _channelOfDestinationAP;
	unsigned _channelOfSWAP;
	NSString* _eaBundleSeedID;
	NSString* _eaFirmwareRevision;
	NSString* _eaHardwareRevision;
	NSString* _eaManufacturerName;
	NSString* _eaModelName;
	NSMutableArray* _eaProtocolStrings;
	int _easyConfigStoppedReasonError;
	int _rssiOfDestinationAP;
	int _rssiOfSWAP;
	float _secondsToApplyConfig;
	float _secondsToCompleteFullConfig;
	float _secondsToCompleteMFiSAPAuth;
	float _secondsToCompletePostConfigCheck;
	float _secondsToFindPostConfigDevice;
	float _secondsToFindPreConfigDevice;
	float _secondsToGetLinkUpOnDestination;
	float _secondsToGetLinkUpOnSWAP;
	unsigned _snrOfDestinationAP;
	unsigned _snrOfSWAP;
	int _wifiJoinDestinationAPError;
	int _wifiJoinSWAPError;
	bool _adminPasswordSet;
	bool _destinationNetworkPSKInKeychain;
	bool _destinationNetworkRecommendationUsed;
	bool _hitJoiningDestinationAPTimeout;
	bool _hitJoiningTargetSWAPTimeout;
	bool _pauseAfterApply;
	bool _playPasswordSet;
	bool _userChangedFriendlyName;
	SCD_Struct_AW1 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasUserChangedFriendlyName; 
@property (assign,nonatomic) bool userChangedFriendlyName;                              //@synthesize userChangedFriendlyName=_userChangedFriendlyName - In the implementation block
@property (assign,nonatomic) bool hasPlayPasswordSet; 
@property (assign,nonatomic) bool playPasswordSet;                                      //@synthesize playPasswordSet=_playPasswordSet - In the implementation block
@property (assign,nonatomic) bool hasAdminPasswordSet; 
@property (assign,nonatomic) bool adminPasswordSet;                                     //@synthesize adminPasswordSet=_adminPasswordSet - In the implementation block
@property (assign,nonatomic) bool hasDestinationNetworkRecommendationUsed; 
@property (assign,nonatomic) bool destinationNetworkRecommendationUsed;                 //@synthesize destinationNetworkRecommendationUsed=_destinationNetworkRecommendationUsed - In the implementation block
@property (assign,nonatomic) bool hasSecondsToCompleteFullConfig; 
@property (assign,nonatomic) float secondsToCompleteFullConfig;                         //@synthesize secondsToCompleteFullConfig=_secondsToCompleteFullConfig - In the implementation block
@property (assign,nonatomic) bool hasSecondsToGetLinkUpOnSWAP; 
@property (assign,nonatomic) float secondsToGetLinkUpOnSWAP;                            //@synthesize secondsToGetLinkUpOnSWAP=_secondsToGetLinkUpOnSWAP - In the implementation block
@property (assign,nonatomic) bool hasWifiJoinSWAPError; 
@property (assign,nonatomic) int wifiJoinSWAPError;                                     //@synthesize wifiJoinSWAPError=_wifiJoinSWAPError - In the implementation block
@property (assign,nonatomic) bool hasHitJoiningTargetSWAPTimeout; 
@property (assign,nonatomic) bool hitJoiningTargetSWAPTimeout;                          //@synthesize hitJoiningTargetSWAPTimeout=_hitJoiningTargetSWAPTimeout - In the implementation block
@property (assign,nonatomic) bool hasRssiOfSWAP; 
@property (assign,nonatomic) int rssiOfSWAP;                                            //@synthesize rssiOfSWAP=_rssiOfSWAP - In the implementation block
@property (assign,nonatomic) bool hasSnrOfSWAP; 
@property (assign,nonatomic) unsigned snrOfSWAP;                                        //@synthesize snrOfSWAP=_snrOfSWAP - In the implementation block
@property (assign,nonatomic) bool hasChannelOfSWAP; 
@property (assign,nonatomic) unsigned channelOfSWAP;                                    //@synthesize channelOfSWAP=_channelOfSWAP - In the implementation block
@property (assign,nonatomic) bool hasSecondsToGetLinkUpOnDestination; 
@property (assign,nonatomic) float secondsToGetLinkUpOnDestination;                     //@synthesize secondsToGetLinkUpOnDestination=_secondsToGetLinkUpOnDestination - In the implementation block
@property (assign,nonatomic) bool hasWifiJoinDestinationAPError; 
@property (assign,nonatomic) int wifiJoinDestinationAPError;                            //@synthesize wifiJoinDestinationAPError=_wifiJoinDestinationAPError - In the implementation block
@property (assign,nonatomic) bool hasDestinationNetworkPSKInKeychain; 
@property (assign,nonatomic) bool destinationNetworkPSKInKeychain;                      //@synthesize destinationNetworkPSKInKeychain=_destinationNetworkPSKInKeychain - In the implementation block
@property (assign,nonatomic) bool hasHitJoiningDestinationAPTimeout; 
@property (assign,nonatomic) bool hitJoiningDestinationAPTimeout;                       //@synthesize hitJoiningDestinationAPTimeout=_hitJoiningDestinationAPTimeout - In the implementation block
@property (assign,nonatomic) bool hasRssiOfDestinationAP; 
@property (assign,nonatomic) int rssiOfDestinationAP;                                   //@synthesize rssiOfDestinationAP=_rssiOfDestinationAP - In the implementation block
@property (assign,nonatomic) bool hasSnrOfDestinationAP; 
@property (assign,nonatomic) unsigned snrOfDestinationAP;                               //@synthesize snrOfDestinationAP=_snrOfDestinationAP - In the implementation block
@property (assign,nonatomic) bool hasChannelOfDestinationAP; 
@property (assign,nonatomic) unsigned channelOfDestinationAP;                           //@synthesize channelOfDestinationAP=_channelOfDestinationAP - In the implementation block
@property (assign,nonatomic) bool hasSecondsToFindPreConfigDevice; 
@property (assign,nonatomic) float secondsToFindPreConfigDevice;                        //@synthesize secondsToFindPreConfigDevice=_secondsToFindPreConfigDevice - In the implementation block
@property (assign,nonatomic) bool hasSecondsToCompleteMFiSAPAuth; 
@property (assign,nonatomic) float secondsToCompleteMFiSAPAuth;                         //@synthesize secondsToCompleteMFiSAPAuth=_secondsToCompleteMFiSAPAuth - In the implementation block
@property (assign,nonatomic) bool hasSecondsToApplyConfig; 
@property (assign,nonatomic) float secondsToApplyConfig;                                //@synthesize secondsToApplyConfig=_secondsToApplyConfig - In the implementation block
@property (assign,nonatomic) bool hasSecondsToFindPostConfigDevice; 
@property (assign,nonatomic) float secondsToFindPostConfigDevice;                       //@synthesize secondsToFindPostConfigDevice=_secondsToFindPostConfigDevice - In the implementation block
@property (assign,nonatomic) bool hasSecondsToCompletePostConfigCheck; 
@property (assign,nonatomic) float secondsToCompletePostConfigCheck;                    //@synthesize secondsToCompletePostConfigCheck=_secondsToCompletePostConfigCheck - In the implementation block
@property (assign,nonatomic) bool hasPauseAfterApply; 
@property (assign,nonatomic) bool pauseAfterApply;                                      //@synthesize pauseAfterApply=_pauseAfterApply - In the implementation block
@property (assign,nonatomic) bool hasEasyConfigStoppedReasonError; 
@property (assign,nonatomic) int easyConfigStoppedReasonError;                          //@synthesize easyConfigStoppedReasonError=_easyConfigStoppedReasonError - In the implementation block
@property (nonatomic,readonly) bool hasEaBundleSeedID; 
@property (nonatomic,retain) NSString * eaBundleSeedID;                                 //@synthesize eaBundleSeedID=_eaBundleSeedID - In the implementation block
@property (nonatomic,retain) NSMutableArray * eaProtocolStrings;                        //@synthesize eaProtocolStrings=_eaProtocolStrings - In the implementation block
@property (nonatomic,readonly) bool hasEaManufacturerName; 
@property (nonatomic,retain) NSString * eaManufacturerName;                             //@synthesize eaManufacturerName=_eaManufacturerName - In the implementation block
@property (nonatomic,readonly) bool hasEaModelName; 
@property (nonatomic,retain) NSString * eaModelName;                                    //@synthesize eaModelName=_eaModelName - In the implementation block
@property (nonatomic,readonly) bool hasEaFirmwareRevision; 
@property (nonatomic,retain) NSString * eaFirmwareRevision;                             //@synthesize eaFirmwareRevision=_eaFirmwareRevision - In the implementation block
@property (nonatomic,readonly) bool hasEaHardwareRevision; 
@property (nonatomic,retain) NSString * eaHardwareRevision;                             //@synthesize eaHardwareRevision=_eaHardwareRevision - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setEaBundleSeedID:(id)arg1 ;
-(void)setEaProtocolStrings:(id)arg1 ;
-(void)setEaManufacturerName:(id)arg1 ;
-(void)setEaModelName:(id)arg1 ;
-(void)setEaFirmwareRevision:(id)arg1 ;
-(void)setEaHardwareRevision:(id)arg1 ;
-(void)addEaProtocolStrings:(id)arg1 ;
-(unsigned long long)eaProtocolStringsCount;
-(void)clearEaProtocolStrings;
-(id)eaProtocolStringsAtIndex:(unsigned long long)arg1 ;
-(void)setUserChangedFriendlyName:(bool)arg1 ;
-(void)setHasUserChangedFriendlyName:(bool)arg1 ;
-(bool)hasUserChangedFriendlyName;
-(void)setPlayPasswordSet:(bool)arg1 ;
-(void)setHasPlayPasswordSet:(bool)arg1 ;
-(bool)hasPlayPasswordSet;
-(void)setAdminPasswordSet:(bool)arg1 ;
-(void)setHasAdminPasswordSet:(bool)arg1 ;
-(bool)hasAdminPasswordSet;
-(void)setDestinationNetworkRecommendationUsed:(bool)arg1 ;
-(void)setHasDestinationNetworkRecommendationUsed:(bool)arg1 ;
-(bool)hasDestinationNetworkRecommendationUsed;
-(void)setSecondsToCompleteFullConfig:(float)arg1 ;
-(void)setHasSecondsToCompleteFullConfig:(bool)arg1 ;
-(bool)hasSecondsToCompleteFullConfig;
-(void)setSecondsToGetLinkUpOnSWAP:(float)arg1 ;
-(void)setHasSecondsToGetLinkUpOnSWAP:(bool)arg1 ;
-(bool)hasSecondsToGetLinkUpOnSWAP;
-(void)setWifiJoinSWAPError:(int)arg1 ;
-(void)setHasWifiJoinSWAPError:(bool)arg1 ;
-(bool)hasWifiJoinSWAPError;
-(void)setHitJoiningTargetSWAPTimeout:(bool)arg1 ;
-(void)setHasHitJoiningTargetSWAPTimeout:(bool)arg1 ;
-(bool)hasHitJoiningTargetSWAPTimeout;
-(void)setRssiOfSWAP:(int)arg1 ;
-(void)setHasRssiOfSWAP:(bool)arg1 ;
-(bool)hasRssiOfSWAP;
-(void)setSnrOfSWAP:(unsigned)arg1 ;
-(void)setHasSnrOfSWAP:(bool)arg1 ;
-(bool)hasSnrOfSWAP;
-(void)setChannelOfSWAP:(unsigned)arg1 ;
-(void)setHasChannelOfSWAP:(bool)arg1 ;
-(bool)hasChannelOfSWAP;
-(void)setSecondsToGetLinkUpOnDestination:(float)arg1 ;
-(void)setHasSecondsToGetLinkUpOnDestination:(bool)arg1 ;
-(bool)hasSecondsToGetLinkUpOnDestination;
-(void)setWifiJoinDestinationAPError:(int)arg1 ;
-(void)setHasWifiJoinDestinationAPError:(bool)arg1 ;
-(bool)hasWifiJoinDestinationAPError;
-(void)setDestinationNetworkPSKInKeychain:(bool)arg1 ;
-(void)setHasDestinationNetworkPSKInKeychain:(bool)arg1 ;
-(bool)hasDestinationNetworkPSKInKeychain;
-(void)setHitJoiningDestinationAPTimeout:(bool)arg1 ;
-(void)setHasHitJoiningDestinationAPTimeout:(bool)arg1 ;
-(bool)hasHitJoiningDestinationAPTimeout;
-(void)setRssiOfDestinationAP:(int)arg1 ;
-(void)setHasRssiOfDestinationAP:(bool)arg1 ;
-(bool)hasRssiOfDestinationAP;
-(void)setSnrOfDestinationAP:(unsigned)arg1 ;
-(void)setHasSnrOfDestinationAP:(bool)arg1 ;
-(bool)hasSnrOfDestinationAP;
-(void)setChannelOfDestinationAP:(unsigned)arg1 ;
-(void)setHasChannelOfDestinationAP:(bool)arg1 ;
-(bool)hasChannelOfDestinationAP;
-(void)setSecondsToFindPreConfigDevice:(float)arg1 ;
-(void)setHasSecondsToFindPreConfigDevice:(bool)arg1 ;
-(bool)hasSecondsToFindPreConfigDevice;
-(void)setSecondsToCompleteMFiSAPAuth:(float)arg1 ;
-(void)setHasSecondsToCompleteMFiSAPAuth:(bool)arg1 ;
-(bool)hasSecondsToCompleteMFiSAPAuth;
-(void)setSecondsToApplyConfig:(float)arg1 ;
-(void)setHasSecondsToApplyConfig:(bool)arg1 ;
-(bool)hasSecondsToApplyConfig;
-(void)setSecondsToFindPostConfigDevice:(float)arg1 ;
-(void)setHasSecondsToFindPostConfigDevice:(bool)arg1 ;
-(bool)hasSecondsToFindPostConfigDevice;
-(void)setSecondsToCompletePostConfigCheck:(float)arg1 ;
-(void)setHasSecondsToCompletePostConfigCheck:(bool)arg1 ;
-(bool)hasSecondsToCompletePostConfigCheck;
-(void)setPauseAfterApply:(bool)arg1 ;
-(void)setHasPauseAfterApply:(bool)arg1 ;
-(bool)hasPauseAfterApply;
-(void)setEasyConfigStoppedReasonError:(int)arg1 ;
-(void)setHasEasyConfigStoppedReasonError:(bool)arg1 ;
-(bool)hasEasyConfigStoppedReasonError;
-(bool)hasEaBundleSeedID;
-(bool)hasEaManufacturerName;
-(bool)hasEaModelName;
-(bool)hasEaFirmwareRevision;
-(bool)hasEaHardwareRevision;
-(bool)userChangedFriendlyName;
-(bool)playPasswordSet;
-(bool)adminPasswordSet;
-(bool)destinationNetworkRecommendationUsed;
-(float)secondsToCompleteFullConfig;
-(float)secondsToGetLinkUpOnSWAP;
-(int)wifiJoinSWAPError;
-(bool)hitJoiningTargetSWAPTimeout;
-(int)rssiOfSWAP;
-(unsigned)snrOfSWAP;
-(unsigned)channelOfSWAP;
-(float)secondsToGetLinkUpOnDestination;
-(int)wifiJoinDestinationAPError;
-(bool)destinationNetworkPSKInKeychain;
-(bool)hitJoiningDestinationAPTimeout;
-(int)rssiOfDestinationAP;
-(unsigned)snrOfDestinationAP;
-(unsigned)channelOfDestinationAP;
-(float)secondsToFindPreConfigDevice;
-(float)secondsToCompleteMFiSAPAuth;
-(float)secondsToApplyConfig;
-(float)secondsToFindPostConfigDevice;
-(float)secondsToCompletePostConfigCheck;
-(bool)pauseAfterApply;
-(int)easyConfigStoppedReasonError;
-(id)eaBundleSeedID;
-(id)eaProtocolStrings;
-(id)eaManufacturerName;
-(id)eaModelName;
-(id)eaFirmwareRevision;
-(id)eaHardwareRevision;
@end

