/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libMobileGestaltExtensions.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_dispatch_source;
#import <libMobileGestaltExtensions.dylib/libMobileGestaltExtensions.dylib-Structs.h>
@class NSString, NSObject;

@interface MGFileWatcher : NSObject {

	NSString* _path;
	unsigned long long _inode;
	timespec _mtime;
	NSObject<OS_dispatch_queue>* _queue;
	NSObject<OS_dispatch_source>* _src;
	NSObject<OS_dispatch_source>* _parentSrc;
	/*^block*/ id _block;

}
-(void)dealloc;
-(void)cancel;
-(bool)updateWatcher;
-(id)initWithPath:(id)arg1 block:(/*^block*/ id)arg2 ;
@end

