/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libMobileGestaltExtensions.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMutableDictionary, NSObject;

@interface MGNotificationRegistration : NSObject {

	NSMutableDictionary* _observers;
	NSObject<OS_dispatch_queue>* _queue;
	/*^block*/ id _block;
	bool _deliverNotifications;
	NSMutableDictionary* _requestedRegistrations;

}
-(void)dealloc;
-(void)cancel;
-(bool)start;
-(id)initWithQueue:(id)arg1 block:(/*^block*/ id)arg2 ;
-(bool)registerForNotification:(int)arg1 argument:(const char*)arg2 question:(id)arg3 ;
@end

