/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:49 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <libmecabra.dylib/libmecabra.dylib-Structs.h>
@class NSString, NSArray, NSDictionary;

@interface CharacterInformationRepository : NSObject {

	IDXIndexRef _characterInfoDictionary;
	NSString* _currentCharacter;
	NSArray* _currentCharacterInfo;
	int _language;

}

@property (nonatomic,retain) NSString * currentCharacter;                         //@synthesize currentCharacter=_currentCharacter - In the implementation block
@property (nonatomic,readonly) NSDictionary * informationDictionary; 
@property (assign,nonatomic) int language;                                        //@synthesize language=_language - In the implementation block
@property (assign,nonatomic) IDXIndexRef characterInfoDictionary;                 //@synthesize characterInfoDictionary=_characterInfoDictionary - In the implementation block
@property (nonatomic,retain) NSArray * currentCharacterInfo;                      //@synthesize currentCharacterInfo=_currentCharacterInfo - In the implementation block
+(id)sharedCharacterInformationRepository;
-(void)dealloc;
-(id)init;
-(int)language;
-(void)setLanguage:(int)arg1 ;
-(void)setCurrentCharacter:(id)arg1 ;
-(id)informationDictionary;
-(IDXIndexRef)characterInfoDictionary;
-(id)searchResultsForCharacter:(id)arg1 ;
-(void)setCurrentCharacterInfo:(id)arg1 ;
-(id)currentCharacterInfo;
-(id)informationStringAtSlot:(int)arg1 ;
-(void)setCharacterInfoDictionary:(IDXIndexRef)arg1 ;
-(id)currentCharacter;
@end

