/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:48 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface CharacterInformationFormattedData : NSObject
-(id)candidatesSortedByRadical:(id)arg1 properties:(id)arg2 ;
-(id)candidatesSortedByStrokeCount:(id)arg1 properties:(id)arg2 ;
-(id)candidatesSortedByPinyin:(id)arg1 properties:(id)arg2 isZhuyin:(bool)arg3 ;
-(id)candidatesSortedByFrequency:(id)arg1 properties:(id)arg2 ;
@end

