/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:48 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary, NSString, NSArray;

@interface MecabraCandidateInformationEntry : NSObject {

	NSDictionary* _informationDictionary;
	NSString* _character;

}

@property (nonatomic,retain) NSDictionary * informationDictionary;              //@synthesize informationDictionary=_informationDictionary - In the implementation block
@property (nonatomic,retain) NSString * character;                              //@synthesize character=_character - In the implementation block
@property (nonatomic,readonly) NSString * radical; 
@property (nonatomic,readonly) long long firstStrokeCount; 
@property (nonatomic,readonly) NSArray * pinyinSyllables; 
@property (nonatomic,readonly) NSArray * zhuyinSyllables; 
@property (nonatomic,readonly) bool isSimplifiedOnly; 
@property (nonatomic,readonly) bool isTraditionalOnly; 
+(id)informationEntryWithCharacter:(id)arg1 language:(int)arg2 ;
-(void)dealloc;
-(id)character;
-(void)setCharacter:(id)arg1 ;
-(id)informationDictionary;
-(void)setInformationDictionary:(id)arg1 ;
-(id)radical;
-(long long)firstStrokeCount;
-(id)pinyinSyllables;
-(id)zhuyinSyllables;
-(bool)isSimplifiedOnly;
-(bool)isTraditionalOnly;
@end

