/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:48 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary, NSArray;

@interface MecabraCandidateCollectionFormatter : NSObject {

	NSMutableDictionary* _classifierToCandidateGroup;
	NSMutableDictionary* _candidateToStrokeCountGroup;

}

@property (nonatomic,retain) NSMutableDictionary * classifierToCandidateGroup;               //@synthesize classifierToCandidateGroup=_classifierToCandidateGroup - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * candidateToStrokeCountGroup;              //@synthesize candidateToStrokeCountGroup=_candidateToStrokeCountGroup - In the implementation block
@property (nonatomic,readonly) NSArray * classifierKeys; 
-(void)dealloc;
-(id)init;
-(void)setClassifierToCandidateGroup:(id)arg1 ;
-(void)setCandidateToStrokeCountGroup:(id)arg1 ;
-(id)classifierToCandidateGroup;
-(bool)candidateIsTraditionalOnly:(id)arg1 language:(int)arg2 ;
-(bool)candidateIsSimplifiedOnly:(id)arg1 language:(int)arg2 ;
-(id)candidateToStrokeCountGroup;
-(void)addCandidate:(id)arg1 forClassifier:(id)arg2 strokeCount:(unsigned long long)arg3 sortingType:(int)arg4 language:(int)arg5 ;
-(id)candidatesForClassifier:(id)arg1 ;
-(unsigned long long)strokeCountForCandidate:(id)arg1 ;
-(id)classifierKeys;
@end

