/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:49 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libmecabra.dylib/MecabraDatabase.h>

@class NSMutableDictionary;

@interface MecabraLearningDictionaryDatabase : MecabraDatabase {

	NSMutableDictionary* _cachedEntries;
	bool _dirty;
	unsigned long long _lastSeedValue;
	unsigned long long _lastUpdateTime;

}

@property (assign,nonatomic) unsigned long long lastSeedValue;                 //@synthesize lastSeedValue=_lastSeedValue - In the implementation block
@property (assign,nonatomic) unsigned long long lastUpdateTime;                //@synthesize lastUpdateTime=_lastUpdateTime - In the implementation block
@property (assign,nonatomic) bool sqliteDatabaseMigrated; 
@property (assign,nonatomic) unsigned long long versionNumber; 
@property (nonatomic,retain) NSMutableDictionary * cachedEntries;              //@synthesize cachedEntries=_cachedEntries - In the implementation block
@property (assign,nonatomic) bool dirty;                                       //@synthesize dirty=_dirty - In the implementation block
+(id)sharedDatabaseForURL:(id)arg1 type:(id)arg2 ;
+(id)sharedDatabases;
+(void)moveInternalDictionariesIfPresentAtURL:(id)arg1 type:(id)arg2 ;
-(unsigned long long)versionNumber;
-(unsigned long long)lastUpdateTime;
-(void)setLastUpdateTime:(unsigned long long)arg1 ;
-(bool)dirty;
-(void)refresh;
-(unsigned long long)lastSeedValue;
-(bool)sqliteDatabaseMigrated;
-(id)identifiersForEntry:(id)arg1 ;
-(id)setValuesForEntry:(id)arg1 uniquingKeys:(id)arg2 originalIdentifier:(unsigned long long)arg3 ;
-(unsigned long long)addEntryAndGetIdentifier:(id)arg1 ;
-(void)setLastSeedValue:(unsigned long long)arg1 ;
-(id)entryForIdentifier:(int)arg1 ;
-(void)rebuildCache;
-(id)allIdentifiers;
-(void)setSqliteDatabaseMigrated:(bool)arg1 ;
-(id)initWithURL:(id)arg1 type:(id)arg2 ;
-(void)setVersionNumber:(unsigned long long)arg1 ;
-(id)cachedEntries;
-(void)setDirty:(bool)arg1 ;
-(void)removeOldEntriesBasedOnMaxCount:(unsigned long long)arg1 ;
-(void)setCachedEntries:(id)arg1 ;
@end

