/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:49 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libmecabra.dylib/MecabraDatabaseAccessProtocol.h>

@class NSMutableDictionary;

@interface MecabraDatabaseInterface : NSObject <MecabraDatabaseAccessProtocol> {

	NSMutableDictionary* _databaseControllers;

}

@property (nonatomic,retain) NSMutableDictionary * databaseControllers;              //@synthesize databaseControllers=_databaseControllers - In the implementation block
-(void)readEntriesForType:(id)arg1 URL:(id)arg2 entry:(id)arg3 reply:(/*^block*/ id)arg4 ;
-(void)readPropertyForType:(id)arg1 URL:(id)arg2 propertyKey:(id)arg3 reply:(/*^block*/ id)arg4 ;
-(void)addEntry:(id)arg1 type:(id)arg2 URL:(id)arg3 reply:(/*^block*/ id)arg4 ;
-(id)readEntriesForType:(id)arg1 URL:(id)arg2 entry:(id)arg3 ;
-(unsigned long long)addEntryWithReturnedIdentifier:(id)arg1 type:(id)arg2 URL:(id)arg3 ;
-(void)addEntry:(id)arg1 type:(id)arg2 URL:(id)arg3 ;
-(void)deleteEntry:(id)arg1 type:(id)arg2 URL:(id)arg3 ;
-(void)deleteAllMatchingEntries:(id)arg1 type:(id)arg2 URL:(id)arg3 ;
-(void)setStringValue:(id)arg1 forKey:(id)arg2 entry:(id)arg3 type:(id)arg4 URL:(id)arg5 ;
-(void)setNumberValue:(id)arg1 forKey:(id)arg2 entry:(id)arg3 type:(id)arg4 URL:(id)arg5 ;
-(void)saveForType:(id)arg1 URL:(id)arg2 ;
-(void)setDatabaseStringProperty:(id)arg1 forKey:(id)arg2 type:(id)arg3 URL:(id)arg4 ;
-(void)setDatabaseNumberProperty:(id)arg1 forKey:(id)arg2 type:(id)arg3 URL:(id)arg4 ;
-(id)readPropertyForType:(id)arg1 URL:(id)arg2 propertyKey:(id)arg3 ;
-(id)removeDuplicatesForEntry:(id)arg1 type:(id)arg2 URL:(id)arg3 uniquingKeys:(id)arg4 sortDescriptors:(id)arg5 restrictToNumberOfElements:(unsigned long long)arg6 identifierKey:(id)arg7 ;
-(id)setValuesForEntry:(id)arg1 uniquingKeys:(id)arg2 type:(id)arg3 URL:(id)arg4 ;
-(id)entriesToMergeForType:(id)arg1 URL:(id)arg2 ;
-(void)clearStoredMergeEntriesForType:(id)arg1 URL:(id)arg2 ;
-(void)refreshForType:(id)arg1 URL:(id)arg2 ;
-(id)databaseControllers;
-(id)coreDataControllerForType:(id)arg1 URL:(id)arg2 ;
-(void)setDatabaseControllers:(id)arg1 ;
@end

