/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:49 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libmecabra.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <libmecabra.dylib/libmecabra.dylib-Structs.h>
@class NSArray, NSString;

@interface SingleWordCandidateSharedData : NSObject {

	NSArray* _syllableIDs;
	NSArray* _fuzzyMatchedSyllableIDs;
	NSArray* _syllableLengthsInAnalysisString;
	NSArray* _syllableLengthsInConvertedAnalysisString;
	NSArray* _syllableLengthsInDictionaryReading;
	NSArray* _syllableSeparatorCounts;
	NSString* _dictionaryReading;
	NSString* _analysisString;
	NSString* _convertedAnalysisString;
	unsigned _matchType;
	int _matchedLengthType;
	int _inputCodeType;
	bool _isFuzzy;
	bool _isAbbreviated;

}

@property (nonatomic,readonly) NSArray * syllableLengthsInAnalysisString;                       //@synthesize syllableLengthsInAnalysisString=_syllableLengthsInAnalysisString - In the implementation block
@property (nonatomic,readonly) NSArray * syllableLengthsInConvertedAnalysisString; 
@property (nonatomic,readonly) NSArray * syllableLengthsInDictionaryReading; 
@property (nonatomic,copy) NSString * dictionaryReading;                                        //@synthesize dictionaryReading=_dictionaryReading - In the implementation block
@property (nonatomic,copy) NSString * analysisString;                                           //@synthesize analysisString=_analysisString - In the implementation block
@property (nonatomic,copy) NSString * convertedAnalysisString;                                  //@synthesize convertedAnalysisString=_convertedAnalysisString - In the implementation block
@property (assign,nonatomic) unsigned matchedType;                                              //@synthesize matchType=_matchType - In the implementation block
@property (assign,nonatomic) int matchedLengthType;                                             //@synthesize matchedLengthType=_matchedLengthType - In the implementation block
@property (assign,nonatomic) bool isFuzzy;                                                      //@synthesize isFuzzy=_isFuzzy - In the implementation block
@property (nonatomic,readonly) int inputCodeType;                                               //@synthesize inputCodeType=_inputCodeType - In the implementation block
@property (nonatomic,readonly) bool isAbbreviated;                                              //@synthesize isAbbreviated=_isAbbreviated - In the implementation block
-(void)dealloc;
-(bool)isAbbreviated;
-(id)syllableLengthsInConvertedAnalysisString;
-(id)syllableLengthsInAnalysisString;
-(id)syllableLengthsInDictionaryReading;
-(bool)isFuzzy;
-(id)dictionaryReading;
-(id)analysisString;
-(id)convertedAnalysisString;
-(int)matchedLengthType;
-(int)inputCodeType;
-(unsigned)matchedType;
-(id)initWithSyllableSequence:(const SyllableSequence*)arg1 lookupContext:(const LookupContext*)arg2 ;
-(id)initWithWordCore:(const WordCore*)arg1 lookupContext:(const LookupContext*)arg2 ;
-(id)initWithDictionaryReading:(id)arg1 lookupContext:(const LookupContext*)arg2 ;
-(id)initWithSyllableIDs:(id)arg1 fuzzyMatchedSyllableIDs:(id)arg2 syllableLengthsInAnalysisString:(id)arg3 syllableLengthsInConvertedAnalysisString:(id)arg4 syllableSeparatorCounts:(id)arg5 analysisString:(id)arg6 convertedAnalysisString:(id)arg7 dictionaryReading:(id)arg8 lookupContext:(const LookupContext*)arg9 matchedLengthType:(int)arg10 isFuzzy:(bool)arg11 isAbbreviated:(bool)arg12 ;
-(id)initWithSyllableLengths:(id)arg1 analysisString:(id)arg2 dictionaryReading:(id)arg3 lookupContext:(const LookupContext*)arg4 matchedLengthType:(int)arg5 ;
-(id)initWithSyllableNode:(const SyllableNode*)arg1 completeSyllablePosition:(unsigned short)arg2 lookupContext:(const LookupContext*)arg3 ;
-(void)setDictionaryReading:(id)arg1 ;
-(void)setAnalysisString:(id)arg1 ;
-(void)setConvertedAnalysisString:(id)arg1 ;
-(void)setMatchedType:(unsigned)arg1 ;
-(void)setMatchedLengthType:(int)arg1 ;
-(void)setIsFuzzy:(bool)arg1 ;
@end

