/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufSiri.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufSiri.dylib/libAWDProtobufSiri.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDSiriServerConnectionFailed : PBCodable <NSCopying> {

	long long _errorCode;
	unsigned long long _timestamp;
	int _connectionType;
	NSString* _errorDomain;
	SCD_Struct_AW2 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) bool hasErrorDomain; 
@property (nonatomic,retain) NSString * errorDomain;                    //@synthesize errorDomain=_errorDomain - In the implementation block
@property (assign,nonatomic) bool hasErrorCode; 
@property (assign,nonatomic) long long errorCode;                       //@synthesize errorCode=_errorCode - In the implementation block
@property (assign,nonatomic) bool hasConnectionType; 
@property (assign,nonatomic) int connectionType;                        //@synthesize connectionType=_connectionType - In the implementation block
-(id)errorDomain;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(int)connectionType;
-(void)setConnectionType:(int)arg1 ;
-(void)setErrorDomain:(id)arg1 ;
-(bool)hasErrorDomain;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setErrorCode:(long long)arg1 ;
-(void)setHasErrorCode:(bool)arg1 ;
-(bool)hasErrorCode;
-(long long)errorCode;
-(void)setHasConnectionType:(bool)arg1 ;
-(bool)hasConnectionType;
@end

