/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufSiri.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufSiri.dylib/libAWDProtobufSiri.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDSiriSpeechRecognized : PBCodable <NSCopying> {

	unsigned long long _durationFromVoiceRecordingEnd;
	unsigned long long _durationFromVoiceSendEnd;
	unsigned long long _timestamp;
	SCD_Struct_AW2 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                                  //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasDurationFromVoiceRecordingEnd; 
@property (assign,nonatomic) unsigned long long durationFromVoiceRecordingEnd;              //@synthesize durationFromVoiceRecordingEnd=_durationFromVoiceRecordingEnd - In the implementation block
@property (assign,nonatomic) bool hasDurationFromVoiceSendEnd; 
@property (assign,nonatomic) unsigned long long durationFromVoiceSendEnd;                   //@synthesize durationFromVoiceSendEnd=_durationFromVoiceSendEnd - In the implementation block
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setDurationFromVoiceRecordingEnd:(unsigned long long)arg1 ;
-(void)setHasDurationFromVoiceRecordingEnd:(bool)arg1 ;
-(bool)hasDurationFromVoiceRecordingEnd;
-(void)setDurationFromVoiceSendEnd:(unsigned long long)arg1 ;
-(void)setHasDurationFromVoiceSendEnd:(bool)arg1 ;
-(bool)hasDurationFromVoiceSendEnd;
-(unsigned long long)durationFromVoiceRecordingEnd;
-(unsigned long long)durationFromVoiceSendEnd;
@end

