/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufSiri.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufSiri.dylib/libAWDProtobufSiri.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDSiriNetworkAnalyzerRun : PBCodable <NSCopying> {

	unsigned long long _gatewayPingDuration;
	unsigned long long _knownURLLoadDuration;
	unsigned long long _siriSaltURLLoadDuration;
	unsigned long long _siriURLLoadDuration;
	unsigned long long _timestamp;
	unsigned _gatewayPingsDropped;
	unsigned _gatewayPingsSent;
	int _gatewayStatus;
	int _interface;
	int _sendBufferBytesRemaining;
	bool _analyzingSuccessfulRetry;
	bool _isUserRequest;
	bool _wwanPreferred;
	SCD_Struct_AW1 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                            //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasInterface; 
@property (assign,nonatomic) int interface;                                           //@synthesize interface=_interface - In the implementation block
@property (assign,nonatomic) bool hasIsUserRequest; 
@property (assign,nonatomic) bool isUserRequest;                                      //@synthesize isUserRequest=_isUserRequest - In the implementation block
@property (assign,nonatomic) bool hasAnalyzingSuccessfulRetry; 
@property (assign,nonatomic) bool analyzingSuccessfulRetry;                           //@synthesize analyzingSuccessfulRetry=_analyzingSuccessfulRetry - In the implementation block
@property (assign,nonatomic) bool hasWwanPreferred; 
@property (assign,nonatomic) bool wwanPreferred;                                      //@synthesize wwanPreferred=_wwanPreferred - In the implementation block
@property (assign,nonatomic) bool hasSendBufferBytesRemaining; 
@property (assign,nonatomic) int sendBufferBytesRemaining;                            //@synthesize sendBufferBytesRemaining=_sendBufferBytesRemaining - In the implementation block
@property (assign,nonatomic) bool hasKnownURLLoadDuration; 
@property (assign,nonatomic) unsigned long long knownURLLoadDuration;                 //@synthesize knownURLLoadDuration=_knownURLLoadDuration - In the implementation block
@property (assign,nonatomic) bool hasSiriURLLoadDuration; 
@property (assign,nonatomic) unsigned long long siriURLLoadDuration;                  //@synthesize siriURLLoadDuration=_siriURLLoadDuration - In the implementation block
@property (assign,nonatomic) bool hasSiriSaltURLLoadDuration; 
@property (assign,nonatomic) unsigned long long siriSaltURLLoadDuration;              //@synthesize siriSaltURLLoadDuration=_siriSaltURLLoadDuration - In the implementation block
@property (assign,nonatomic) bool hasGatewayStatus; 
@property (assign,nonatomic) int gatewayStatus;                                       //@synthesize gatewayStatus=_gatewayStatus - In the implementation block
@property (assign,nonatomic) bool hasGatewayPingDuration; 
@property (assign,nonatomic) unsigned long long gatewayPingDuration;                  //@synthesize gatewayPingDuration=_gatewayPingDuration - In the implementation block
@property (assign,nonatomic) bool hasGatewayPingsSent; 
@property (assign,nonatomic) unsigned gatewayPingsSent;                               //@synthesize gatewayPingsSent=_gatewayPingsSent - In the implementation block
@property (assign,nonatomic) bool hasGatewayPingsDropped; 
@property (assign,nonatomic) unsigned gatewayPingsDropped;                            //@synthesize gatewayPingsDropped=_gatewayPingsDropped - In the implementation block
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(int)interface;
-(void)setInterface:(int)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setHasInterface:(bool)arg1 ;
-(bool)hasInterface;
-(void)setIsUserRequest:(bool)arg1 ;
-(void)setHasIsUserRequest:(bool)arg1 ;
-(bool)hasIsUserRequest;
-(void)setAnalyzingSuccessfulRetry:(bool)arg1 ;
-(void)setHasAnalyzingSuccessfulRetry:(bool)arg1 ;
-(bool)hasAnalyzingSuccessfulRetry;
-(void)setWwanPreferred:(bool)arg1 ;
-(void)setHasWwanPreferred:(bool)arg1 ;
-(bool)hasWwanPreferred;
-(void)setSendBufferBytesRemaining:(int)arg1 ;
-(void)setHasSendBufferBytesRemaining:(bool)arg1 ;
-(bool)hasSendBufferBytesRemaining;
-(void)setKnownURLLoadDuration:(unsigned long long)arg1 ;
-(void)setHasKnownURLLoadDuration:(bool)arg1 ;
-(bool)hasKnownURLLoadDuration;
-(void)setSiriURLLoadDuration:(unsigned long long)arg1 ;
-(void)setHasSiriURLLoadDuration:(bool)arg1 ;
-(bool)hasSiriURLLoadDuration;
-(void)setSiriSaltURLLoadDuration:(unsigned long long)arg1 ;
-(void)setHasSiriSaltURLLoadDuration:(bool)arg1 ;
-(bool)hasSiriSaltURLLoadDuration;
-(void)setGatewayStatus:(int)arg1 ;
-(void)setHasGatewayStatus:(bool)arg1 ;
-(bool)hasGatewayStatus;
-(void)setGatewayPingDuration:(unsigned long long)arg1 ;
-(void)setHasGatewayPingDuration:(bool)arg1 ;
-(bool)hasGatewayPingDuration;
-(void)setGatewayPingsSent:(unsigned)arg1 ;
-(void)setHasGatewayPingsSent:(bool)arg1 ;
-(bool)hasGatewayPingsSent;
-(void)setGatewayPingsDropped:(unsigned)arg1 ;
-(void)setHasGatewayPingsDropped:(bool)arg1 ;
-(bool)hasGatewayPingsDropped;
-(bool)isUserRequest;
-(bool)analyzingSuccessfulRetry;
-(bool)wwanPreferred;
-(int)sendBufferBytesRemaining;
-(unsigned long long)knownURLLoadDuration;
-(unsigned long long)siriURLLoadDuration;
-(unsigned long long)siriSaltURLLoadDuration;
-(int)gatewayStatus;
-(unsigned long long)gatewayPingDuration;
-(unsigned)gatewayPingsSent;
-(unsigned)gatewayPingsDropped;
@end

