/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufCaptive.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufCaptive.dylib/libAWDProtobufCaptive.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString, NSMutableArray;

@interface AWDCaptiveSession : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	NSString* _appTriggeredPassiveSymptom;
	NSString* _autoLoginCarrierID;
	unsigned _autoLoginType;
	unsigned _durationNetworkNotCaptive;
	unsigned _durationOnNetwork;
	NSString* _handlerCNP;
	NSMutableArray* _installedCNPDisplayIDs;
	unsigned _passiveCaptivityCorrectDetection;
	unsigned _passiveCaptivityIncorrectDetection;
	unsigned _passiveCaptivitySymptom;
	unsigned _result;
	unsigned _websheetProbeCount;
	unsigned _websheetScrapeResult;
	bool _autoLoginFailed;
	bool _detectedNotCaptiveHandledByCNP;
	bool _handlerCNPTriggeredLogOff;
	bool _isDetectedCaptive;
	bool _passiveCaptivityDetected;
	bool _websheetScraped;
	bool _wisprDetected;
	SCD_Struct_AW1 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                             //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasResult; 
@property (assign,nonatomic) unsigned result;                                          //@synthesize result=_result - In the implementation block
@property (assign,nonatomic) bool hasWebsheetProbeCount; 
@property (assign,nonatomic) unsigned websheetProbeCount;                              //@synthesize websheetProbeCount=_websheetProbeCount - In the implementation block
@property (assign,nonatomic) bool hasWebsheetScraped; 
@property (assign,nonatomic) bool websheetScraped;                                     //@synthesize websheetScraped=_websheetScraped - In the implementation block
@property (assign,nonatomic) bool hasWebsheetScrapeResult; 
@property (assign,nonatomic) unsigned websheetScrapeResult;                            //@synthesize websheetScrapeResult=_websheetScrapeResult - In the implementation block
@property (nonatomic,retain) NSMutableArray * installedCNPDisplayIDs;                  //@synthesize installedCNPDisplayIDs=_installedCNPDisplayIDs - In the implementation block
@property (nonatomic,readonly) bool hasHandlerCNP; 
@property (nonatomic,retain) NSString * handlerCNP;                                    //@synthesize handlerCNP=_handlerCNP - In the implementation block
@property (assign,nonatomic) bool hasDetectedNotCaptiveHandledByCNP; 
@property (assign,nonatomic) bool detectedNotCaptiveHandledByCNP;                      //@synthesize detectedNotCaptiveHandledByCNP=_detectedNotCaptiveHandledByCNP - In the implementation block
@property (assign,nonatomic) bool hasAutoLoginType; 
@property (assign,nonatomic) unsigned autoLoginType;                                   //@synthesize autoLoginType=_autoLoginType - In the implementation block
@property (assign,nonatomic) bool hasAutoLoginFailed; 
@property (assign,nonatomic) bool autoLoginFailed;                                     //@synthesize autoLoginFailed=_autoLoginFailed - In the implementation block
@property (nonatomic,readonly) bool hasAutoLoginCarrierID; 
@property (nonatomic,retain) NSString * autoLoginCarrierID;                            //@synthesize autoLoginCarrierID=_autoLoginCarrierID - In the implementation block
@property (assign,nonatomic) bool hasWisprDetected; 
@property (assign,nonatomic) bool wisprDetected;                                       //@synthesize wisprDetected=_wisprDetected - In the implementation block
@property (assign,nonatomic) bool hasPassiveCaptivityDetected; 
@property (assign,nonatomic) bool passiveCaptivityDetected;                            //@synthesize passiveCaptivityDetected=_passiveCaptivityDetected - In the implementation block
@property (assign,nonatomic) bool hasPassiveCaptivityCorrectDetection; 
@property (assign,nonatomic) unsigned passiveCaptivityCorrectDetection;                //@synthesize passiveCaptivityCorrectDetection=_passiveCaptivityCorrectDetection - In the implementation block
@property (assign,nonatomic) bool hasPassiveCaptivityIncorrectDetection; 
@property (assign,nonatomic) unsigned passiveCaptivityIncorrectDetection;              //@synthesize passiveCaptivityIncorrectDetection=_passiveCaptivityIncorrectDetection - In the implementation block
@property (assign,nonatomic) bool hasHandlerCNPTriggeredLogOff; 
@property (assign,nonatomic) bool handlerCNPTriggeredLogOff;                           //@synthesize handlerCNPTriggeredLogOff=_handlerCNPTriggeredLogOff - In the implementation block
@property (assign,nonatomic) bool hasIsDetectedCaptive; 
@property (assign,nonatomic) bool isDetectedCaptive;                                   //@synthesize isDetectedCaptive=_isDetectedCaptive - In the implementation block
@property (assign,nonatomic) bool hasDurationOnNetwork; 
@property (assign,nonatomic) unsigned durationOnNetwork;                               //@synthesize durationOnNetwork=_durationOnNetwork - In the implementation block
@property (assign,nonatomic) bool hasDurationNetworkNotCaptive; 
@property (assign,nonatomic) unsigned durationNetworkNotCaptive;                       //@synthesize durationNetworkNotCaptive=_durationNetworkNotCaptive - In the implementation block
@property (assign,nonatomic) bool hasPassiveCaptivitySymptom; 
@property (assign,nonatomic) unsigned passiveCaptivitySymptom;                         //@synthesize passiveCaptivitySymptom=_passiveCaptivitySymptom - In the implementation block
@property (nonatomic,readonly) bool hasAppTriggeredPassiveSymptom; 
@property (nonatomic,retain) NSString * appTriggeredPassiveSymptom;                    //@synthesize appTriggeredPassiveSymptom=_appTriggeredPassiveSymptom - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(void)setResult:(unsigned)arg1 ;
-(unsigned)result;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setInstalledCNPDisplayIDs:(id)arg1 ;
-(void)setHandlerCNP:(id)arg1 ;
-(void)setAutoLoginCarrierID:(id)arg1 ;
-(void)setAppTriggeredPassiveSymptom:(id)arg1 ;
-(void)addInstalledCNPDisplayIDs:(id)arg1 ;
-(unsigned long long)installedCNPDisplayIDsCount;
-(void)clearInstalledCNPDisplayIDs;
-(id)installedCNPDisplayIDsAtIndex:(unsigned long long)arg1 ;
-(void)setHasResult:(bool)arg1 ;
-(bool)hasResult;
-(void)setWebsheetProbeCount:(unsigned)arg1 ;
-(void)setHasWebsheetProbeCount:(bool)arg1 ;
-(bool)hasWebsheetProbeCount;
-(void)setWebsheetScraped:(bool)arg1 ;
-(void)setHasWebsheetScraped:(bool)arg1 ;
-(bool)hasWebsheetScraped;
-(void)setWebsheetScrapeResult:(unsigned)arg1 ;
-(void)setHasWebsheetScrapeResult:(bool)arg1 ;
-(bool)hasWebsheetScrapeResult;
-(bool)hasHandlerCNP;
-(void)setDetectedNotCaptiveHandledByCNP:(bool)arg1 ;
-(void)setHasDetectedNotCaptiveHandledByCNP:(bool)arg1 ;
-(bool)hasDetectedNotCaptiveHandledByCNP;
-(void)setAutoLoginType:(unsigned)arg1 ;
-(void)setHasAutoLoginType:(bool)arg1 ;
-(bool)hasAutoLoginType;
-(void)setAutoLoginFailed:(bool)arg1 ;
-(void)setHasAutoLoginFailed:(bool)arg1 ;
-(bool)hasAutoLoginFailed;
-(bool)hasAutoLoginCarrierID;
-(void)setWisprDetected:(bool)arg1 ;
-(void)setHasWisprDetected:(bool)arg1 ;
-(bool)hasWisprDetected;
-(void)setPassiveCaptivityDetected:(bool)arg1 ;
-(void)setHasPassiveCaptivityDetected:(bool)arg1 ;
-(bool)hasPassiveCaptivityDetected;
-(void)setPassiveCaptivityCorrectDetection:(unsigned)arg1 ;
-(void)setHasPassiveCaptivityCorrectDetection:(bool)arg1 ;
-(bool)hasPassiveCaptivityCorrectDetection;
-(void)setPassiveCaptivityIncorrectDetection:(unsigned)arg1 ;
-(void)setHasPassiveCaptivityIncorrectDetection:(bool)arg1 ;
-(bool)hasPassiveCaptivityIncorrectDetection;
-(void)setHandlerCNPTriggeredLogOff:(bool)arg1 ;
-(void)setHasHandlerCNPTriggeredLogOff:(bool)arg1 ;
-(bool)hasHandlerCNPTriggeredLogOff;
-(void)setIsDetectedCaptive:(bool)arg1 ;
-(void)setHasIsDetectedCaptive:(bool)arg1 ;
-(bool)hasIsDetectedCaptive;
-(void)setDurationOnNetwork:(unsigned)arg1 ;
-(void)setHasDurationOnNetwork:(bool)arg1 ;
-(bool)hasDurationOnNetwork;
-(void)setDurationNetworkNotCaptive:(unsigned)arg1 ;
-(void)setHasDurationNetworkNotCaptive:(bool)arg1 ;
-(bool)hasDurationNetworkNotCaptive;
-(void)setPassiveCaptivitySymptom:(unsigned)arg1 ;
-(void)setHasPassiveCaptivitySymptom:(bool)arg1 ;
-(bool)hasPassiveCaptivitySymptom;
-(bool)hasAppTriggeredPassiveSymptom;
-(unsigned)websheetProbeCount;
-(bool)websheetScraped;
-(unsigned)websheetScrapeResult;
-(id)installedCNPDisplayIDs;
-(id)handlerCNP;
-(bool)detectedNotCaptiveHandledByCNP;
-(unsigned)autoLoginType;
-(bool)autoLoginFailed;
-(id)autoLoginCarrierID;
-(bool)wisprDetected;
-(bool)passiveCaptivityDetected;
-(unsigned)passiveCaptivityCorrectDetection;
-(unsigned)passiveCaptivityIncorrectDetection;
-(bool)handlerCNPTriggeredLogOff;
-(bool)isDetectedCaptive;
-(unsigned)durationOnNetwork;
-(unsigned)durationNetworkNotCaptive;
-(unsigned)passiveCaptivitySymptom;
-(id)appTriggeredPassiveSymptom;
@end

