/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDWiFiMetricsManagerWatchdogEvent : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	int _available;
	unsigned _deviceIdentifierMap;
	unsigned _flags;
	int _reason;
	unsigned _subreason;
	unsigned _version;
	SCD_Struct_AW12 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasVersion; 
@property (assign,nonatomic) unsigned version;                          //@synthesize version=_version - In the implementation block
@property (assign,nonatomic) bool hasFlags; 
@property (assign,nonatomic) unsigned flags;                            //@synthesize flags=_flags - In the implementation block
@property (assign,nonatomic) bool hasAvailable; 
@property (assign,nonatomic) int available;                             //@synthesize available=_available - In the implementation block
@property (assign,nonatomic) bool hasReason; 
@property (assign,nonatomic) int reason;                                //@synthesize reason=_reason - In the implementation block
@property (assign,nonatomic) bool hasSubreason; 
@property (assign,nonatomic) unsigned subreason;                        //@synthesize subreason=_subreason - In the implementation block
@property (assign,nonatomic) bool hasDeviceIdentifierMap; 
@property (assign,nonatomic) unsigned deviceIdentifierMap;              //@synthesize deviceIdentifierMap=_deviceIdentifierMap - In the implementation block
-(void)setReason:(int)arg1 ;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(void)setVersion:(unsigned)arg1 ;
-(unsigned)version;
-(int)reason;
-(unsigned)flags;
-(int)available;
-(void)setAvailable:(int)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(void)setFlags:(unsigned)arg1 ;
-(bool)hasFlags;
-(void)setHasFlags:(bool)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)setHasVersion:(bool)arg1 ;
-(bool)hasVersion;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setHasReason:(bool)arg1 ;
-(bool)hasReason;
-(void)setSubreason:(unsigned)arg1 ;
-(void)setHasSubreason:(bool)arg1 ;
-(bool)hasSubreason;
-(unsigned)subreason;
-(void)setDeviceIdentifierMap:(unsigned)arg1 ;
-(void)setHasDeviceIdentifierMap:(bool)arg1 ;
-(bool)hasDeviceIdentifierMap;
-(unsigned)deviceIdentifierMap;
-(void)setHasAvailable:(bool)arg1 ;
-(bool)hasAvailable;
@end

