/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSData;

@interface AWDWiFiMetricLinkChangeData : PBCodable <NSCopying> {

	SCD_Struct_AW4* _rssiHistorys;
	unsigned long long _timestamp;
	unsigned _akmSuites;
	unsigned _capabilities;
	unsigned _channel;
	unsigned _channelWidth;
	unsigned _flags;
	unsigned _htASel;
	unsigned _htAmpduParams;
	unsigned _htExtended;
	unsigned _htInfo;
	NSData* _htSupportedMcsSet;
	unsigned _htTxBf;
	unsigned _mcastCipher;
	NSData* _oui;
	unsigned _phyMode;
	unsigned _reason;
	unsigned _securityType;
	unsigned _subreason;
	unsigned _ucastCipher;
	unsigned _vhtInfo;
	NSData* _vhtSupportedMcsSet;
	unsigned _wpaProtocol;
	bool _isInVol;
	bool _isLinkUp;
	SCD_Struct_AW5 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                        //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) unsigned long long rssiHistorysCount; 
@property (nonatomic,readonly) int* rssiHistorys; 
@property (assign,nonatomic) bool hasIsLinkUp; 
@property (assign,nonatomic) bool isLinkUp;                                       //@synthesize isLinkUp=_isLinkUp - In the implementation block
@property (assign,nonatomic) bool hasIsInVol; 
@property (assign,nonatomic) bool isInVol;                                        //@synthesize isInVol=_isInVol - In the implementation block
@property (assign,nonatomic) bool hasReason; 
@property (assign,nonatomic) unsigned reason;                                     //@synthesize reason=_reason - In the implementation block
@property (assign,nonatomic) bool hasSubreason; 
@property (assign,nonatomic) unsigned subreason;                                  //@synthesize subreason=_subreason - In the implementation block
@property (assign,nonatomic) bool hasChannel; 
@property (assign,nonatomic) unsigned channel;                                    //@synthesize channel=_channel - In the implementation block
@property (assign,nonatomic) bool hasChannelWidth; 
@property (assign,nonatomic) unsigned channelWidth;                               //@synthesize channelWidth=_channelWidth - In the implementation block
@property (assign,nonatomic) bool hasPhyMode; 
@property (assign,nonatomic) unsigned phyMode;                                    //@synthesize phyMode=_phyMode - In the implementation block
@property (assign,nonatomic) bool hasFlags; 
@property (assign,nonatomic) unsigned flags;                                      //@synthesize flags=_flags - In the implementation block
@property (nonatomic,readonly) bool hasOui; 
@property (nonatomic,retain) NSData * oui;                                        //@synthesize oui=_oui - In the implementation block
@property (assign,nonatomic) bool hasSecurityType; 
@property (assign,nonatomic) unsigned securityType;                               //@synthesize securityType=_securityType - In the implementation block
@property (assign,nonatomic) bool hasWpaProtocol; 
@property (assign,nonatomic) unsigned wpaProtocol;                                //@synthesize wpaProtocol=_wpaProtocol - In the implementation block
@property (assign,nonatomic) bool hasMcastCipher; 
@property (assign,nonatomic) unsigned mcastCipher;                                //@synthesize mcastCipher=_mcastCipher - In the implementation block
@property (assign,nonatomic) bool hasUcastCipher; 
@property (assign,nonatomic) unsigned ucastCipher;                                //@synthesize ucastCipher=_ucastCipher - In the implementation block
@property (assign,nonatomic) bool hasAkmSuites; 
@property (assign,nonatomic) unsigned akmSuites;                                  //@synthesize akmSuites=_akmSuites - In the implementation block
@property (assign,nonatomic) bool hasCapabilities; 
@property (assign,nonatomic) unsigned capabilities;                               //@synthesize capabilities=_capabilities - In the implementation block
@property (assign,nonatomic) bool hasHtInfo; 
@property (assign,nonatomic) unsigned htInfo;                                     //@synthesize htInfo=_htInfo - In the implementation block
@property (assign,nonatomic) bool hasHtExtended; 
@property (assign,nonatomic) unsigned htExtended;                                 //@synthesize htExtended=_htExtended - In the implementation block
@property (assign,nonatomic) bool hasHtTxBf; 
@property (assign,nonatomic) unsigned htTxBf;                                     //@synthesize htTxBf=_htTxBf - In the implementation block
@property (assign,nonatomic) bool hasHtASel; 
@property (assign,nonatomic) unsigned htASel;                                     //@synthesize htASel=_htASel - In the implementation block
@property (assign,nonatomic) bool hasHtAmpduParams; 
@property (assign,nonatomic) unsigned htAmpduParams;                              //@synthesize htAmpduParams=_htAmpduParams - In the implementation block
@property (nonatomic,readonly) bool hasHtSupportedMcsSet; 
@property (nonatomic,retain) NSData * htSupportedMcsSet;                          //@synthesize htSupportedMcsSet=_htSupportedMcsSet - In the implementation block
@property (assign,nonatomic) bool hasVhtInfo; 
@property (assign,nonatomic) unsigned vhtInfo;                                    //@synthesize vhtInfo=_vhtInfo - In the implementation block
@property (nonatomic,readonly) bool hasVhtSupportedMcsSet; 
@property (nonatomic,retain) NSData * vhtSupportedMcsSet;                         //@synthesize vhtSupportedMcsSet=_vhtSupportedMcsSet - In the implementation block
-(void)setReason:(unsigned)arg1 ;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned)reason;
-(unsigned)flags;
-(void)setCapabilities:(unsigned)arg1 ;
-(unsigned)capabilities;
-(bool)readFrom:(id)arg1 ;
-(void)setFlags:(unsigned)arg1 ;
-(bool)hasFlags;
-(void)setHasFlags:(bool)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setChannel:(unsigned)arg1 ;
-(unsigned)channel;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setHasChannel:(bool)arg1 ;
-(bool)hasChannel;
-(void)setOui:(id)arg1 ;
-(void)setHtSupportedMcsSet:(id)arg1 ;
-(void)setVhtSupportedMcsSet:(id)arg1 ;
-(unsigned long long)rssiHistorysCount;
-(void)clearRssiHistorys;
-(int)rssiHistoryAtIndex:(unsigned long long)arg1 ;
-(void)addRssiHistory:(int)arg1 ;
-(int*)rssiHistorys;
-(void)setRssiHistorys:(int*)arg1 count:(unsigned long long)arg2 ;
-(void)setIsLinkUp:(bool)arg1 ;
-(void)setHasIsLinkUp:(bool)arg1 ;
-(bool)hasIsLinkUp;
-(void)setIsInVol:(bool)arg1 ;
-(void)setHasIsInVol:(bool)arg1 ;
-(bool)hasIsInVol;
-(void)setHasReason:(bool)arg1 ;
-(bool)hasReason;
-(void)setSubreason:(unsigned)arg1 ;
-(void)setHasSubreason:(bool)arg1 ;
-(bool)hasSubreason;
-(void)setChannelWidth:(unsigned)arg1 ;
-(void)setHasChannelWidth:(bool)arg1 ;
-(bool)hasChannelWidth;
-(void)setPhyMode:(unsigned)arg1 ;
-(void)setHasPhyMode:(bool)arg1 ;
-(bool)hasPhyMode;
-(bool)hasOui;
-(void)setSecurityType:(unsigned)arg1 ;
-(void)setHasSecurityType:(bool)arg1 ;
-(bool)hasSecurityType;
-(void)setWpaProtocol:(unsigned)arg1 ;
-(void)setHasWpaProtocol:(bool)arg1 ;
-(bool)hasWpaProtocol;
-(void)setMcastCipher:(unsigned)arg1 ;
-(void)setHasMcastCipher:(bool)arg1 ;
-(bool)hasMcastCipher;
-(void)setUcastCipher:(unsigned)arg1 ;
-(void)setHasUcastCipher:(bool)arg1 ;
-(bool)hasUcastCipher;
-(void)setAkmSuites:(unsigned)arg1 ;
-(void)setHasAkmSuites:(bool)arg1 ;
-(bool)hasAkmSuites;
-(void)setHasCapabilities:(bool)arg1 ;
-(bool)hasCapabilities;
-(void)setHtInfo:(unsigned)arg1 ;
-(void)setHasHtInfo:(bool)arg1 ;
-(bool)hasHtInfo;
-(void)setHtExtended:(unsigned)arg1 ;
-(void)setHasHtExtended:(bool)arg1 ;
-(bool)hasHtExtended;
-(void)setHtTxBf:(unsigned)arg1 ;
-(void)setHasHtTxBf:(bool)arg1 ;
-(bool)hasHtTxBf;
-(void)setHtASel:(unsigned)arg1 ;
-(void)setHasHtASel:(bool)arg1 ;
-(bool)hasHtASel;
-(void)setHtAmpduParams:(unsigned)arg1 ;
-(void)setHasHtAmpduParams:(bool)arg1 ;
-(bool)hasHtAmpduParams;
-(bool)hasHtSupportedMcsSet;
-(void)setVhtInfo:(unsigned)arg1 ;
-(void)setHasVhtInfo:(bool)arg1 ;
-(bool)hasVhtInfo;
-(bool)hasVhtSupportedMcsSet;
-(bool)isLinkUp;
-(bool)isInVol;
-(unsigned)subreason;
-(unsigned)channelWidth;
-(unsigned)phyMode;
-(id)oui;
-(unsigned)securityType;
-(unsigned)wpaProtocol;
-(unsigned)mcastCipher;
-(unsigned)ucastCipher;
-(unsigned)akmSuites;
-(unsigned)htInfo;
-(unsigned)htExtended;
-(unsigned)htTxBf;
-(unsigned)htASel;
-(unsigned)htAmpduParams;
-(id)htSupportedMcsSet;
-(unsigned)vhtInfo;
-(id)vhtSupportedMcsSet;
@end

