/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDWiFiMetricIPv4DHCPLatency : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _dhcpLatencyMilliSecs;
	unsigned _dhcpLeaseMins;
	unsigned _securityType;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) bool hasDhcpLatencyMilliSecs; 
@property (assign,nonatomic) unsigned dhcpLatencyMilliSecs;              //@synthesize dhcpLatencyMilliSecs=_dhcpLatencyMilliSecs - In the implementation block
@property (assign,nonatomic) bool hasSecurityType; 
@property (assign,nonatomic) unsigned securityType;                      //@synthesize securityType=_securityType - In the implementation block
@property (assign,nonatomic) bool hasDhcpLeaseMins; 
@property (assign,nonatomic) unsigned dhcpLeaseMins;                     //@synthesize dhcpLeaseMins=_dhcpLeaseMins - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setSecurityType:(unsigned)arg1 ;
-(void)setHasSecurityType:(bool)arg1 ;
-(bool)hasSecurityType;
-(unsigned)securityType;
-(void)setDhcpLatencyMilliSecs:(unsigned)arg1 ;
-(void)setHasDhcpLatencyMilliSecs:(bool)arg1 ;
-(bool)hasDhcpLatencyMilliSecs;
-(void)setDhcpLeaseMins:(unsigned)arg1 ;
-(void)setHasDhcpLeaseMins:(bool)arg1 ;
-(bool)hasDhcpLeaseMins;
-(unsigned)dhcpLatencyMilliSecs;
-(unsigned)dhcpLeaseMins;
@end

