/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDWiFiMetricCustomNetworkSetting : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _autoProxySetCount;
	unsigned _bootpSetCount;
	unsigned _customNetworkCount;
	unsigned _dhcpSetCount;
	unsigned _manualProxySetCount;
	unsigned _staticSetCount;
	unsigned _totalNetworkCount;
	SCD_Struct_AW10 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasCustomNetworkCount; 
@property (assign,nonatomic) unsigned customNetworkCount;               //@synthesize customNetworkCount=_customNetworkCount - In the implementation block
@property (assign,nonatomic) bool hasTotalNetworkCount; 
@property (assign,nonatomic) unsigned totalNetworkCount;                //@synthesize totalNetworkCount=_totalNetworkCount - In the implementation block
@property (assign,nonatomic) bool hasDhcpSetCount; 
@property (assign,nonatomic) unsigned dhcpSetCount;                     //@synthesize dhcpSetCount=_dhcpSetCount - In the implementation block
@property (assign,nonatomic) bool hasBootpSetCount; 
@property (assign,nonatomic) unsigned bootpSetCount;                    //@synthesize bootpSetCount=_bootpSetCount - In the implementation block
@property (assign,nonatomic) bool hasStaticSetCount; 
@property (assign,nonatomic) unsigned staticSetCount;                   //@synthesize staticSetCount=_staticSetCount - In the implementation block
@property (assign,nonatomic) bool hasManualProxySetCount; 
@property (assign,nonatomic) unsigned manualProxySetCount;              //@synthesize manualProxySetCount=_manualProxySetCount - In the implementation block
@property (assign,nonatomic) bool hasAutoProxySetCount; 
@property (assign,nonatomic) unsigned autoProxySetCount;                //@synthesize autoProxySetCount=_autoProxySetCount - In the implementation block
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setCustomNetworkCount:(unsigned)arg1 ;
-(void)setHasCustomNetworkCount:(bool)arg1 ;
-(bool)hasCustomNetworkCount;
-(void)setTotalNetworkCount:(unsigned)arg1 ;
-(void)setHasTotalNetworkCount:(bool)arg1 ;
-(bool)hasTotalNetworkCount;
-(void)setDhcpSetCount:(unsigned)arg1 ;
-(void)setHasDhcpSetCount:(bool)arg1 ;
-(bool)hasDhcpSetCount;
-(void)setBootpSetCount:(unsigned)arg1 ;
-(void)setHasBootpSetCount:(bool)arg1 ;
-(bool)hasBootpSetCount;
-(void)setStaticSetCount:(unsigned)arg1 ;
-(void)setHasStaticSetCount:(bool)arg1 ;
-(bool)hasStaticSetCount;
-(void)setManualProxySetCount:(unsigned)arg1 ;
-(void)setHasManualProxySetCount:(bool)arg1 ;
-(bool)hasManualProxySetCount;
-(void)setAutoProxySetCount:(unsigned)arg1 ;
-(void)setHasAutoProxySetCount:(bool)arg1 ;
-(bool)hasAutoProxySetCount;
-(unsigned)customNetworkCount;
-(unsigned)totalNetworkCount;
-(unsigned)dhcpSetCount;
-(unsigned)bootpSetCount;
-(unsigned)staticSetCount;
-(unsigned)manualProxySetCount;
-(unsigned)autoProxySetCount;
@end

