/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDWiFiMetricInterfaceStats : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _a2dpAssocMinutes;
	unsigned _cellularDataRxBytes;
	unsigned _cellularDataTxBytes;
	unsigned _hidAssocMinutes;
	unsigned _scoAssocMinutes;
	unsigned _statsCollectionMinutes;
	unsigned _wifiA2dpRxBytes;
	unsigned _wifiA2dpTxBytes;
	unsigned _wifiAssocMinutes;
	unsigned _wifiHidRxBytes;
	unsigned _wifiHidTxBytes;
	unsigned _wifiRxBytes;
	unsigned _wifiScoRxBytes;
	unsigned _wifiScoTxBytes;
	unsigned _wifiTxBytes;
	SCD_Struct_AW8 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                 //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasWifiA2dpRxBytes; 
@property (assign,nonatomic) unsigned wifiA2dpRxBytes;                     //@synthesize wifiA2dpRxBytes=_wifiA2dpRxBytes - In the implementation block
@property (assign,nonatomic) bool hasWifiScoRxBytes; 
@property (assign,nonatomic) unsigned wifiScoRxBytes;                      //@synthesize wifiScoRxBytes=_wifiScoRxBytes - In the implementation block
@property (assign,nonatomic) bool hasWifiRxBytes; 
@property (assign,nonatomic) unsigned wifiRxBytes;                         //@synthesize wifiRxBytes=_wifiRxBytes - In the implementation block
@property (assign,nonatomic) bool hasWifiHidRxBytes; 
@property (assign,nonatomic) unsigned wifiHidRxBytes;                      //@synthesize wifiHidRxBytes=_wifiHidRxBytes - In the implementation block
@property (assign,nonatomic) bool hasCellularDataRxBytes; 
@property (assign,nonatomic) unsigned cellularDataRxBytes;                 //@synthesize cellularDataRxBytes=_cellularDataRxBytes - In the implementation block
@property (assign,nonatomic) bool hasWifiA2dpTxBytes; 
@property (assign,nonatomic) unsigned wifiA2dpTxBytes;                     //@synthesize wifiA2dpTxBytes=_wifiA2dpTxBytes - In the implementation block
@property (assign,nonatomic) bool hasWifiScoTxBytes; 
@property (assign,nonatomic) unsigned wifiScoTxBytes;                      //@synthesize wifiScoTxBytes=_wifiScoTxBytes - In the implementation block
@property (assign,nonatomic) bool hasWifiTxBytes; 
@property (assign,nonatomic) unsigned wifiTxBytes;                         //@synthesize wifiTxBytes=_wifiTxBytes - In the implementation block
@property (assign,nonatomic) bool hasWifiHidTxBytes; 
@property (assign,nonatomic) unsigned wifiHidTxBytes;                      //@synthesize wifiHidTxBytes=_wifiHidTxBytes - In the implementation block
@property (assign,nonatomic) bool hasCellularDataTxBytes; 
@property (assign,nonatomic) unsigned cellularDataTxBytes;                 //@synthesize cellularDataTxBytes=_cellularDataTxBytes - In the implementation block
@property (assign,nonatomic) bool hasStatsCollectionMinutes; 
@property (assign,nonatomic) unsigned statsCollectionMinutes;              //@synthesize statsCollectionMinutes=_statsCollectionMinutes - In the implementation block
@property (assign,nonatomic) bool hasWifiAssocMinutes; 
@property (assign,nonatomic) unsigned wifiAssocMinutes;                    //@synthesize wifiAssocMinutes=_wifiAssocMinutes - In the implementation block
@property (assign,nonatomic) bool hasA2dpAssocMinutes; 
@property (assign,nonatomic) unsigned a2dpAssocMinutes;                    //@synthesize a2dpAssocMinutes=_a2dpAssocMinutes - In the implementation block
@property (assign,nonatomic) bool hasScoAssocMinutes; 
@property (assign,nonatomic) unsigned scoAssocMinutes;                     //@synthesize scoAssocMinutes=_scoAssocMinutes - In the implementation block
@property (assign,nonatomic) bool hasHidAssocMinutes; 
@property (assign,nonatomic) unsigned hidAssocMinutes;                     //@synthesize hidAssocMinutes=_hidAssocMinutes - In the implementation block
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setWifiA2dpRxBytes:(unsigned)arg1 ;
-(void)setHasWifiA2dpRxBytes:(bool)arg1 ;
-(bool)hasWifiA2dpRxBytes;
-(void)setWifiScoRxBytes:(unsigned)arg1 ;
-(void)setHasWifiScoRxBytes:(bool)arg1 ;
-(bool)hasWifiScoRxBytes;
-(void)setWifiRxBytes:(unsigned)arg1 ;
-(void)setHasWifiRxBytes:(bool)arg1 ;
-(bool)hasWifiRxBytes;
-(void)setWifiHidRxBytes:(unsigned)arg1 ;
-(void)setHasWifiHidRxBytes:(bool)arg1 ;
-(bool)hasWifiHidRxBytes;
-(void)setCellularDataRxBytes:(unsigned)arg1 ;
-(void)setHasCellularDataRxBytes:(bool)arg1 ;
-(bool)hasCellularDataRxBytes;
-(void)setWifiA2dpTxBytes:(unsigned)arg1 ;
-(void)setHasWifiA2dpTxBytes:(bool)arg1 ;
-(bool)hasWifiA2dpTxBytes;
-(void)setWifiScoTxBytes:(unsigned)arg1 ;
-(void)setHasWifiScoTxBytes:(bool)arg1 ;
-(bool)hasWifiScoTxBytes;
-(void)setWifiTxBytes:(unsigned)arg1 ;
-(void)setHasWifiTxBytes:(bool)arg1 ;
-(bool)hasWifiTxBytes;
-(void)setWifiHidTxBytes:(unsigned)arg1 ;
-(void)setHasWifiHidTxBytes:(bool)arg1 ;
-(bool)hasWifiHidTxBytes;
-(void)setCellularDataTxBytes:(unsigned)arg1 ;
-(void)setHasCellularDataTxBytes:(bool)arg1 ;
-(bool)hasCellularDataTxBytes;
-(void)setStatsCollectionMinutes:(unsigned)arg1 ;
-(void)setHasStatsCollectionMinutes:(bool)arg1 ;
-(bool)hasStatsCollectionMinutes;
-(void)setWifiAssocMinutes:(unsigned)arg1 ;
-(void)setHasWifiAssocMinutes:(bool)arg1 ;
-(bool)hasWifiAssocMinutes;
-(void)setA2dpAssocMinutes:(unsigned)arg1 ;
-(void)setHasA2dpAssocMinutes:(bool)arg1 ;
-(bool)hasA2dpAssocMinutes;
-(void)setScoAssocMinutes:(unsigned)arg1 ;
-(void)setHasScoAssocMinutes:(bool)arg1 ;
-(bool)hasScoAssocMinutes;
-(void)setHidAssocMinutes:(unsigned)arg1 ;
-(void)setHasHidAssocMinutes:(bool)arg1 ;
-(bool)hasHidAssocMinutes;
-(unsigned)wifiA2dpRxBytes;
-(unsigned)wifiScoRxBytes;
-(unsigned)wifiRxBytes;
-(unsigned)wifiHidRxBytes;
-(unsigned)cellularDataRxBytes;
-(unsigned)wifiA2dpTxBytes;
-(unsigned)wifiScoTxBytes;
-(unsigned)wifiTxBytes;
-(unsigned)wifiHidTxBytes;
-(unsigned)cellularDataTxBytes;
-(unsigned)statsCollectionMinutes;
-(unsigned)wifiAssocMinutes;
-(unsigned)a2dpAssocMinutes;
-(unsigned)scoAssocMinutes;
-(unsigned)hidAssocMinutes;
@end

