/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDWiFiMetricsManagerPowerStatsUpdateEvent : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _associatedSleepDur;
	unsigned _roamDur;
	unsigned _totalDur;
	unsigned _type;
	unsigned _unassociatedSleepDur;
	SCD_Struct_AW7 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasType; 
@property (assign,nonatomic) unsigned type;                              //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) bool hasUnassociatedSleepDur; 
@property (assign,nonatomic) unsigned unassociatedSleepDur;              //@synthesize unassociatedSleepDur=_unassociatedSleepDur - In the implementation block
@property (assign,nonatomic) bool hasAssociatedSleepDur; 
@property (assign,nonatomic) unsigned associatedSleepDur;                //@synthesize associatedSleepDur=_associatedSleepDur - In the implementation block
@property (assign,nonatomic) bool hasRoamDur; 
@property (assign,nonatomic) unsigned roamDur;                           //@synthesize roamDur=_roamDur - In the implementation block
@property (assign,nonatomic) bool hasTotalDur; 
@property (assign,nonatomic) unsigned totalDur;                          //@synthesize totalDur=_totalDur - In the implementation block
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setType:(unsigned)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(unsigned)type;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(void)setHasType:(bool)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(bool)hasType;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setUnassociatedSleepDur:(unsigned)arg1 ;
-(void)setHasUnassociatedSleepDur:(bool)arg1 ;
-(bool)hasUnassociatedSleepDur;
-(void)setAssociatedSleepDur:(unsigned)arg1 ;
-(void)setHasAssociatedSleepDur:(bool)arg1 ;
-(bool)hasAssociatedSleepDur;
-(void)setRoamDur:(unsigned)arg1 ;
-(void)setHasRoamDur:(bool)arg1 ;
-(bool)hasRoamDur;
-(void)setTotalDur:(unsigned)arg1 ;
-(void)setHasTotalDur:(bool)arg1 ;
-(bool)hasTotalDur;
-(unsigned)unassociatedSleepDur;
-(unsigned)associatedSleepDur;
-(unsigned)roamDur;
-(unsigned)totalDur;
@end

