/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDWiFiMetricsManagerDeviceCount : PBCodable <NSCopying> {

	double _timeSinceBoot;
	unsigned long long _timestamp;
	unsigned _deviceCount;
	unsigned _deviceIdentifierMap;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasDeviceCount; 
@property (assign,nonatomic) unsigned deviceCount;                      //@synthesize deviceCount=_deviceCount - In the implementation block
@property (assign,nonatomic) bool hasTimeSinceBoot; 
@property (assign,nonatomic) double timeSinceBoot;                      //@synthesize timeSinceBoot=_timeSinceBoot - In the implementation block
@property (assign,nonatomic) bool hasDeviceIdentifierMap; 
@property (assign,nonatomic) unsigned deviceIdentifierMap;              //@synthesize deviceIdentifierMap=_deviceIdentifierMap - In the implementation block
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setDeviceCount:(unsigned)arg1 ;
-(void)setHasDeviceCount:(bool)arg1 ;
-(bool)hasDeviceCount;
-(void)setTimeSinceBoot:(double)arg1 ;
-(void)setHasTimeSinceBoot:(bool)arg1 ;
-(bool)hasTimeSinceBoot;
-(void)setDeviceIdentifierMap:(unsigned)arg1 ;
-(void)setHasDeviceIdentifierMap:(bool)arg1 ;
-(bool)hasDeviceIdentifierMap;
-(unsigned)deviceCount;
-(double)timeSinceBoot;
-(unsigned)deviceIdentifierMap;
@end

