/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSData;

@interface AWDWifiMostUsedNetworks : PBCodable <NSCopying> {

	double _timeUsed;
	unsigned _apOUI;
	NSData* _apOui;
	unsigned _securityType;
	unsigned _timeUsedMinutes;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) bool hasApOUI; 
@property (assign,nonatomic) unsigned apOUI;                        //@synthesize apOUI=_apOUI - In the implementation block
@property (assign,nonatomic) bool hasSecurityType; 
@property (assign,nonatomic) unsigned securityType;                 //@synthesize securityType=_securityType - In the implementation block
@property (assign,nonatomic) bool hasTimeUsed; 
@property (assign,nonatomic) double timeUsed;                       //@synthesize timeUsed=_timeUsed - In the implementation block
@property (nonatomic,readonly) bool hasApOui; 
@property (nonatomic,retain) NSData * apOui;                        //@synthesize apOui=_apOui - In the implementation block
@property (assign,nonatomic) bool hasTimeUsedMinutes; 
@property (assign,nonatomic) unsigned timeUsedMinutes;              //@synthesize timeUsedMinutes=_timeUsedMinutes - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setSecurityType:(unsigned)arg1 ;
-(void)setHasSecurityType:(bool)arg1 ;
-(bool)hasSecurityType;
-(unsigned)securityType;
-(void)setApOui:(id)arg1 ;
-(void)setApOUI:(unsigned)arg1 ;
-(void)setHasApOUI:(bool)arg1 ;
-(bool)hasApOUI;
-(void)setTimeUsed:(double)arg1 ;
-(void)setHasTimeUsed:(bool)arg1 ;
-(bool)hasTimeUsed;
-(bool)hasApOui;
-(void)setTimeUsedMinutes:(unsigned)arg1 ;
-(void)setHasTimeUsedMinutes:(bool)arg1 ;
-(bool)hasTimeUsedMinutes;
-(unsigned)apOUI;
-(double)timeUsed;
-(id)apOui;
-(unsigned)timeUsedMinutes;
@end

