/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@interface AWDWiFiMetricsManagerWifidAvailability : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	double _wifidBootTimeDiff;
	unsigned _pid;
	SCD_Struct_AW11 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasWifidBootTimeDiff; 
@property (assign,nonatomic) double wifidBootTimeDiff;                  //@synthesize wifidBootTimeDiff=_wifidBootTimeDiff - In the implementation block
@property (assign,nonatomic) bool hasPid; 
@property (assign,nonatomic) unsigned pid;                              //@synthesize pid=_pid - In the implementation block
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned)pid;
-(void)setPid:(unsigned)arg1 ;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setWifidBootTimeDiff:(double)arg1 ;
-(void)setHasWifidBootTimeDiff:(bool)arg1 ;
-(bool)hasWifidBootTimeDiff;
-(void)setHasPid:(bool)arg1 ;
-(bool)hasPid;
-(double)wifidBootTimeDiff;
@end

