/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufWifi.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufWifi.dylib/libAWDProtobufWifi.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSMutableArray;

@interface AWDWiFiMetricNetworkPrefs : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _adhocNetsCount;
	unsigned _applePersHotspotNetsCount;
	unsigned _atjCanceledCount;
	unsigned _atjUsedCount;
	unsigned _captiveNetsCount;
	unsigned _eapNetsCount;
	unsigned _hiddenNetsCount;
	unsigned _mostUsedCount;
	NSMutableArray* _mostUsedNetworks;
	unsigned _openNonCaptiveNetsCount;
	unsigned _prefNetsCount;
	unsigned _wapiNetsCount;
	unsigned _wepNetsCount;
	unsigned _wpaNetsCount;
	bool _atjEnabled;
	SCD_Struct_AW1 _has;

}

@property (assign,nonatomic) bool hasAtjEnabled; 
@property (assign,nonatomic) bool atjEnabled;                                 //@synthesize atjEnabled=_atjEnabled - In the implementation block
@property (assign,nonatomic) bool hasAtjCanceledCount; 
@property (assign,nonatomic) unsigned atjCanceledCount;                       //@synthesize atjCanceledCount=_atjCanceledCount - In the implementation block
@property (assign,nonatomic) bool hasAtjUsedCount; 
@property (assign,nonatomic) unsigned atjUsedCount;                           //@synthesize atjUsedCount=_atjUsedCount - In the implementation block
@property (assign,nonatomic) bool hasAdhocNetsCount; 
@property (assign,nonatomic) unsigned adhocNetsCount;                         //@synthesize adhocNetsCount=_adhocNetsCount - In the implementation block
@property (assign,nonatomic) bool hasPrefNetsCount; 
@property (assign,nonatomic) unsigned prefNetsCount;                          //@synthesize prefNetsCount=_prefNetsCount - In the implementation block
@property (assign,nonatomic) bool hasCaptiveNetsCount; 
@property (assign,nonatomic) unsigned captiveNetsCount;                       //@synthesize captiveNetsCount=_captiveNetsCount - In the implementation block
@property (assign,nonatomic) bool hasApplePersHotspotNetsCount; 
@property (assign,nonatomic) unsigned applePersHotspotNetsCount;              //@synthesize applePersHotspotNetsCount=_applePersHotspotNetsCount - In the implementation block
@property (assign,nonatomic) bool hasWapiNetsCount; 
@property (assign,nonatomic) unsigned wapiNetsCount;                          //@synthesize wapiNetsCount=_wapiNetsCount - In the implementation block
@property (assign,nonatomic) bool hasMostUsedCount; 
@property (assign,nonatomic) unsigned mostUsedCount;                          //@synthesize mostUsedCount=_mostUsedCount - In the implementation block
@property (nonatomic,retain) NSMutableArray * mostUsedNetworks;               //@synthesize mostUsedNetworks=_mostUsedNetworks - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                    //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasHiddenNetsCount; 
@property (assign,nonatomic) unsigned hiddenNetsCount;                        //@synthesize hiddenNetsCount=_hiddenNetsCount - In the implementation block
@property (assign,nonatomic) bool hasWepNetsCount; 
@property (assign,nonatomic) unsigned wepNetsCount;                           //@synthesize wepNetsCount=_wepNetsCount - In the implementation block
@property (assign,nonatomic) bool hasWpaNetsCount; 
@property (assign,nonatomic) unsigned wpaNetsCount;                           //@synthesize wpaNetsCount=_wpaNetsCount - In the implementation block
@property (assign,nonatomic) bool hasEapNetsCount; 
@property (assign,nonatomic) unsigned eapNetsCount;                           //@synthesize eapNetsCount=_eapNetsCount - In the implementation block
@property (assign,nonatomic) bool hasOpenNonCaptiveNetsCount; 
@property (assign,nonatomic) unsigned openNonCaptiveNetsCount;                //@synthesize openNonCaptiveNetsCount=_openNonCaptiveNetsCount - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setMostUsedNetworks:(id)arg1 ;
-(void)addMostUsedNetworks:(id)arg1 ;
-(unsigned long long)mostUsedNetworksCount;
-(void)clearMostUsedNetworks;
-(id)mostUsedNetworksAtIndex:(unsigned long long)arg1 ;
-(void)setAtjEnabled:(bool)arg1 ;
-(void)setHasAtjEnabled:(bool)arg1 ;
-(bool)hasAtjEnabled;
-(void)setAtjCanceledCount:(unsigned)arg1 ;
-(void)setHasAtjCanceledCount:(bool)arg1 ;
-(bool)hasAtjCanceledCount;
-(void)setAtjUsedCount:(unsigned)arg1 ;
-(void)setHasAtjUsedCount:(bool)arg1 ;
-(bool)hasAtjUsedCount;
-(void)setAdhocNetsCount:(unsigned)arg1 ;
-(void)setHasAdhocNetsCount:(bool)arg1 ;
-(bool)hasAdhocNetsCount;
-(void)setPrefNetsCount:(unsigned)arg1 ;
-(void)setHasPrefNetsCount:(bool)arg1 ;
-(bool)hasPrefNetsCount;
-(void)setCaptiveNetsCount:(unsigned)arg1 ;
-(void)setHasCaptiveNetsCount:(bool)arg1 ;
-(bool)hasCaptiveNetsCount;
-(void)setApplePersHotspotNetsCount:(unsigned)arg1 ;
-(void)setHasApplePersHotspotNetsCount:(bool)arg1 ;
-(bool)hasApplePersHotspotNetsCount;
-(void)setWapiNetsCount:(unsigned)arg1 ;
-(void)setHasWapiNetsCount:(bool)arg1 ;
-(bool)hasWapiNetsCount;
-(void)setMostUsedCount:(unsigned)arg1 ;
-(void)setHasMostUsedCount:(bool)arg1 ;
-(bool)hasMostUsedCount;
-(void)setHiddenNetsCount:(unsigned)arg1 ;
-(void)setHasHiddenNetsCount:(bool)arg1 ;
-(bool)hasHiddenNetsCount;
-(void)setWepNetsCount:(unsigned)arg1 ;
-(void)setHasWepNetsCount:(bool)arg1 ;
-(bool)hasWepNetsCount;
-(void)setWpaNetsCount:(unsigned)arg1 ;
-(void)setHasWpaNetsCount:(bool)arg1 ;
-(bool)hasWpaNetsCount;
-(void)setEapNetsCount:(unsigned)arg1 ;
-(void)setHasEapNetsCount:(bool)arg1 ;
-(bool)hasEapNetsCount;
-(void)setOpenNonCaptiveNetsCount:(unsigned)arg1 ;
-(void)setHasOpenNonCaptiveNetsCount:(bool)arg1 ;
-(bool)hasOpenNonCaptiveNetsCount;
-(bool)atjEnabled;
-(unsigned)atjCanceledCount;
-(unsigned)atjUsedCount;
-(unsigned)adhocNetsCount;
-(unsigned)prefNetsCount;
-(unsigned)captiveNetsCount;
-(unsigned)applePersHotspotNetsCount;
-(unsigned)wapiNetsCount;
-(unsigned)mostUsedCount;
-(id)mostUsedNetworks;
-(unsigned)hiddenNetsCount;
-(unsigned)wepNetsCount;
-(unsigned)wpaNetsCount;
-(unsigned)eapNetsCount;
-(unsigned)openNonCaptiveNetsCount;
@end

