/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:43 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufFacetimeiMessage.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufFacetimeiMessage.dylib/libAWDProtobufFacetimeiMessage.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDFaceTimeCallInterruptionBegan : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	NSString* _guid;
	unsigned _isAudioInterrupted;
	unsigned _isVideo;
	unsigned _isVideoInterrupted;
	int _linkQuality;
	SCD_Struct_AW2 _has;

}

@property (nonatomic,readonly) bool hasGuid; 
@property (nonatomic,retain) NSString * guid;                           //@synthesize guid=_guid - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasIsVideoInterrupted; 
@property (assign,nonatomic) unsigned isVideoInterrupted;               //@synthesize isVideoInterrupted=_isVideoInterrupted - In the implementation block
@property (assign,nonatomic) bool hasIsAudioInterrupted; 
@property (assign,nonatomic) unsigned isAudioInterrupted;               //@synthesize isAudioInterrupted=_isAudioInterrupted - In the implementation block
@property (assign,nonatomic) bool hasLinkQuality; 
@property (assign,nonatomic) int linkQuality;                           //@synthesize linkQuality=_linkQuality - In the implementation block
@property (assign,nonatomic) bool hasIsVideo; 
@property (assign,nonatomic) unsigned isVideo;                          //@synthesize isVideo=_isVideo - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned)isVideo;
-(id)guid;
-(bool)readFrom:(id)arg1 ;
-(void)setIsVideo:(unsigned)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setGuid:(id)arg1 ;
-(bool)hasGuid;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setHasIsVideo:(bool)arg1 ;
-(bool)hasIsVideo;
-(void)setIsVideoInterrupted:(unsigned)arg1 ;
-(void)setHasIsVideoInterrupted:(bool)arg1 ;
-(bool)hasIsVideoInterrupted;
-(void)setIsAudioInterrupted:(unsigned)arg1 ;
-(void)setHasIsAudioInterrupted:(bool)arg1 ;
-(bool)hasIsAudioInterrupted;
-(void)setLinkQuality:(int)arg1 ;
-(void)setHasLinkQuality:(bool)arg1 ;
-(bool)hasLinkQuality;
-(unsigned)isVideoInterrupted;
-(unsigned)isAudioInterrupted;
-(int)linkQuality;
@end

