/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufFacetimeiMessage.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufFacetimeiMessage.dylib/libAWDProtobufFacetimeiMessage.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDIMessageDowngrade : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _durationBeforeDowngrade;
	NSString* _guid;
	unsigned _isManualDowngrade;
	SCD_Struct_AW8 _has;

}

@property (nonatomic,readonly) bool hasGuid; 
@property (nonatomic,retain) NSString * guid;                               //@synthesize guid=_guid - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                  //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasDurationBeforeDowngrade; 
@property (assign,nonatomic) unsigned durationBeforeDowngrade;              //@synthesize durationBeforeDowngrade=_durationBeforeDowngrade - In the implementation block
@property (assign,nonatomic) bool hasIsManualDowngrade; 
@property (assign,nonatomic) unsigned isManualDowngrade;                    //@synthesize isManualDowngrade=_isManualDowngrade - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(id)guid;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setGuid:(id)arg1 ;
-(bool)hasGuid;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setDurationBeforeDowngrade:(unsigned)arg1 ;
-(void)setHasDurationBeforeDowngrade:(bool)arg1 ;
-(bool)hasDurationBeforeDowngrade;
-(void)setIsManualDowngrade:(unsigned)arg1 ;
-(void)setHasIsManualDowngrade:(bool)arg1 ;
-(bool)hasIsManualDowngrade;
-(unsigned)durationBeforeDowngrade;
-(unsigned)isManualDowngrade;
@end

