/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufFacetimeiMessage.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufFacetimeiMessage.dylib/libAWDProtobufFacetimeiMessage.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDIMessageQueryFinished : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _connectionType;
	int _genericError;
	NSString* _guid;
	unsigned _isEmail;
	unsigned _isPhoneNumber;
	int _pOSIXError;
	unsigned _queryDuration;
	int _resultCode;
	unsigned _success;
	int _uRLError;
	SCD_Struct_AW3 _has;

}

@property (nonatomic,readonly) bool hasGuid; 
@property (nonatomic,retain) NSString * guid;                           //@synthesize guid=_guid - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasSuccess; 
@property (assign,nonatomic) unsigned success;                          //@synthesize success=_success - In the implementation block
@property (assign,nonatomic) bool hasConnectionType; 
@property (assign,nonatomic) unsigned connectionType;                   //@synthesize connectionType=_connectionType - In the implementation block
@property (assign,nonatomic) bool hasQueryDuration; 
@property (assign,nonatomic) unsigned queryDuration;                    //@synthesize queryDuration=_queryDuration - In the implementation block
@property (assign,nonatomic) bool hasIsPhoneNumber; 
@property (assign,nonatomic) unsigned isPhoneNumber;                    //@synthesize isPhoneNumber=_isPhoneNumber - In the implementation block
@property (assign,nonatomic) bool hasIsEmail; 
@property (assign,nonatomic) unsigned isEmail;                          //@synthesize isEmail=_isEmail - In the implementation block
@property (assign,nonatomic) bool hasResultCode; 
@property (assign,nonatomic) int resultCode;                            //@synthesize resultCode=_resultCode - In the implementation block
@property (assign,nonatomic) bool hasGenericError; 
@property (assign,nonatomic) int genericError;                          //@synthesize genericError=_genericError - In the implementation block
@property (assign,nonatomic) bool hasURLError; 
@property (assign,nonatomic) int uRLError;                              //@synthesize uRLError=_uRLError - In the implementation block
@property (assign,nonatomic) bool hasPOSIXError; 
@property (assign,nonatomic) int pOSIXError;                            //@synthesize pOSIXError=_pOSIXError - In the implementation block
-(unsigned)success;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned)connectionType;
-(void)setConnectionType:(unsigned)arg1 ;
-(id)guid;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setSuccess:(unsigned)arg1 ;
-(void)setGuid:(id)arg1 ;
-(bool)hasGuid;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setHasConnectionType:(bool)arg1 ;
-(bool)hasConnectionType;
-(void)setGenericError:(int)arg1 ;
-(void)setHasGenericError:(bool)arg1 ;
-(bool)hasGenericError;
-(int)genericError;
-(void)setHasSuccess:(bool)arg1 ;
-(bool)hasSuccess;
-(void)setQueryDuration:(unsigned)arg1 ;
-(void)setHasQueryDuration:(bool)arg1 ;
-(bool)hasQueryDuration;
-(void)setIsPhoneNumber:(unsigned)arg1 ;
-(void)setHasIsPhoneNumber:(bool)arg1 ;
-(bool)hasIsPhoneNumber;
-(void)setIsEmail:(unsigned)arg1 ;
-(void)setHasIsEmail:(bool)arg1 ;
-(bool)hasIsEmail;
-(void)setResultCode:(int)arg1 ;
-(void)setHasResultCode:(bool)arg1 ;
-(bool)hasResultCode;
-(void)setURLError:(int)arg1 ;
-(void)setHasURLError:(bool)arg1 ;
-(bool)hasURLError;
-(void)setPOSIXError:(int)arg1 ;
-(void)setHasPOSIXError:(bool)arg1 ;
-(bool)hasPOSIXError;
-(unsigned)queryDuration;
-(unsigned)isPhoneNumber;
-(unsigned)isEmail;
-(int)resultCode;
-(int)uRLError;
-(int)pOSIXError;
@end

