/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufFacetimeiMessage.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufFacetimeiMessage.dylib/libAWDProtobufFacetimeiMessage.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDIMessageAttachmentDownload : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _attachmentSize;
	unsigned _connectionType;
	unsigned _downloadDuration;
	int _fzError;
	int _genericError;
	NSString* _guid;
	int _linkQuality;
	unsigned _messageError;
	unsigned _tokenError;
	SCD_Struct_AW7 _has;

}

@property (nonatomic,readonly) bool hasGuid; 
@property (nonatomic,retain) NSString * guid;                           //@synthesize guid=_guid - In the implementation block
@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasFzError; 
@property (assign,nonatomic) int fzError;                               //@synthesize fzError=_fzError - In the implementation block
@property (assign,nonatomic) bool hasMessageError; 
@property (assign,nonatomic) unsigned messageError;                     //@synthesize messageError=_messageError - In the implementation block
@property (assign,nonatomic) bool hasTokenError; 
@property (assign,nonatomic) unsigned tokenError;                       //@synthesize tokenError=_tokenError - In the implementation block
@property (assign,nonatomic) bool hasGenericError; 
@property (assign,nonatomic) int genericError;                          //@synthesize genericError=_genericError - In the implementation block
@property (assign,nonatomic) bool hasDownloadDuration; 
@property (assign,nonatomic) unsigned downloadDuration;                 //@synthesize downloadDuration=_downloadDuration - In the implementation block
@property (assign,nonatomic) bool hasLinkQuality; 
@property (assign,nonatomic) int linkQuality;                           //@synthesize linkQuality=_linkQuality - In the implementation block
@property (assign,nonatomic) bool hasConnectionType; 
@property (assign,nonatomic) unsigned connectionType;                   //@synthesize connectionType=_connectionType - In the implementation block
@property (assign,nonatomic) bool hasAttachmentSize; 
@property (assign,nonatomic) unsigned attachmentSize;                   //@synthesize attachmentSize=_attachmentSize - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned)connectionType;
-(void)setConnectionType:(unsigned)arg1 ;
-(id)guid;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setGuid:(id)arg1 ;
-(bool)hasGuid;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setHasConnectionType:(bool)arg1 ;
-(bool)hasConnectionType;
-(void)setGenericError:(int)arg1 ;
-(void)setHasGenericError:(bool)arg1 ;
-(bool)hasGenericError;
-(void)setLinkQuality:(int)arg1 ;
-(void)setHasLinkQuality:(bool)arg1 ;
-(bool)hasLinkQuality;
-(int)genericError;
-(int)linkQuality;
-(void)setFzError:(int)arg1 ;
-(void)setHasFzError:(bool)arg1 ;
-(bool)hasFzError;
-(void)setMessageError:(unsigned)arg1 ;
-(void)setHasMessageError:(bool)arg1 ;
-(bool)hasMessageError;
-(void)setTokenError:(unsigned)arg1 ;
-(void)setHasTokenError:(bool)arg1 ;
-(bool)hasTokenError;
-(void)setDownloadDuration:(unsigned)arg1 ;
-(void)setHasDownloadDuration:(bool)arg1 ;
-(bool)hasDownloadDuration;
-(void)setAttachmentSize:(unsigned)arg1 ;
-(void)setHasAttachmentSize:(bool)arg1 ;
-(bool)hasAttachmentSize;
-(int)fzError;
-(unsigned)messageError;
-(unsigned)tokenError;
-(unsigned)downloadDuration;
-(unsigned)attachmentSize;
@end

