/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:47 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACFHTTPMethodInvocationDelegate.h>

@protocol ACFHTTPMethodInvocationAuthenticationHandler;
@class NSError, NSData;

@interface ACFHTTPMethodSynchronousInvocationHelper : NSObject <ACFHTTPMethodInvocationDelegate> {

	<ACFHTTPMethodInvocationAuthenticationHandler>* _authenticationHandler;
	NSError* _error;
	NSData* _result;

}

@property (assign) <ACFHTTPMethodInvocationAuthenticationHandler> * authenticationHandler;              //@synthesize authenticationHandler=_authenticationHandler - In the implementation block
@property (retain) NSError * error;                                                                     //@synthesize error=_error - In the implementation block
@property (retain) NSData * result;                                                                     //@synthesize result=_result - In the implementation block
-(void)setError:(id)arg1 ;
-(void)dealloc;
-(void)setResult:(id)arg1 ;
-(id)result;
-(id)error;
-(void)finalize;
-(void)httpMethodInvocation:(id)arg1 didFinishWithResult:(id)arg2 ;
-(void)httpMethodInvocation:(id)arg1 didFailWithError:(id)arg2 ;
-(id)httpMethodInvocation:(id)arg1 credentialForProtectionSpace:(id)arg2 ;
-(void)setAuthenticationHandler:(id)arg1 ;
-(id)authenticationHandler;
@end

