/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:47 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACFRunLoopScheduling.h>

@class ACFHTTPMethod, NSURL, ACFHTTPMethodInvocationInternal;

@interface ACFHTTPMethodInvocation : NSObject <ACFRunLoopScheduling> {

	ACFHTTPMethod* _method;
	NSURL* _url;
	double _timeout;
	id _delegate;
	id _internal;
	bool _isWaitingForResponse;

}

@property (assign) <ACFHTTPMethodInvocationDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) ACFHTTPMethod * method;                                  //@synthesize method=_method - In the implementation block
@property (readonly) NSURL * url;                                             //@synthesize url=_url - In the implementation block
@property (readonly) double timeout;                                          //@synthesize timeout=_timeout - In the implementation block
@property (assign) bool isWaitingForResponse;                                 //@synthesize isWaitingForResponse=_isWaitingForResponse - In the implementation block
@property (readonly) ACFHTTPMethodInvocationInternal * internal;              //@synthesize internal=_internal - In the implementation block
+(id)invokeHTTPMethodSynchronously:(id)arg1 withURL:(id)arg2 authenticationHandler:(id)arg3 timeout:(double)arg4 result:(id*)arg5 ;
+(id)invocation;
+(id)invocationWithMethod:(id)arg1 url:(id)arg2 timeout:(double)arg3 delegate:(id)arg4 invokeImmediately:(bool)arg5 ;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(bool)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 ;
-(void)scheduleInRunLoop:(id)arg1 forMode:(id)arg2 ;
-(void)unscheduleFromRunLoop:(id)arg1 forMode:(id)arg2 ;
-(double)timeout;
-(id)internal;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(id)delegate;
-(void)invoke;
-(void)cancel;
-(id)url;
-(id)method;
-(void)finalize;
-(bool)isWaitingForResponse;
-(id)initWithMethod:(id)arg1 url:(id)arg2 timeout:(double)arg3 delegate:(id)arg4 invokeImmediately:(bool)arg5 ;
-(void)setIsWaitingForResponse:(bool)arg1 ;
@end

