/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMFactoryProtocol.h>

@class ACMAppleConnect, ACMKeychainManager, ACMSettings, ACMProvisionManager, ACMSystemInfo, ACMMobileCryptograph, NSError, NSMutableSet;

@interface ACMAppleConnectPrivate : NSObject <ACMFactoryProtocol> {

	ACMAppleConnect* _masterObject;
	id _delegate;
	ACMKeychainManager* _keychain;
	ACMSettings* _settings;
	ACMProvisionManager* _provisionManager;
	ACMSystemInfo* _systemInfo;
	ACMMobileCryptograph* _cryptograph;
	NSError* _memoryError;
	NSMutableSet* _handlers;

}

@property (assign) id delegate;                                 //@synthesize delegate=_delegate - In the implementation block
@property (assign) ACMAppleConnect * masterObject;              //@synthesize masterObject=_masterObject - In the implementation block
@property (assign) int logLevel; 
@property (readonly) NSMutableSet * handlers; 
+(id)sharedInstance;
-(int)logLevel;
-(void)setLogLevel:(int)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(id)settings;
-(void)cancelRequests;
-(void)removeHandler:(id)arg1 ;
-(id)handlers;
-(id)authenticationRequest;
-(void)authenticateWithRequest:(id)arg1 password:(id)arg2 ;
-(void)setMasterObject:(id)arg1 ;
-(bool)shouldReleaseOnMemoryWarning;
-(id)initWithMasterObject:(id)arg1 ;
-(void)authenticate:(id)arg1 ;
-(id)hideAppleConnectSignInDialog;
-(void)verifyServiceTicket:(id)arg1 ;
-(id)systemInfo;
-(id)masterObject;
-(id)provisionManager;
-(id)createSSOTokenWithTGT:(id)arg1 keyHMAC:(id)arg2 keyCode:(id)arg3 initialToken:(id)arg4 ;
-(void)launchHandler:(id)arg1 ;
-(Class)settingsClass;
-(Class)provisionManagerClass;
-(void)authenticateRunningOnMainThreadWithRequest:(id)arg1 ;
-(void)removeAllHandlers;
-(Class)keychainClass;
-(id)keychain;
-(id)cryptograph;
-(id)memoryError;
-(id)ticketVerificationRequest;
@end

