/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ACMBaseAuthenticationRequest <NSObject>
@property (retain) NSString * realm; 
@property (retain) NSString * userName; 
@property (retain) NSNumber * appID; 
@property (retain) NSString * appIDKey; 
@property (retain) NSNumber * serverResponseTimeout; 
@required
-(id)userName;
-(id)realm;
-(void)setAppID:(id)arg1;
-(void)setRealm:(id)arg1;
-(void)setUserName:(id)arg1;
-(void)setAppIDKey:(id)arg1;
-(id)appID;
-(id)appIDKey;
-(id)serverResponseTimeout;
-(void)setServerResponseTimeout:(id)arg1;
@end

