/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:48 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary;

@interface ACMBaseLocale : NSObject {

	NSDictionary* _localeStrings;
	ACMBaseLocale* _nextLocale;

}

@property (retain) ACMBaseLocale * nextLocale;              //@synthesize nextLocale=_nextLocale - In the implementation block
+(id)sharedInstance;
+(id)currentLanguageCode;
+(id)localizedString:(id)arg1 ;
+(void)initResources;
+(id)localeForIdentifier:(id)arg1 ;
+(id)localeForLanguage:(id)arg1 ;
-(void)dealloc;
-(id)objectForKey:(id)arg1 ;
-(void)setNextLocale:(id)arg1 ;
-(id)nextLocale;
@end

