/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class NSString;

@interface ACMDialog : UIViewController {

	long long _savedStatusBarStyle;

}

@property (readonly) long long statusBarStyle; 
@property (assign) long long savedStatusBarStyle;                 //@synthesize savedStatusBarStyle=_savedStatusBarStyle - In the implementation block
@property (readonly) NSString * backgroundImageName; 
+(id)dialog;
+(void)setDialogOnFlight:(bool)arg1 ;
+(bool)dialogOnFlight;
-(void)applicationWillEnterForeground;
-(void)applicationDidEnterBackground;
-(void)dealloc;
-(id)init;
-(long long)statusBarStyle;
-(void)loadView;
-(void)viewWillAppear:(bool)arg1 ;
-(void)viewDidAppear:(bool)arg1 ;
-(void)viewWillDisappear:(bool)arg1 ;
-(void)viewDidDisappear:(bool)arg1 ;
-(id)backgroundImageName;
-(void)applicationDidBecomeActive;
-(void)applicationWillResignActive;
-(void)disableControls:(bool)arg1 ;
-(void)showWithOptions:(id)arg1 ;
-(void)hideWithOptions:(id)arg1 ;
-(void)setSavedStatusBarStyle:(long long)arg1 ;
-(long long)savedStatusBarStyle;
-(void)showWithParentViewController:(id)arg1 animated:(bool)arg2 ;
-(void)hideWithParentViewController:(id)arg1 animated:(bool)arg2 ;
@end

