/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/libacmobileshim.dylib-Structs.h>
#import <libacmobileshim.dylib/ACMExternalAppleConnectDelegate.h>

@interface ACMDelegate : NSObject <ACMExternalAppleConnectDelegate> {

	unsigned char _finished;
	/*^block*/ id copyTicketCompletion;

}

@property (assign) unsigned char finished;              //@synthesize finished=_finished - In the implementation block
@property (copy) id copyTicketCompletion; 
-(unsigned char)finished;
-(id)init;
-(void)setFinished:(unsigned char)arg1 ;
-(void)setCopyTicketCompletion:(/*^block*/ id)arg1 ;
-(/*^block*/ id)copyTicketCompletion;
-(void)appleConnect:(id)arg1 authenticationDidEndWithResponse:(id)arg2 ;
-(id)appleConnectParentViewController:(id)arg1 ;
@end

