/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ACMExternalAuthenticationRequest <ACMBaseAuthenticationRequest>
@property (assign) bool useAlertView; 
@property (assign) bool userNameFieldEditable; 
@property (retain) NSString * alertViewPrompt; 
@property (assign) bool automaticallyCancelWhenSwitchingToBackground; 
@required
-(bool)useAlertView;
-(bool)automaticallyCancelWhenSwitchingToBackground;
-(void)setUserNameFieldEditable:(bool)arg1;
-(void)setAlertViewPrompt:(id)arg1;
-(void)setUseAlertView:(bool)arg1;
-(bool)userNameFieldEditable;
-(id)alertViewPrompt;
-(void)setAutomaticallyCancelWhenSwitchingToBackground:(bool)arg1;
@end

