/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/libacmobileshim.dylib-Structs.h>
#import <libacmobileshim.dylib/ACMSettings.h>

@interface ACMExternalSettings : ACMSettings
-(id)authenticateURLStringForRealm:(id)arg1 ;
-(id)verifyTicketURLStringForRealm:(id)arg1 ;
-(id)realmServersMap;
-(CFStringRef)preferenceID;
-(id)defaultPublicKeyStringForRealm:(id)arg1 ;
@end

