/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMBaseAuthenticationRequestImpl.h>
#import <libacmobileshim.dylib/ACMExternalAuthenticationRequest.h>

@class NSString, NSNumber;

@interface ACMExternalAuthenticationRequestImpl : ACMBaseAuthenticationRequestImpl <ACMExternalAuthenticationRequest> {

	bool _useAlertView;
	bool _userNameFieldEditable;
	NSString* _alertViewPrompt;
	bool _automaticallyCancelWhenSwitchingToBackground;
	NSNumber* serverResponseTimeout;

}

@property (@dynamic,retain) NSString * realm; 
@property (@dynamic,retain) NSString * userName; 
@property (@dynamic,retain) NSNumber * appID; 
@property (@dynamic,retain) NSString * appIDKey; 
@property (retain) NSNumber * serverResponseTimeout; 
@property (assign) bool useAlertView;                                              //@synthesize useAlertView=_useAlertView - In the implementation block
@property (assign) bool userNameFieldEditable;                                     //@synthesize userNameFieldEditable=_userNameFieldEditable - In the implementation block
@property (retain) NSString * alertViewPrompt;                                     //@synthesize alertViewPrompt=_alertViewPrompt - In the implementation block
@property (assign) bool automaticallyCancelWhenSwitchingToBackground;              //@synthesize automaticallyCancelWhenSwitchingToBackground=_automaticallyCancelWhenSwitchingToBackground - In the implementation block
-(void)dealloc;
-(id)init;
-(bool)useAlertView;
-(id)serverResponseTimeout;
-(bool)automaticallyCancelWhenSwitchingToBackground;
-(void)setUserNameFieldEditable:(bool)arg1 ;
-(void)setAlertViewPrompt:(id)arg1 ;
-(void)setUseAlertView:(bool)arg1 ;
-(bool)userNameFieldEditable;
-(id)alertViewPrompt;
-(void)setAutomaticallyCancelWhenSwitchingToBackground:(bool)arg1 ;
-(void)setServerResponseTimeout:(id)arg1 ;
@end

