/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMHTTPHandler.h>

@class ACMInitialToken, NSString, NSDate;

@interface ACMHTTPAuthenticationHandler : ACMHTTPHandler {

	ACMInitialToken* _token;
	NSString* _policyVersion;
	id _request;
	long long _tryCounter;
	NSDate* _startInvocationDate;

}

@property (nonatomic,retain) ACMInitialToken * token;                   //@synthesize token=_token - In the implementation block
@property (nonatomic,retain) NSString * policyVersion;                  //@synthesize policyVersion=_policyVersion - In the implementation block
@property (nonatomic,retain) id request;                                //@synthesize request=_request - In the implementation block
@property (nonatomic,readonly) NSString * realm; 
@property (assign,nonatomic) long long tryCounter;                      //@synthesize tryCounter=_tryCounter - In the implementation block
@property (nonatomic,retain) NSDate * startInvocationDate;              //@synthesize startInvocationDate=_startInvocationDate - In the implementation block
+(id)handlerWithRequest:(id)arg1 ;
+(id)handlerWithToken:(id)arg1 ;
-(void)didReceiveResponse:(id)arg1 ;
-(id)realm;
-(void)setRequest:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(id)request;
-(id)requestBody;
-(id)token;
-(void)setToken:(id)arg1 ;
-(void)setPolicyVersion:(id)arg1 ;
-(void)launchMethodInvocation;
-(void)setTryCounter:(long long)arg1 ;
-(void)setStartInvocationDate:(id)arg1 ;
-(id)policyVersion;
-(void)didStopWithError:(id)arg1 ;
-(long long)tryCounter;
-(id)startInvocationDate;
-(bool)isConnectionError:(id)arg1 ;
-(bool)shouldRetryMethodInvocationAfterError:(id)arg1 ;
@end

