/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACFHTTPMethodInvocationDelegate.h>

@class NSString, NSDictionary, ACFHTTPMethodInvocation, NSData;

@interface ACMHTTPHandler : NSObject <ACFHTTPMethodInvocationDelegate> {

	NSString* _address;
	NSString* _httpMethod;
	NSDictionary* _httpHeader;
	NSDictionary* _httpGETParameters;
	ACFHTTPMethodInvocation* _methodInvocation;
	double _timeout;
	bool _isCanceled;
	/*^block*/ id _finalizeBlock;
	/*^block*/ id _completionBlock;

}

@property (nonatomic,copy) id finalizeBlock;                                      //@synthesize finalizeBlock=_finalizeBlock - In the implementation block
@property (nonatomic,copy) id completionBlock;                                    //@synthesize completionBlock=_completionBlock - In the implementation block
@property (retain) NSString * httpMethod;                                         //@synthesize httpMethod=_httpMethod - In the implementation block
@property (retain) NSDictionary * httpHeader;                                     //@synthesize httpHeader=_httpHeader - In the implementation block
@property (retain) NSDictionary * httpGETParameters;                              //@synthesize httpGETParameters=_httpGETParameters - In the implementation block
@property (retain) NSString * address;                                            //@synthesize address=_address - In the implementation block
@property (assign) double timeout;                                                //@synthesize timeout=_timeout - In the implementation block
@property (nonatomic,readonly) NSData * httpPOSTBody; 
@property (nonatomic,readonly) NSDictionary * httpRequestDictionary; 
@property (nonatomic,readonly) NSDictionary * requestHeader; 
@property (nonatomic,readonly) NSDictionary * requestBody; 
@property (assign,nonatomic) bool isCanceled;                                     //@synthesize isCanceled=_isCanceled - In the implementation block
@property (retain) ACFHTTPMethodInvocation * methodInvocation;                    //@synthesize methodInvocation=_methodInvocation - In the implementation block
+(id)handler;
+(id)requestString:(id)arg1 ;
+(id)responseWithData:(id)arg1 error:(id*)arg2 ;
-(void)setAddress:(id)arg1 ;
-(void)didReceiveResponse:(id)arg1 ;
-(void)setTimeout:(double)arg1 ;
-(double)timeout;
-(bool)isCanceled;
-(void)dealloc;
-(id)init;
-(void)applicationWillEnterForeground:(id)arg1 ;
-(void)setCompletionBlock:(/*^block*/ id)arg1 ;
-(/*^block*/ id)completionBlock;
-(id)requestBody;
-(id)httpMethod;
-(id)address;
-(void)setFinalizeBlock:(/*^block*/ id)arg1 ;
-(void)launchMethodInvocation;
-(void)setHttpHeader:(id)arg1 ;
-(void)setHttpMethod:(id)arg1 ;
-(void)setHttpGETParameters:(id)arg1 ;
-(id)methodInvocation;
-(void)setMethodInvocation:(id)arg1 ;
-(void)setIsCanceled:(bool)arg1 ;
-(void)requestWillCanceled;
-(id)requestHeader;
-(id)httpRequestDictionary;
-(/*^block*/ id)finalizeBlock;
-(void)callCompletionBlockWithResponse:(id)arg1 error:(id)arg2 ;
-(id)convertToACMError:(id)arg1 ;
-(id)httpGETParameters;
-(id)urlWithRequest:(id)arg1 ;
-(id)httpHeader;
-(id)httpPOSTBody;
-(void)finalizeInvocation;
-(void)cancelMethodInvocation;
-(void)httpMethodInvocation:(id)arg1 didFinishWithResult:(id)arg2 ;
-(void)httpMethodInvocation:(id)arg1 didFailWithError:(id)arg2 ;
-(id)httpMethodInvocation:(id)arg1 credentialForProtectionSpace:(id)arg2 ;
-(void)didStopWithError:(id)arg1 ;
-(void)didStopWithResponse:(id)arg1 ;
@end

