/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:47 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/libacmobileshim.dylib-Structs.h>
#import <libacmobileshim.dylib/ACMiTunesSignInDialog.h>

@interface ACMiTunesSignInDialog_Legacy : ACMiTunesSignInDialog
-(void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2 ;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2 ;
-(void)loadView;
-(void)willPresentAlertView:(id)arg1 ;
-(CGRect)userNameFrame;
-(CGRect)passwordFrame;
-(void)handleRotation;
-(void)handleTextFieldShouldReturnOnNonPasswordField;
@end

