/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface ACMKeychainManager : NSObject
+(id)sharedInstance;
-(id)universalAccessGroup;
-(id)obtainAccessGroup;
-(void)dumpResults:(id)arg1 printAttributes:(bool)arg2 ;
-(id)searchItemWithInfo:(id)arg1 ;
-(void)dumpResults:(id)arg1 ;
-(id)sharedAccessGroup;
-(int)storeItemWithInfo:(id)arg1 share:(bool)arg2 result:(id*)arg3 ;
-(bool)removeItemWithInfo:(id)arg1 ;
@end

