/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/libacmobileshim.dylib-Structs.h>
#import <CoreFoundation/NSCopying.h>

@class NSMutableDictionary, NSString, NSDate, NSData;

@interface ACMKeychainItemInfo : NSObject <NSCopying> {

	NSMutableDictionary* _attributeDictionary;

}

@property (retain) id classCode; 
@property (retain) NSString * accessGroup; 
@property (retain) NSDate * creationDate; 
@property (retain) NSDate * modificationDate; 
@property (retain) NSString * description; 
@property (retain) NSString * comment; 
@property (assign) unsigned long long creator; 
@property (assign) unsigned long long type; 
@property (retain) NSString * label; 
@property (assign) bool isInvisible; 
@property (assign) bool isNegative; 
@property (retain) NSString * account; 
@property (retain) NSString * service; 
@property (retain) NSData * generic; 
@property (retain) id valueRef; 
@property (retain) id valueData; 
@property (retain) id valuePersistentRef; 
@property (assign) bool isPermanent; 
@property (retain) id keyType; 
@property (retain) NSData * applicationTag; 
@property (copy) NSString * applicationTagString; 
@property (retain) NSString * genericString; 
@property (assign) bool returnData; 
@property (assign) bool returnAttributes; 
@property (assign) bool returnRef; 
@property (assign) bool returnPersistentRef; 
@property (assign) unsigned long long returnLimit; 
@property (retain) NSMutableDictionary * attributeDictionary;              //@synthesize attributeDictionary=_attributeDictionary - In the implementation block
+(id)keychainItemInfoWithAttributes:(id)arg1 ;
+(id)keychainItemInfo;
-(void)setComment:(id)arg1 ;
-(id)service;
-(bool)isNegative;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setType:(unsigned long long)arg1 ;
-(unsigned long long)type;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)label;
-(void)setLabel:(id)arg1 ;
-(id)attributes;
-(bool)isInvisible;
-(id)account;
-(void)setAccount:(id)arg1 ;
-(void)setService:(id)arg1 ;
-(id)valueData;
-(void)setValueData:(id)arg1 ;
-(unsigned long long)creator;
-(id)keyType;
-(void)setModificationDate:(id)arg1 ;
-(id)creationDate;
-(id)modificationDate;
-(id)initWithAttributes:(id)arg1 ;
-(void)setCreationDate:(id)arg1 ;
-(id)comment;
-(void)setDescription:(id)arg1 ;
-(void)setAttributeDictionary:(id)arg1 ;
-(id)attributeDictionary;
-(void)setApplicationTag:(id)arg1 ;
-(id)applicationTag;
-(void)setGeneric:(id)arg1 ;
-(id)classCode;
-(void)setCreator:(unsigned long long)arg1 ;
-(void)setIsInvisible:(bool)arg1 ;
-(void)setIsNegative:(bool)arg1 ;
-(void)setIsPermanent:(bool)arg1 ;
-(bool)isPermanent;
-(void)setKeyType:(id)arg1 ;
-(void)setApplicationTagString:(id)arg1 ;
-(id)applicationTagString;
-(void)setGenericString:(id)arg1 ;
-(id)genericString;
-(void)setValuePersistentRef:(id)arg1 ;
-(id)valuePersistentRef;
-(void)setReturnData:(bool)arg1 ;
-(bool)returnData;
-(bool)returnAttributes;
-(bool)returnRef;
-(void)setReturnPersistentRef:(bool)arg1 ;
-(bool)returnPersistentRef;
-(unsigned long long)returnLimit;
-(void)setAccessGroup:(id)arg1 ;
-(id)accessGroup;
-(void)setReturnLimit:(unsigned long long)arg1 ;
-(void)setReturnAttributes:(bool)arg1 ;
-(void)setClassCode:(id)arg1 ;
-(void)setReturnRef:(bool)arg1 ;
-(id)valueRef;
-(void)setValueRef:(id)arg1 ;
-(id)generic;
@end

