/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ACMProvisionManagerProtocol <NSObject>
@required
-(id)publicKeyVersionForRealm:(id)arg1;
-(SecKeyRef)publicKeyForRealm:(id)arg1;
-(void)clearPublicKeyForRealm:(id)arg1;
-(SecIdentityRef)deviceIdentityForRealm:(id)arg1;
-(id)deviceIdentityCertificatesForRealm:(id)arg1;
-(void)clearDeviceIdentityForRealm:(id)arg1;
-(bool)isDeviceIdentityValidForRealm:(id)arg1;
-(SecCertificateRef)defaultPublicKeyCertificateForRealm:(id)arg1;
-(id)defaultPublicKeyVersionForRealm:(id)arg1;
-(bool)setPublicKeyWithCertificate:(SecCertificateRef)arg1 version:(id)arg2 forRealm:(id)arg3;
@end

