/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:47 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/libacmobileshim.dylib-Structs.h>
#import <libacmobileshim.dylib/ACMSignInDialog.h>

@class UIButton, UIImage, UITextView, UIColor, NSString, UIView;

@interface ACMSignInDialogSimple : ACMSignInDialog {

	UIButton* _loginButton;
	UIButton* _cancelButton;
	UIImage* _logo;
	UITextView* _licenseTextField;
	UIColor* _backgroundColor;
	NSString* _accountNameFieldPlaceholder;
	UIView* _backgroudView;

}

@property (retain) UIImage * logo;                                            //@synthesize logo=_logo - In the implementation block
@property (retain) UIColor * backgroundColor;                                 //@synthesize backgroundColor=_backgroundColor - In the implementation block
@property (retain) NSString * licenseText; 
@property (retain) UIColor * licenseTextColor; 
@property (retain) NSString * accountNameFieldPlaceholder;                    //@synthesize accountNameFieldPlaceholder=_accountNameFieldPlaceholder - In the implementation block
@property (nonatomic,retain) UIView * backgroudView;                          //@synthesize backgroudView=_backgroudView - In the implementation block
@property (nonatomic,readonly) UITextView * licenseTextField; 
@property (nonatomic,readonly) unsigned long long verticalShift; 
@property (nonatomic,readonly) UIButton * loginButton;                        //@synthesize loginButton=_loginButton - In the implementation block
@property (nonatomic,readonly) UIButton * cancelButton;                       //@synthesize cancelButton=_cancelButton - In the implementation block
+(id)dialog;
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1 ;
-(id)backgroundColor;
-(void)loadView;
-(bool)textFieldShouldBeginEditing:(id)arg1 ;
-(bool)textField:(id)arg1 shouldChangeCharactersInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(bool)textFieldShouldClear:(id)arg1 ;
-(bool)textFieldShouldReturn:(id)arg1 ;
-(id)cancelButton;
-(bool)shouldAutorotateToInterfaceOrientation:(long long)arg1 ;
-(void)viewWillAppear:(bool)arg1 ;
-(id)passwordString;
-(void)focus;
-(id)logo;
-(void)setLogo:(id)arg1 ;
-(void)checkFields;
-(void)onSignIn:(id)arg1 ;
-(void)disableControls:(bool)arg1 ;
-(void)setLicenseText:(id)arg1 ;
-(void)setLicenseTextColor:(id)arg1 ;
-(void)setAccountNameFieldPlaceholder:(id)arg1 ;
-(id)loginButton;
-(id)licenseTextField;
-(unsigned long long)verticalShift;
-(id)licenseText;
-(id)licenseTextColor;
-(id)userNameString;
-(id)backgroudView;
-(void)setBackgroudView:(id)arg1 ;
-(id)accountNameFieldPlaceholder;
@end

