/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:48 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMSignInDialogSimple.h>

@interface ACMSignInDialogSimple_Modern : ACMSignInDialogSimple {

	double _backgroundHorizontalParallaxValue;
	double _backgroundVerticalParallaxValue;

}
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)backgroundColor;
-(id)init;
-(void)didReceiveMemoryWarning;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)loadView;
-(id)cancelButton;
-(void)updateViewConstraints;
-(id)imageView;
-(id)passwordField;
-(id)accountNameField;
-(id)loginButton;
-(void)setupBackgroundViewIfNeeded;
-(void)setupParallaxParameters;
-(void)setParallaxEffectForView:(id)arg1 ;
-(void)setupView;
-(void)centerHorizontallyView:(id)arg1 relativeToView:(id)arg2 ;
-(id)buttonsContainerView;
-(id)defaultBackgroundPatternImage;
@end

