/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class ACMInitialToken, NSString;

@interface ACMServiceTicket : NSObject {

	ACMInitialToken* _initialToken;
	id _publicKey;
	id _deviceIdentity;

}

@property (nonatomic,readonly) ACMInitialToken * initialToken;              //@synthesize initialToken=_initialToken - In the implementation block
@property (retain) id publicKey;                                            //@synthesize publicKey=_publicKey - In the implementation block
@property (retain) id deviceIdentity;                                       //@synthesize deviceIdentity=_deviceIdentity - In the implementation block
@property (nonatomic,readonly) NSString * tokenString; 
+(id)serviceTicketWithRequest:(id)arg1 ssoToken:(id)arg2 initialTokenClass:(Class)arg3 ;
-(void)dealloc;
-(id)initialToken;
-(void)setPublicKey:(id)arg1 ;
-(id)publicKey;
-(id)tokenString;
-(void)setDeviceIdentity:(id)arg1 ;
-(id)deviceIdentity;
@end

