/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ACMSignInDialogProtocol <NSObject>
@property (assign) <ACMSignInDialogDelegate> * delegate; 
@property (retain) ACMExternalAuthenticationRequestImpl * request; 
@property (readonly) NSString * passwordString; 
@required
-(void)setRequest:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id)delegate;
-(id)request;
-(id)passwordString;
-(void)showWithParentViewController:(id)arg1 animated:(bool)arg2;
-(void)hideWithParentViewController:(id)arg1 animated:(bool)arg2;
@end

