/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/libacmobileshim.dylib-Structs.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITextFieldDelegate.h>

@protocol ACMSignInWidgetDelegate;
@class UITableView, UITableViewCell, UITextField, UILabel, NSString;

@interface ACMSignInWidget : NSObject <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate> {

	<ACMSignInWidgetDelegate>* _delegate;
	UITableView* _table;
	UITableViewCell* _accountEditCell;
	UITableViewCell* _passwordEditCell;
	UITextField* _accountField;
	UITextField* _passwordField;
	UILabel* _accountLabel;
	NSString* _textFieldValueBeforeEditing;
	NSString* _textFieldValueAfterEditing;
	long long _undoRedoField;
	NSString* _accountNameText;
	NSString* _passwordText;
	unsigned long long _accountNameFieldCursorPosition;
	unsigned long long _passwordFieldCursorPosition;

}

@property (assign,nonatomic) <ACMSignInWidgetDelegate> * delegate;                           //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) UITableView * table; 
@property (nonatomic,readonly) UITableViewCell * accountEditCell; 
@property (nonatomic,readonly) UITableViewCell * passwordEditCell; 
@property (nonatomic,readonly) UILabel * accountLabel; 
@property (retain) UITextField * accountField;                                               //@synthesize accountField=_accountField - In the implementation block
@property (retain) UITextField * passwordField;                                              //@synthesize passwordField=_passwordField - In the implementation block
@property (assign,nonatomic) CGPoint position; 
@property (nonatomic,retain) NSString * accountNameText;                                     //@synthesize accountNameText=_accountNameText - In the implementation block
@property (nonatomic,retain) NSString * passwordText;                                        //@synthesize passwordText=_passwordText - In the implementation block
@property (assign,nonatomic) unsigned long long accountNameFieldCursorPosition;              //@synthesize accountNameFieldCursorPosition=_accountNameFieldCursorPosition - In the implementation block
@property (assign,nonatomic) unsigned long long passwordFieldCursorPosition;                 //@synthesize passwordFieldCursorPosition=_passwordFieldCursorPosition - In the implementation block
@property (nonatomic,retain) NSString * textFieldValueBeforeEditing;                         //@synthesize textFieldValueBeforeEditing=_textFieldValueBeforeEditing - In the implementation block
@property (nonatomic,retain) NSString * textFieldValueAfterEditing;                          //@synthesize textFieldValueAfterEditing=_textFieldValueAfterEditing - In the implementation block
@property (assign,nonatomic) long long undoRedoField;                                        //@synthesize undoRedoField=_undoRedoField - In the implementation block
+(id)widget;
-(void)setPasswordField:(id)arg1 ;
-(id)accountLabel;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id)delegate;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2 ;
-(void)setPosition:(CGPoint)arg1 ;
-(CGPoint)position;
-(void)textFieldDidBeginEditing:(id)arg1 ;
-(void)textFieldDidEndEditing:(id)arg1 ;
-(bool)textField:(id)arg1 shouldChangeCharactersInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(bool)textFieldShouldClear:(id)arg1 ;
-(bool)textFieldShouldReturn:(id)arg1 ;
-(id)table;
-(id)passwordField;
-(void)undoManagerDidUndo:(id)arg1 ;
-(void)undoManagerDidRedo:(id)arg1 ;
-(void)setAccountNameText:(id)arg1 ;
-(void)setPasswordText:(id)arg1 ;
-(void)setTextFieldValueBeforeEditing:(id)arg1 ;
-(void)setTextFieldValueAfterEditing:(id)arg1 ;
-(id)accountField;
-(void)setAccountField:(id)arg1 ;
-(id)accountEditCell;
-(id)passwordEditCell;
-(id)accountNameText;
-(unsigned long long)accountNameFieldCursorPosition;
-(id)passwordText;
-(unsigned long long)passwordFieldCursorPosition;
-(long long)undoRedoField;
-(id)textFieldValueBeforeEditing;
-(id)textFieldValueAfterEditing;
-(void)onSignIn:(id)arg1 ;
-(void)setUndoRedoField:(long long)arg1 ;
-(void)setAccountNameFieldCursorPosition:(unsigned long long)arg1 ;
-(void)setPasswordFieldCursorPosition:(unsigned long long)arg1 ;
-(void)onIForgot:(id)arg1 ;
-(void)checkTextFields;
-(void)disableControls:(bool)arg1 ;
@end

