/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:47 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMTicketVerificationResponse.h>

@class NSNumber, NSDictionary, NSError;

@interface ACMTicketVerificationResponseImpl : NSObject <ACMTicketVerificationResponse> {

	NSDictionary* _rawResponseData;
	NSError* _error;
	id _userInfo;

}

@property (retain) id userInfo;                                 //@synthesize userInfo=_userInfo - In the implementation block
@property (retain) NSDictionary * rawResponseData;              //@synthesize rawResponseData=_rawResponseData - In the implementation block
@property (retain) NSError * error;                             //@synthesize error=_error - In the implementation block
@property (readonly) NSNumber * personDSID; 
-(void)setError:(id)arg1 ;
-(void)dealloc;
-(id)userInfo;
-(void)setUserInfo:(id)arg1 ;
-(id)error;
-(void)setRawResponseData:(id)arg1 ;
-(id)rawResponseData;
-(id)personDSID;
@end

