/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAXSafeCategoryBundle.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <libAXSafeCategoryBundle.dylib/libAXSafeCategoryBundle.dylib-Structs.h>
@class NSString;

@interface UIAccessibilitySafeCategory : NSObject

@property (nonatomic,@dynamic,copy) NSString * accessibilityIdentifier; 
+(void)installCategoryOnClassNamed:(id)arg1 ;
+(id)installCategoryOnClassNamed:(id)arg1 isManaged:(bool)arg2 ;
+(id)installLocalValidationMethodOnClassNamed:(id)arg1 ;
+(void)_addCategoryMethod:(objc_methodRef)arg1 toClass:(Class)arg2 isClass:(bool)arg3 ;
@end

