/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufPower.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufPower.dylib/libAWDProtobufPower.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDAppUsageInfo : PBCodable <NSCopying> {

	unsigned _appBGCount;
	unsigned _appBGDuration;
	NSString* _appBundleId;
	unsigned _appFGCount;
	unsigned _appFGDuration;
	SCD_Struct_AW2 _has;

}

@property (nonatomic,readonly) bool hasAppBundleId; 
@property (nonatomic,retain) NSString * appBundleId;              //@synthesize appBundleId=_appBundleId - In the implementation block
@property (assign,nonatomic) bool hasAppFGDuration; 
@property (assign,nonatomic) unsigned appFGDuration;              //@synthesize appFGDuration=_appFGDuration - In the implementation block
@property (assign,nonatomic) bool hasAppFGCount; 
@property (assign,nonatomic) unsigned appFGCount;                 //@synthesize appFGCount=_appFGCount - In the implementation block
@property (assign,nonatomic) bool hasAppBGDuration; 
@property (assign,nonatomic) unsigned appBGDuration;              //@synthesize appBGDuration=_appBGDuration - In the implementation block
@property (assign,nonatomic) bool hasAppBGCount; 
@property (assign,nonatomic) unsigned appBGCount;                 //@synthesize appBGCount=_appBGCount - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setAppBundleId:(id)arg1 ;
-(bool)hasAppBundleId;
-(void)setAppFGDuration:(unsigned)arg1 ;
-(void)setHasAppFGDuration:(bool)arg1 ;
-(bool)hasAppFGDuration;
-(void)setAppFGCount:(unsigned)arg1 ;
-(void)setHasAppFGCount:(bool)arg1 ;
-(bool)hasAppFGCount;
-(void)setAppBGDuration:(unsigned)arg1 ;
-(void)setHasAppBGDuration:(bool)arg1 ;
-(bool)hasAppBGDuration;
-(void)setAppBGCount:(unsigned)arg1 ;
-(void)setHasAppBGCount:(bool)arg1 ;
-(bool)hasAppBGCount;
-(id)appBundleId;
-(unsigned)appFGDuration;
-(unsigned)appFGCount;
-(unsigned)appBGDuration;
-(unsigned)appBGCount;
@end

