/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufPower.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufPower.dylib/libAWDProtobufPower.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDNetworkUsageInfo : PBCodable <NSCopying> {

	unsigned long long _cellIn;
	unsigned long long _cellOut;
	unsigned long long _wifiIn;
	unsigned long long _wifiOut;
	NSString* _processName;
	SCD_Struct_AW2 _has;

}

@property (nonatomic,readonly) bool hasProcessName; 
@property (nonatomic,retain) NSString * processName;                  //@synthesize processName=_processName - In the implementation block
@property (assign,nonatomic) bool hasWifiIn; 
@property (assign,nonatomic) unsigned long long wifiIn;               //@synthesize wifiIn=_wifiIn - In the implementation block
@property (assign,nonatomic) bool hasWifiOut; 
@property (assign,nonatomic) unsigned long long wifiOut;              //@synthesize wifiOut=_wifiOut - In the implementation block
@property (assign,nonatomic) bool hasCellIn; 
@property (assign,nonatomic) unsigned long long cellIn;               //@synthesize cellIn=_cellIn - In the implementation block
@property (assign,nonatomic) bool hasCellOut; 
@property (assign,nonatomic) unsigned long long cellOut;              //@synthesize cellOut=_cellOut - In the implementation block
-(void)setProcessName:(id)arg1 ;
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)processName;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(bool)hasProcessName;
-(void)setWifiIn:(unsigned long long)arg1 ;
-(void)setHasWifiIn:(bool)arg1 ;
-(bool)hasWifiIn;
-(void)setWifiOut:(unsigned long long)arg1 ;
-(void)setHasWifiOut:(bool)arg1 ;
-(bool)hasWifiOut;
-(void)setCellIn:(unsigned long long)arg1 ;
-(void)setHasCellIn:(bool)arg1 ;
-(bool)hasCellIn;
-(void)setCellOut:(unsigned long long)arg1 ;
-(void)setHasCellOut:(bool)arg1 ;
-(bool)hasCellOut;
-(unsigned long long)wifiIn;
-(unsigned long long)wifiOut;
-(unsigned long long)cellIn;
-(unsigned long long)cellOut;
@end

