/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufPower.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufPower.dylib/libAWDProtobufPower.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSString;

@interface AWDPerProcessCPULoad : PBCodable <NSCopying> {

	unsigned _duration;
	NSString* _procName;
	SCD_Struct_AW3 _has;

}

@property (nonatomic,readonly) bool hasProcName; 
@property (nonatomic,retain) NSString * procName;              //@synthesize procName=_procName - In the implementation block
@property (assign,nonatomic) bool hasDuration; 
@property (assign,nonatomic) unsigned duration;                //@synthesize duration=_duration - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned)duration;
-(void)setDuration:(unsigned)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(bool)hasDuration;
-(void)setHasDuration:(bool)arg1 ;
-(id)procName;
-(void)setProcName:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(bool)hasProcName;
@end

