/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:44 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufPower.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufPower.dylib/libAWDProtobufPower.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <CoreFoundation/NSCopying.h>

@class NSMutableArray;

@interface AWDPowerMetricSystemStats : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _allAppsCount;
	NSMutableArray* _appInfos;
	unsigned _avgBrightness;
	unsigned _avgMicroAmps;
	NSMutableArray* _backlightBuckets;
	unsigned _cPUEnergyMicroWatt;
	NSMutableArray* _cpuLoads;
	NSMutableArray* _dataUsageInfos;
	unsigned _dispOnCount;
	unsigned _dispOnDuration;
	unsigned _energyChargedMicroWatt;
	unsigned _energyConsumedMicroWatt;
	unsigned _mieCount;
	unsigned _mieDuration;
	SCD_Struct_AW1 _has;

}

@property (assign,nonatomic) bool hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                   //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) bool hasDispOnDuration; 
@property (assign,nonatomic) unsigned dispOnDuration;                        //@synthesize dispOnDuration=_dispOnDuration - In the implementation block
@property (assign,nonatomic) bool hasDispOnCount; 
@property (assign,nonatomic) unsigned dispOnCount;                           //@synthesize dispOnCount=_dispOnCount - In the implementation block
@property (assign,nonatomic) bool hasAvgMicroAmps; 
@property (assign,nonatomic) unsigned avgMicroAmps;                          //@synthesize avgMicroAmps=_avgMicroAmps - In the implementation block
@property (assign,nonatomic) bool hasAvgBrightness; 
@property (assign,nonatomic) unsigned avgBrightness;                         //@synthesize avgBrightness=_avgBrightness - In the implementation block
@property (assign,nonatomic) bool hasMieDuration; 
@property (assign,nonatomic) unsigned mieDuration;                           //@synthesize mieDuration=_mieDuration - In the implementation block
@property (assign,nonatomic) bool hasMieCount; 
@property (assign,nonatomic) unsigned mieCount;                              //@synthesize mieCount=_mieCount - In the implementation block
@property (nonatomic,retain) NSMutableArray * appInfos;                      //@synthesize appInfos=_appInfos - In the implementation block
@property (assign,nonatomic) bool hasAllAppsCount; 
@property (assign,nonatomic) unsigned allAppsCount;                          //@synthesize allAppsCount=_allAppsCount - In the implementation block
@property (nonatomic,retain) NSMutableArray * dataUsageInfos;                //@synthesize dataUsageInfos=_dataUsageInfos - In the implementation block
@property (nonatomic,retain) NSMutableArray * cpuLoads;                      //@synthesize cpuLoads=_cpuLoads - In the implementation block
@property (assign,nonatomic) bool hasCPUEnergyMicroWatt; 
@property (assign,nonatomic) unsigned cPUEnergyMicroWatt;                    //@synthesize cPUEnergyMicroWatt=_cPUEnergyMicroWatt - In the implementation block
@property (assign,nonatomic) bool hasEnergyConsumedMicroWatt; 
@property (assign,nonatomic) unsigned energyConsumedMicroWatt;               //@synthesize energyConsumedMicroWatt=_energyConsumedMicroWatt - In the implementation block
@property (assign,nonatomic) bool hasEnergyChargedMicroWatt; 
@property (assign,nonatomic) unsigned energyChargedMicroWatt;                //@synthesize energyChargedMicroWatt=_energyChargedMicroWatt - In the implementation block
@property (nonatomic,retain) NSMutableArray * backlightBuckets;              //@synthesize backlightBuckets=_backlightBuckets - In the implementation block
-(void)dealloc;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(id)dictionaryRepresentation;
-(bool)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setHasTimestamp:(bool)arg1 ;
-(bool)hasTimestamp;
-(void)setAppInfos:(id)arg1 ;
-(void)setDataUsageInfos:(id)arg1 ;
-(void)setCpuLoads:(id)arg1 ;
-(void)setBacklightBuckets:(id)arg1 ;
-(void)addAppInfo:(id)arg1 ;
-(void)addDataUsageInfo:(id)arg1 ;
-(void)addCpuLoad:(id)arg1 ;
-(void)addBacklightBucket:(id)arg1 ;
-(unsigned long long)appInfosCount;
-(void)clearAppInfos;
-(id)appInfoAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)dataUsageInfosCount;
-(void)clearDataUsageInfos;
-(id)dataUsageInfoAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)cpuLoadsCount;
-(void)clearCpuLoads;
-(id)cpuLoadAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)backlightBucketsCount;
-(void)clearBacklightBuckets;
-(id)backlightBucketAtIndex:(unsigned long long)arg1 ;
-(void)setDispOnDuration:(unsigned)arg1 ;
-(void)setHasDispOnDuration:(bool)arg1 ;
-(bool)hasDispOnDuration;
-(void)setDispOnCount:(unsigned)arg1 ;
-(void)setHasDispOnCount:(bool)arg1 ;
-(bool)hasDispOnCount;
-(void)setAvgMicroAmps:(unsigned)arg1 ;
-(void)setHasAvgMicroAmps:(bool)arg1 ;
-(bool)hasAvgMicroAmps;
-(void)setAvgBrightness:(unsigned)arg1 ;
-(void)setHasAvgBrightness:(bool)arg1 ;
-(bool)hasAvgBrightness;
-(void)setMieDuration:(unsigned)arg1 ;
-(void)setHasMieDuration:(bool)arg1 ;
-(bool)hasMieDuration;
-(void)setMieCount:(unsigned)arg1 ;
-(void)setHasMieCount:(bool)arg1 ;
-(bool)hasMieCount;
-(void)setAllAppsCount:(unsigned)arg1 ;
-(void)setHasAllAppsCount:(bool)arg1 ;
-(bool)hasAllAppsCount;
-(void)setCPUEnergyMicroWatt:(unsigned)arg1 ;
-(void)setHasCPUEnergyMicroWatt:(bool)arg1 ;
-(bool)hasCPUEnergyMicroWatt;
-(void)setEnergyConsumedMicroWatt:(unsigned)arg1 ;
-(void)setHasEnergyConsumedMicroWatt:(bool)arg1 ;
-(bool)hasEnergyConsumedMicroWatt;
-(void)setEnergyChargedMicroWatt:(unsigned)arg1 ;
-(void)setHasEnergyChargedMicroWatt:(bool)arg1 ;
-(bool)hasEnergyChargedMicroWatt;
-(unsigned)dispOnDuration;
-(unsigned)dispOnCount;
-(unsigned)avgMicroAmps;
-(unsigned)avgBrightness;
-(unsigned)mieDuration;
-(unsigned)mieCount;
-(id)appInfos;
-(unsigned)allAppsCount;
-(id)dataUsageInfos;
-(id)cpuLoads;
-(unsigned)cPUEnergyMicroWatt;
-(unsigned)energyConsumedMicroWatt;
-(unsigned)energyChargedMicroWatt;
-(id)backlightBuckets;
@end

