/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAXSpeechManager.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, TTSSpeechRequest;

@interface AXSpeechAction : NSObject {

	NSString* _string;
	double _pitch;
	double _volume;
	double _speakingRate;
	NSString* _language;
	bool _shouldQueue;
	bool _cannotInterrupt;
	bool _shouldDetectLanguage;
	bool _shouldProcessEmoji;
	bool _shouldPrecomposeString;
	/*^block*/ id _completionCallback;
	/*^block*/ id _onPauseCallback;
	/*^block*/ id _onResumeCallback;
	/*^block*/ id _onWillSpeakRangeCallback;
	/*^block*/ id _onSpeechStartCallback;
	TTSSpeechRequest* _speechRequest;

}

@property (assign,nonatomic) bool shouldQueue;                              //@synthesize shouldQueue=_shouldQueue - In the implementation block
@property (assign,nonatomic) bool cannotInterrupt;                          //@synthesize cannotInterrupt=_cannotInterrupt - In the implementation block
@property (assign,nonatomic) bool shouldDetectLanguage;                     //@synthesize shouldDetectLanguage=_shouldDetectLanguage - In the implementation block
@property (assign,nonatomic) bool shouldProcessEmoji;                       //@synthesize shouldProcessEmoji=_shouldProcessEmoji - In the implementation block
@property (assign,nonatomic) bool shouldPrecomposeString;                   //@synthesize shouldPrecomposeString=_shouldPrecomposeString - In the implementation block
@property (nonatomic,copy) NSString * string;                               //@synthesize string=_string - In the implementation block
@property (nonatomic,retain) NSString * language;                           //@synthesize language=_language - In the implementation block
@property (nonatomic,copy) id completionCallback;                           //@synthesize completionCallback=_completionCallback - In the implementation block
@property (nonatomic,copy) id onPauseCallback;                              //@synthesize onPauseCallback=_onPauseCallback - In the implementation block
@property (nonatomic,copy) id onResumeCallback;                             //@synthesize onResumeCallback=_onResumeCallback - In the implementation block
@property (nonatomic,copy) id onWillSpeakRangeCallback;                     //@synthesize onWillSpeakRangeCallback=_onWillSpeakRangeCallback - In the implementation block
@property (nonatomic,copy) id onSpeechStartCallback;                        //@synthesize onSpeechStartCallback=_onSpeechStartCallback - In the implementation block
@property (assign,nonatomic) double speakingRate;                           //@synthesize speakingRate=_speakingRate - In the implementation block
@property (assign,nonatomic) double pitch;                                  //@synthesize pitch=_pitch - In the implementation block
@property (assign,nonatomic) double volume;                                 //@synthesize volume=_volume - In the implementation block
@property (nonatomic,retain) TTSSpeechRequest * speechRequest;              //@synthesize speechRequest=_speechRequest - In the implementation block
+(id)actionWithString:(id)arg1 shouldQueue:(bool)arg2 ;
-(void)dealloc;
-(id)init;
-(id)description;
-(id)string;
-(void)setString:(id)arg1 ;
-(id)language;
-(void)setLanguage:(id)arg1 ;
-(id)speechRequest;
-(void)setSpeechRequest:(id)arg1 ;
-(double)pitch;
-(void)setPitch:(double)arg1 ;
-(double)volume;
-(void)setVolume:(double)arg1 ;
-(void)setShouldQueue:(bool)arg1 ;
-(id)_detectLanguageFromContent;
-(void)preprocessAction;
-(double)speakingRate;
-(void)setSpeakingRate:(double)arg1 ;
-(bool)shouldQueue;
-(bool)cannotInterrupt;
-(void)setCannotInterrupt:(bool)arg1 ;
-(bool)shouldProcessEmoji;
-(void)setShouldProcessEmoji:(bool)arg1 ;
-(bool)shouldPrecomposeString;
-(void)setShouldPrecomposeString:(bool)arg1 ;
-(bool)shouldDetectLanguage;
-(void)setShouldDetectLanguage:(bool)arg1 ;
-(/*^block*/ id)completionCallback;
-(void)setCompletionCallback:(/*^block*/ id)arg1 ;
-(/*^block*/ id)onPauseCallback;
-(void)setOnPauseCallback:(/*^block*/ id)arg1 ;
-(/*^block*/ id)onResumeCallback;
-(void)setOnResumeCallback:(/*^block*/ id)arg1 ;
-(/*^block*/ id)onWillSpeakRangeCallback;
-(void)setOnWillSpeakRangeCallback:(/*^block*/ id)arg1 ;
-(/*^block*/ id)onSpeechStartCallback;
-(void)setOnSpeechStartCallback:(/*^block*/ id)arg1 ;
@end

