/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:49 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libobjc.A.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <libobjc.A.dylib/libobjc.A.dylib-Structs.h>
@interface Protocol : NSObject
+(void)load;
-(bool)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(const char*)name;
-(bool)conformsTo:(id)arg1 ;
-(objc_method_description*)descriptionForInstanceMethod:(SEL)arg1 ;
-(objc_method_description*)descriptionForClassMethod:(SEL)arg1 ;
@end

