/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:49 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_dispatch_object.h>
#import <libdispatch.dylib/OS_dispatch_semaphore.h>

@protocol OS_dispatch_semaphore <OS_dispatch_object>@end


@interface OS_dispatch_semaphore : OS_dispatch_object <OS_dispatch_semaphore>
+(void)load;
@end

