/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:50 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libdispatch.dylib/libdispatch.dylib-Structs.h>
#import <Foundation/_NSDispatchData.h>
#import <libdispatch.dylib/OS_dispatch_data.h>

@protocol OS_dispatch_data <OS_dispatch_object>@end


@interface OS_dispatch_data : _NSDispatchData <OS_dispatch_data>
+(id)allocWithZone:(NSZone)arg1 ;
-(id)initWithBytes:(void*)arg1 length:(unsigned long long)arg2 copy:(bool)arg3 freeWhenDone:(bool)arg4 bytesAreVM:(bool)arg5 ;
-(void)dealloc;
-(id)init;
-(id)debugDescription;
-(void)_setContext:(void*)arg1 ;
-(void)_setTargetQueue:(id)arg1 ;
-(void)finalize;
-(void*)_getContext;
-(void)_setFinalizer:(/*function pointer*/ void*)arg1 ;
-(bool)_bytesAreVM;
@end

