/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:50 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/system/libxpc.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libxpc.dylib/OS_xpc_object.h>
#import <libxpc.dylib/OS_xpc_fd.h>

@protocol OS_xpc_fd <OS_xpc_object>@end


@interface OS_xpc_fd : OS_xpc_object <OS_xpc_fd>
+(void)load;
@end

