/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libTelephonyUtilDynamic.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct weak_ptr<ctu::Http::URLConnectionCallbackHandler> {
	URLConnectionCallbackHandler __ptr_;
	__shared_weak_count __cntrl_;
} weak_ptr<ctu::Http::URLConnectionCallbackHandler>;

typedef struct shared_ptr<ctu::Http::HttpResponse> {
	HttpResponse __ptr_;
	__shared_weak_count __cntrl_;
} shared_ptr<ctu::Http::HttpResponse>;

