/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:46 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libTelephonyUtilDynamic.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libTelephonyUtilDynamic.dylib/libTelephonyUtilDynamic.dylib-Structs.h>
#import <libTelephonyUtilDynamic.dylib/NSURLConnectionDelegate.h>

@class NSMutableData;

@interface URLConnectionDelegate : NSObject <NSURLConnectionDelegate> {

	NSMutableData* fData;
	weak_ptr<ctu::Http::URLConnectionCallbackHandler>* fHandler;
	shared_ptr<ctu::Http::HttpResponse>* fResponse;

}
-(void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4 ;
-(void)dealloc;
-(id).cxx_construct;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(void).cxx_destruct;
-(void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2 ;
-(shared_ptr<ctu::Http::URLConnectionCallbackHandler>*)getHandler;
-(id)initWithCallbackHandler:(shared_ptr<ctu::Http::URLConnectionCallbackHandler>*)arg1 ;
@end

