/*
* This header is generated by classdump-dyld 0.2
* on Tuesday, October 21, 2014 at 10:03:45 PM Eastern European Summer Time
* Operating System: Version 7.1 (Build 11D167)
* Image Source: /usr/lib/libAWDProtobufVPN.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	unsigned inBytes : 1;
	unsigned outBytes : 1;
	unsigned timestamp : 1;
	unsigned disconnectReason : 1;
	unsigned duration : 1;
	unsigned ipv4Installed : 1;
	unsigned ipv6Installed : 1;
	unsigned reassertCount : 1;
	unsigned systemAuthenMethod : 1;
	unsigned triggerTrafficClass : 1;
	unsigned triggerType : 1;
	unsigned userAuthenMethod : 1;
	unsigned appVpnUsed : 1;
	unsigned connectFailed : 1;
	unsigned proxyInstalled : 1;
} SCD_Struct_AW1;

